Vizzuality/marxan-cloud

- app/components/button/component.tsx
- app/components/forms/checkbox/component.stories.tsx
- app/components/forms/checkbox/component.tsx
- app/components/forms/checkbox/index.ts
- app/components/forms/component.stories.tsx
- app/components/forms/field/component.stories.tsx
- app/components/forms/field/component.tsx
- app/components/forms/input/component.tsx
- app/components/forms/label/component.stories.tsx
- app/components/forms/label/component.tsx
- app/components/forms/label/index.ts
- app/components/forms/radio/component.stories.tsx
- app/components/forms/radio/component.tsx
- app/components/forms/radio/index.ts
- app/components/forms/textarea/component.tsx
- app/components/forms/validations.ts
- app/package.json
- app/tailwind.config.js
- app/yarn.lock
This PR adds:
- Checkbox component
- Radio component
- Label component
> Form components

- app/.storybook/preview.js
- app/components/map/component.stories.tsx
- app/components/map/component.tsx
- app/components/map/index.ts
- app/components/map/layers.ts
- app/package.json
- app/yarn.lock
This PR adds:
- Map component
- Layer Manager
`yarn && yarn storybook:dev`
https://www.pivotaltracker.com/story/show/176243915
> Map component + Layer manager

- api/CHANGELOG.md
- api/package.json
- api/src/main.ts
- api/src/modules/projects/project.entity.ts
- api/src/modules/projects/projects.controller.ts
- api/src/modules/users/user.entity.ts
- api/src/modules/users/users.controller.ts
- api/yarn.lock
This PR:
* adds and configures the NestJS OpenAPI plugin
* adds decorators to document the stub users and projects modules
* configures a global API path prefix (`/api/v1`)
N/A
`GET /swagger` should show a minimal Swagger UI.
`GET /swagger-json` should show the JSON spec.
The API documentation for `GET` responses for users and projects does not currently match the JSON:API serialization that is effectively sent. We'll deal with this later.
https://www.pivotaltracker.com/story/show/176205745
---
> API scaffolding - NestJS OpenAPI plugin

- api/CHANGELOG.md
- api/ormconfig.ts
- api/src/app.module.ts
- api/src/migrations/api/1611764861883-AddCascadesToJoinTables.ts
- api/src/modules/geo/admin-region.geo.entity.ts
- api/src/modules/geo/geo.module.ts
- api/src/modules/projects/project.api.entity.ts
- api/src/modules/scenarios/scenario.api.entity.ts
- api/src/ormconfig.ts
- api/src/types/time-user-entity-metadata.ts
- api/src/utils/config.utils.ts
- api/src/utils/cors.utils.ts
- api/src/utils/file-uploads.utils.ts
- geoprocessing/src/migrations/geoprocessing/1611221157285-initialGeoDBSetup.ts
- geoprocessing/src/utils/postgresql.utils.ts
This PR:
* adds all the columns of the current `scenarios` table to the `Scenarios` entity (with some per-prop documentation)
* fixes some missing cascades via a migration
* adds a stub of the `AdminRegion` entity (for the API service), mostly to validate the ORM setup for multiple connections
* refactors the ORM config so that we can easily use multiple connections in NestJS via TypeOrmModule, while sharing configuration code with the ORM CLI utility (`ormconfig.ts`) - as a positive externality of this, updates to the ORM configuration are now effective immediately in development once the app restarts - no need to rebuild the container image anymore 🚀)
* adds a new base class with entity columns which are common to several of our metadata classes (`createdAt`, `createdBy`, …
> scenarios module - part 1

- .gitignore
- Makefile
- api/CHANGELOG.md
- api/Dockerfile
- api/TESTING.md
- api/entrypoint.sh
- api/test/app.e2e-spec.ts
- api/test/jest-e2e.json
- docker-compose-test-e2e.yml
Setup for API e2e tests + actual tests for the endpoints we have so far 🚀 
N/A
Read `api/TESTING.md`, specifically the section about configuring and running e2e tests..
`make test-e2e-api` 🚀 
https://www.pivotaltracker.com/story/show/176715821
---
> API e2e tests - inception

- api/src/modules/countries/countries.controller.ts
- api/src/modules/organizations/organizations.controller.ts
- api/src/modules/scenarios/scenarios.controller.ts
- api/src/modules/scenarios/scenarios.service.ts
- api/src/modules/users/users.controller.ts
- api/src/modules/users/users.service.ts
- api/test/scenarios.e2e-spec.ts
Replace use of fake data from earlier phase of API development with reading/writing of actual data from/to db.
Plus e2e tests for Scenarios and some minor updates to other tests.
N/A
This is a bit tricky to test - basically all endpoints (GET singular or plural, POST, PATCH and DELETE) are now using real data from the API db connection... So I think that short of manually hitting all endpoints, we may assume that I didn't forget to remove wirings (the TypeScript language server shouted at me for some bits I had forgotten during this PR).
In general, I think it's time to start upping our e2e tests to not only check success/failure as expected, but also to check that the data we receive from the API is what we expect - but for the moment, the tests we have don't do this yet. …
> [MARXAN-74] remove fake data wirings

- .github/workflows/api-e2e-tests.yml
- Makefile
- docker-compose-test-e2e.local.yml
- docker-compose-test-e2e.yml
What it says on the tin :)
N/A
GH Actions should run a CI pipeline for API e2e tests, triggered by push with changes in the api or geoprocessing directories.
N/A
---
> GitHub actions workflow definition for API e2e tests

- docker-compose-test-e2e.yml
remove explicit network definition in API e2e tests compose file
N/A
N/A
N/A
---
> remove explicit network definition in API e2e tests compose file

- app/components/tooltip/arrow/component.tsx
- app/components/tooltip/arrow/index.ts
- app/components/tooltip/component.stories.tsx
- app/components/tooltip/component.tsx
This PR adds:
- Tooltip arrow component
https://vizzuality.atlassian.net/browse/MARXAN-132
> Tooltip: arrow

- data/data_download/Dockerfile
- data/data_download/wdpa/Makefile
fixed error  issue with wdpa pipe
Fixed bug that prevented wdpa not running.
`make seed-geodb-data`
---
> fixed error issue with wdpa pipe

- app/components/tooltip/component.tsx
- app/hooks/projects/index.ts
- app/hooks/projects/types.ts
- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/layout/header/title/component.tsx
- app/layout/scenarios/sidebar/name/component.tsx
This PR adds:
- Form instead of titles for allowing project and scenario edition
https://marxan-git-feature-header-title-edition-vizzuality1.vercel.app/projects/b0a14339-732a-430b-a01d-6bc06494b05f/scenarios/374b2483-a5ce-4a76-8b24-f4cafb49aa6b/edit
Go there and edit names. You can try to put a very long name if you want
https://vizzuality.atlassian.net/browse/MARXAN-105
> Header: title edition

- docs/adr/0001_queues.md
ADR draft for  discussion: backend and data queues.
N/A
N/A
https://vizzuality.atlassian.net/browse/MARXAN-204
---
> ADR: queues [MARXAN-204]

- api/CHANGELOG.md
- api/src/app.module.ts
- api/src/migrations/api/1615293097000-AddApiEventsTable.ts
- api/src/modules/api-events/api-event.api.entity.ts
- api/src/modules/api-events/api-event.topic+kind.api.entity.ts
- api/src/modules/api-events/api-events.controller.ts
- api/src/modules/api-events/api-events.module.ts
- api/src/modules/api-events/api-events.service.ts
- api/src/modules/api-events/dto/apiEvents.user.data.dto.ts
- api/src/modules/api-events/dto/create.api-event.dto.ts
- api/src/modules/api-events/dto/update.api-event.dto.ts
- api/src/modules/authentication/authentication.controller.ts
- api/src/modules/authentication/authentication.module.ts
- api/src/modules/authentication/authentication.service.ts
- api/src/modules/authentication/dto/user-account.validation.dto.ts
- api/src/modules/users/users.service.ts
- api/test/plan.s01e02.e2e-spec.ts
- api/test/projects.e2e-spec.ts
- api/test/users.e2e-spec.ts
See https://vizzuality.atlassian.net/browse/MARXAN-124
> event module [MARXAN-124]

- README.md
- api/CHANGELOG.md
- api/package.json
- api/src/app.module.ts
- api/src/filters/all-exceptions.exception.filter.ts
- api/src/modules/admin-areas/admin-areas.service.ts
- api/src/modules/organizations/organization.api.entity.ts
- api/src/modules/organizations/organizations.controller.ts
- api/src/modules/projects/project.api.entity.ts
- api/src/modules/projects/projects.controller.ts
- api/src/modules/protected-areas/dto/create.protected-area.dto.ts
- api/src/modules/protected-areas/dto/iucn-protected-area-category.dto.ts
- api/src/modules/protected-areas/dto/update.protected-area.dto.ts
- api/src/modules/protected-areas/protected-area.geo.entity.ts
- api/src/modules/protected-areas/protected-areas.controller.ts
- api/src/modules/protected-areas/protected-areas.module.ts
- api/src/modules/protected-areas/protected-areas.service.ts
- api/src/modules/scenarios/scenarios.controller.ts
- api/src/utils/app-base.service.ts
- api/test/e2e.config.ts
- api/test/projects.e2e-spec.ts
- api/test/protected-areas.e2e-spec.ts
- api/test/users.e2e-spec.ts
- api/yarn.lock
- docker-compose.yml
See https://vizzuality.atlassian.net/browse/MARXAN-210
There are three new tests in `test/protected-areas.e2e-spec.ts` that cover the functionality of this PR (all the other tests in that file are currently skipped, some of them are even just a stub, so the skipped ones can be ignored altogether).
> protected areas: list IUCN categories and list protected areas by parent admin area or geometry

- api/CHANGELOG.md
- api/package.json
- api/src/decorators/json-api-parameters.decorator.ts
- api/src/modules/admin-areas/admin-areas.controller.ts
- api/src/modules/admin-areas/admin-areas.service.ts
- api/src/modules/countries/countries.controller.ts
- api/src/modules/organizations/organizations.controller.ts
- api/src/modules/organizations/organizations.service.ts
- api/src/modules/projects/projects.controller.ts
- api/src/modules/projects/projects.service.ts
- api/src/modules/protected-areas/protected-areas.controller.ts
- api/src/modules/protected-areas/protected-areas.service.ts
- api/src/modules/scenarios/scenarios.controller.ts
- api/src/modules/scenarios/scenarios.service.ts
- api/src/utils/app-base.service.ts
- api/yarn.lock
See https://vizzuality.atlassian.net/browse/MARXAN-212 and https://vizzuality.atlassian.net/browse/MARXAN-213
> allow to specify includes in singular get endpoints; add base filters for scenarios, projects and organizations [MARXAN-212] [MARXAN-213]

- app/layout/projects/new/form/component.tsx
- app/layout/projects/show/scenarios/component.tsx
- app/layout/scenarios/sidebar/component.tsx
- app/layout/scenarios/sidebar/tabs/component.tsx
- app/layout/scenarios/sidebar/tabs/index.ts
- app/layout/scenarios/sidebar/wdpa/component.tsx
- app/store/index.ts
- app/store/slices/scenarios/edit.ts
- app/tailwind.config.js
This PR adds:
- Tabs
- Sidebar components reacting to tab changes
- Dynamic slice example
> Scenario tabs

- api/package.json
Add node version restriction to api package.json to match the corresponding dockerfile
> Add node version restriction to api package.json

- api/src/decorators/json-api-parameters.decorator.ts
Just a first step to `strict: true` and very first contribution.
No changes in swagger output (compared to [this version](https://marxan49.westeurope.cloudapp.azure.com/swagger/))
---
> chore(decorators): simplify composed decorators

- .github/workflows/api-e2e-tests.yml
See https://vizzuality.atlassian.net/browse/MARXAN-373
> set sensible (for now) timeout for API CI jobs

- api/src/utils/app-base.service.ts
See https://vizzuality.atlassian.net/browse/MARXAN-374
> fix missing meta prop for pagination

- app/components/search/component.tsx
- app/hooks/administrative-areas/index.ts
- app/hooks/countries/index.ts
- app/hooks/features/index.ts
- app/hooks/me/index.ts
- app/hooks/projects/index.ts
- app/hooks/scenarios/index.ts
- app/hooks/wdpa/index.ts
- app/layout/header/title/component.tsx
- app/layout/projects/new/form/component.tsx
- app/layout/scenarios/sidebar/features/add/list/component.tsx
- app/layout/scenarios/sidebar/features/intersect/component.tsx
- app/layout/scenarios/sidebar/features/intersect/list/component.tsx
- app/layout/scenarios/sidebar/name/component.tsx
- app/package.json
- app/pages/auth/sign-up.tsx
- app/services/administrative-areas/index.ts
- app/services/countries/index.ts
- app/services/projects/index.ts
- app/services/scenarios/index.ts
- app/services/users/index.ts
- app/services/wdpa/index.ts
- app/yarn.lock
This PR adds:
- `meta` inside service responses
- All features pagination
- Improve loaders inside infiniteQuery lists
> Meta inside service responses. Features pagination. Features loaders

- Makefile
- Makefile-ci
- api/src/migrations/api/1616155304000-AddCascadeToAllowDeletingProjectsWithScenarios.migration.ts
- api/src/migrations/api/1616764914000-UpdateScenarioTableForProtectedAreaSelection.ts
- api/src/migrations/api/1618241224000-AddDraftStatusToJobStatusEnum.ts
- api/src/migrations/api/1618248224000-AllowToLinkCustomGeoFeaturesToProjects.ts
- api/src/migrations/api/1619711501000-DropNotNullsOnTimeUserMetadataColumns.ts
- api/src/modules/proxy/proxy.controller.ts
- api/test/proxy.vector-tiles.e2e-spec.ts
- geoprocessing/src/migrations/geoprocessing/1616690947000-AddIdToCountriesView.ts
- geoprocessing/src/migrations/geoprocessing/1618853324000-ExtractDistictPropsFromFeatures.ts
- geoprocessing/src/migrations/geoprocessing/1619711501000-DropNotNullsOnTimeUserMetadataColumns.ts
See https://vizzuality.atlassian.net/browse/MARXAN-342
> make time/user metadata nullable

- api/src/app.module.ts
- api/src/modules/scenarios-features/scenario-features.service.ts
- api/src/modules/scenarios-planning-unit/entities/remote-connection-name.ts
- api/src/modules/scenarios-planning-unit/entities/scenarios-planning-unit.geo.entity.ts
- api/src/modules/scenarios-planning-unit/lock-status.enum.ts
- api/src/modules/scenarios-planning-unit/scenarios-planning-unit.module.ts
- api/src/modules/scenarios-planning-unit/scenarios-planning-unit.service.ts
- api/test/scenarios-pu-data/scenarios-pu-data-service.integration.e2e-spec.ts
- api/test/scenarios-pu-data/steps/given-scenario-pu-data-exists.ts
- api/test/scenarios-pu-data/steps/world.ts
integration-e2e was mostly added to verify mapping(transform)
---
> chore(api): scenarios-planning-units base service

- api/src/modules/proxy/proxy.controller.ts
- geoprocessing/src/modules/features/features.controller.ts
- geoprocessing/src/modules/protected-areas/protected-areas.controller.ts
Add protected areas and features endpoint in proxy.
---
> add features and protected areas to proxy

- .github/workflows/api-e2e-tests.yml
- Makefile
- api/entrypoint.sh
- api/package.json
- api/src/filters/all-exceptions.exception.filter.spec.ts
- api/src/filters/all-exceptions.exception.filter.ts
- docker-compose-test-unit.yml
See https://github.com/Vizzuality/marxan-cloud/pull/158
> enable unit tests in GH Actions CI

- api/src/modules/planning-units-protection-level/calculate-planning-units-protection-level.handler.ts
- api/src/modules/queue/queue.module.ts
- api/src/modules/queue/queue.service.ts
- api/src/modules/queue/queue.tokens.ts
- api/test/calculate-pu-protection-level/example.integration.e2e-spec.ts
- api/test/utils/api-application.ts
- api/test/utils/queues.ts
> chore(api): integration-or-e2e tests with queues

- api/src/app.module.ts
- api/src/modules/planning-units-protection-level/index.ts
- api/src/modules/scenarios/scenarios.module.ts
- api/src/modules/scenarios/scenarios.service.ts
- api/test/e2e.config.ts
- api/test/scenarios-pu-data/scenarios-pu-data-service.integration.e2e-spec.ts
- api/test/scenarios.e2e-spec.ts
Restored https://github.com/Vizzuality/marxan-cloud/pull/173
> feat(api): calculate planning units protection level - submit job to queue

- api/src/modules/analysis/analysis.module.ts
- api/src/modules/analysis/providers/planning-units/adapters/async-jobs-adapter.spec.ts
- api/src/modules/analysis/providers/planning-units/adapters/async-jobs-adapter.ts
- api/src/modules/analysis/queue-name.ts
- api/src/modules/scenarios-planning-unit/scenarios-planning-unit.service.ts
- api/src/modules/scenarios/scenarios.controller.ts
- api/src/modules/scenarios/scenarios.module.ts
- api/test/scenario-pu-change/assertions/expect-bad-request.ts
- api/test/scenario-pu-change/assertions/has-expected-job-details.ts
- api/test/scenario-pu-change/assertions/has-relevant-job-name.ts
- api/test/scenario-pu-change/scenario-put-change.e2e-spec.ts
- api/test/scenario-pu-change/steps/WhenChangingPlanningUnitInclusivity.ts
- api/test/scenario-pu-change/steps/world.ts
- api/test/steps/given-scenario-pu-data-exists.ts
Restored https://github.com/Vizzuality/marxan-cloud/pull/172
> feat(api): analysis: push job to bullmq queue

- geoprocessing/test/jest-e2e.json
- geoprocessing/test/planning-units-processor.e2e-spec.ts
- geoprocessing/test/setEnvironment.ts
> fix(geoprocessing): bring e2e test to valid state

- app/components/map/legend/component.stories.tsx
- app/components/map/legend/component.tsx
- app/components/map/legend/item/component.tsx
- app/components/map/legend/mock.tsx
- app/components/map/legend/types/basic/component.tsx
- app/components/map/legend/types/basic/index.ts
- app/components/map/legend/types/choropleth/component.tsx
- app/components/map/legend/types/choropleth/index.ts
- app/components/map/legend/types/gradient/component.tsx
- app/components/map/legend/types/gradient/index.ts
This PR adds:
- Legend types
- Choropleth
- Basic
- Gradient
- Max height
> Legend types and maxHeight

- api/src/modules/proxy/proxy.controller.ts
- api/src/modules/proxy/proxy.service.ts
- geoprocessing/src/api.config.ts
- geoprocessing/src/filters/all-exceptions.exception.filter.ts
- geoprocessing/src/modules/admin-areas/admin-areas.controller.ts
- geoprocessing/src/modules/admin-areas/admin-areas.service.ts
- geoprocessing/src/modules/features/features.controller.ts
- geoprocessing/src/modules/features/features.service.ts
- geoprocessing/src/modules/planning-units/planning-units.controller.ts
- geoprocessing/src/modules/planning-units/planning-units.geo.entity.ts
- geoprocessing/src/modules/planning-units/planning-units.module.ts
- geoprocessing/src/modules/planning-units/planning-units.service.ts
- geoprocessing/src/modules/protected-areas/protected-areas.controller.ts
- geoprocessing/src/modules/protected-areas/protected-areas.service.ts
- geoprocessing/src/modules/shapefiles/shapefiles.service.ts
- geoprocessing/test/index.html
Supercedes https://github.com/Vizzuality/marxan-cloud/pull/155
Rebased on latest `develop` after some history rewrite.
> add planning unit vector tile preview - rebased

- api/src/modules/api-events/api-event.api.entity.ts
- env.default
- geoprocessing/config/custom-environment-variables.json
- geoprocessing/config/default.json
- geoprocessing/package.json
- geoprocessing/src/app.module.ts
- geoprocessing/src/modules/api-events/api-events.module.ts
- geoprocessing/src/modules/api-events/api-events.service.ts
- geoprocessing/src/modules/api-events/events.enum.ts
- geoprocessing/test/api-events.service.integration.e2e-spec.ts
- geoprocessing/yarn.lock
> feat(geoprocessing): api-events wrapper

- api/entrypoint.sh
- geoprocessing/src/modules/planning-units/planning-units-processing.ts
- geoprocessing/src/modules/planning-units/planning-units.module.ts
- geoprocessing/src/modules/planning-units/planning-units.worker.ts
- geoprocessing/src/modules/worker/worker-announcer.ts
- geoprocessing/src/modules/worker/worker.module.ts
- geoprocessing/src/modules/worker/worker.service.ts
- geoprocessing/src/modules/worker/worker.tokens.ts
- geoprocessing/test/worker-module/bullmq-worker-code.ts
- geoprocessing/test/worker-module/worker-module-usage.e2e-spec.ts
> feat(geoprocessing): worker module with example

- api/src/migrations/api/1621341638168-CostSurfaceEvents.ts
- api/src/modules/api-events/api-event.api.entity.ts
- api/src/modules/api-events/api-events.service.ts
- api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.spec.ts
- api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.ts
- api/src/modules/scenarios/scenarios.module.ts
> feat(api): cost-surface: api-events impl

- api/package.json
- api/src/modules/scenarios/__mocks__/fake-cost-template.service.ts
- api/src/modules/scenarios/cost-surface-template.controller.integration.spec.ts
- api/src/modules/scenarios/cost-surface-template.controller.ts
- api/src/modules/scenarios/cost-template.service.ts
- api/src/modules/scenarios/scenario-cost-surface-template.service.ts
- api/yarn.lock
https://vizzuality.atlassian.net/browse/MARXAN-403
---
> feat(scenarios): add cost template controller

- README.md
- api/api.Dockerfile
- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- docker-compose-test-e2e.yml
- docker-compose-test-unit.yml
- docker-compose.yml
See https://vizzuality.atlassian.net/browse/MARXAN-440 (and https://vizzuality.atlassian.net/browse/MARXAN-439 for context)
> configure volume for sharing of uploaded files between api and geoprocessing service (development environments)

- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/projects/new/form/component.tsx
- app/pages/projects/new.tsx
> Project new: scroll

- api/apps/geoprocessing/src/modules/api-events/index.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-worker.ts
- api/apps/geoprocessing/src/modules/surface-cost/surface-cost.module.ts
> feat(geoprocessing): cost-surface: emit api-events on job result

- app/layout/header/component.tsx
- app/layout/header/my-projects/component.tsx
- app/layout/header/my-projects/index.ts
> Header: my projects link

- api/apps/api/src/modules/projects/project.api.entity.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/test/geo-features.e2e-spec.ts
- api/apps/api/test/project/project-get.e2e-spec.ts
- api/apps/api/test/project/projects-world.ts
> feat(api): projects: include most-specific admin area name/id

- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/test/project/project-get.e2e-spec.ts
> fix(api): projects: update snapshots after bbox inclusion in response

- api/apps/api/src/migrations/api/1623163237087-DropProjectExtentTrigger.ts
- api/apps/api/test/fixtures/test-data.sql
- api/apps/api/test/project/project-get.e2e-spec.ts
A minimal fix to have bbox working correctly.
---
> fix(api): drop extent trigger on bbox

- api/apps/api/src/modules/api-events/api-event.api.entity.ts
- api/apps/api/src/modules/api-events/api-event.topic+kind.api.entity.ts
- api/apps/api/src/modules/api-events/api-events.controller.ts
- api/apps/api/src/modules/api-events/dto/create.api-event.dto.ts
- api/apps/api/src/modules/authentication/authentication.service.ts
- api/apps/api/src/modules/projects/protected-areas/protected-areas.facade.ts
- api/apps/api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.spec.ts
- api/apps/api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.ts
- api/apps/api/test/jest-e2e.json
- api/apps/api/test/users.e2e-spec.ts
- api/apps/geoprocessing/src/modules/api-events/api-events-subscriber.spec.ts
- api/apps/geoprocessing/src/modules/api-events/api-events.service.ts
- api/apps/geoprocessing/src/modules/api-events/api.event.ts
- api/apps/geoprocessing/src/modules/api-events/index.ts
- api/apps/geoprocessing/src/modules/protected-areas/worker/protected-area-worker.service.ts
- api/apps/geoprocessing/src/modules/surface-cost/adapters/pu-cost-extractor.spec.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-processor.spec.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-worker.ts
- api/apps/geoprocessing/test/api-events.service.integration.e2e-spec.ts
- api/apps/geoprocessing/test/jest-e2e.json
- api/libs/api-events/src/api-event-kinds.enum.ts
- api/libs/api-events/src/index.ts
- api/libs/api-events/tsconfig.lib.json
- api/nest-cli.json
- api/package.json
- api/tsconfig.json
> refactor: move api-events to shared lib

- api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
- api/apps/api/src/modules/projects/job-status/job-status-target-events.ts
- api/apps/api/src/modules/projects/job-status/job-status.service.ts
- api/apps/api/src/modules/projects/job-status/jobs.enum.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.module.ts
> feat(api): scenario's job status - API

- api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
- api/apps/api/test/project-jobs-status/project-job-status.e2e-spec.ts
- api/apps/api/test/project-jobs-status/world.ts
- api/apps/api/test/steps/given-api-event.ts
- api/apps/api/test/steps/given-scenario-exists.ts
Failing test is fine - it should be "green" once valid implementation is in place.
> test(api): project-jobs-status

- api/apps/api/src/migrations/api/1623166932364-DropExtentInProject.ts
- api/apps/api/src/modules/projects/dto/create.project.dto.ts
- api/apps/api/src/modules/projects/project.api.entity.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
- api/apps/api/test/e2e.config.ts
- api/apps/api/test/fixtures/test-data.sql
- api/apps/geoprocessing/src/modules/planning-units/dto/create.regular.planning-units.dto.ts
- api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
- api/apps/geoprocessing/test/e2e.config.ts
> [MARXAN-451] remove extent from projects

- api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
> addressed issues with test error in api

- api/apps/api/src/migrations/api/1623311716713-AddJobStatusView.ts
- api/apps/api/src/modules/projects/dto/job-status.serializer.ts
- api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
- api/apps/api/src/modules/projects/job-status/job-status.service.ts
- api/apps/api/src/modules/projects/job-status/job-status.view.api.entity.ts
- api/apps/api/src/modules/projects/projects.module.ts
- api/apps/api/test/project-jobs-status/job-status.service.integration.e2e-spec.ts
- api/apps/api/test/project-jobs-status/project-job-status.e2e-spec.ts
- api/apps/api/test/project-jobs-status/world.ts
- api/libs/utils/src/assert-defined.ts
- api/libs/utils/src/index.ts
> feature(api): add service for jobs status

- app/hooks/organizations/index.ts
- app/hooks/organizations/types.ts
- app/layout/projects/new/form/component.tsx
- app/services/organizations/index.ts
This PR adds:
- Organization hook
- Organization service
- Project new: fetch organization id from API instead of hardcoding it
> Project: Organization fetched from API

- app/hooks/features/index.ts
- app/layout/scenarios/sidebar/features/add/component.tsx
- app/layout/scenarios/sidebar/features/add/filters/component.tsx
- app/layout/scenarios/sidebar/features/add/filters/index.ts
- app/layout/scenarios/sidebar/features/add/list/component.tsx
- app/layout/scenarios/sidebar/features/add/toolbar/component.tsx
- app/layout/scenarios/sidebar/features/component.tsx
- app/svgs/ui/filter.svg
This PR adds:
- filter modal
- filters applied to requests
> Features filters

- api/apps/api/src/modules/admin-areas/admin-areas.service.ts
- api/apps/api/test/countries.e2e-spec.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1623754019796-AddMinMaxAreaSizeToAdminRegions.ts
- api/libs/admin-regions/src/admin-areas.geo.entity.ts
> feat(geoprocessing): add min/max pu area size in admin regions

- api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/project-scenarios.e2e-spec.ts
> feat(api): add name/desc search for scenarios

- api/apps/api/test/scenario-cost-template/bull-mq-integration.e2e-spec.ts
> test(api): improve stability of queue tests

- api/apps/api/src/modules/countries/countries.service.ts
- api/apps/api/src/modules/countries/country.geo.entity.ts
- api/apps/api/test/countries.e2e-spec.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1623937649032-AddMinMaxAreaSizeToCountries.ts
> feat(geoprocessing): add min/max pu area size in countries

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/modules/queue/queue.module.ts
- api/apps/api/src/modules/scenarios/input-parameter-file.provider.spec.ts
- api/apps/api/src/modules/scenarios/input-parameter-file.provider.ts
- api/apps/api/src/modules/scenarios/scenario.api.entity.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
> feat(api): add io settings to input parameter file

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/modules/queue/queue.module.ts
- api/apps/api/src/modules/scenarios/dto/create.scenario.dto.ts
- api/apps/api/src/modules/scenarios/dto/scenario-metadata.dto.ts
- api/apps/api/src/modules/scenarios/input-parameter-file.provider.spec.ts
- api/apps/api/src/modules/scenarios/input-parameter-file.provider.ts
- api/apps/api/src/modules/scenarios/scenario.api.entity.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/jest-e2e.json
- api/apps/api/test/project-scenarios.e2e-spec.ts
- api/apps/geoprocessing/test/jest-e2e.json
- api/libs/marxan-input/src/__snapshots__/marxan-input.spec.ts.snap
- api/libs/marxan-input/src/index.ts
- api/libs/marxan-input/src/marxan-file-input.ts
- api/libs/marxan-input/src/marxan-input.spec.ts
- api/libs/marxan-input/src/marxan-input.ts
- api/libs/marxan-input/src/marxan-parameters.ts
- api/libs/marxan-input/tsconfig.lib.json
- api/nest-cli.json
- api/package.json
- api/tsconfig.json
> feat(marxan-input): add marxan input definitions

- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
- app/layout/scenarios/sidebar/analysis/cost-surface/component.tsx
- app/services/downloads/index.ts
This PR adds:
- download cost surface
- upload new cost surface
> Cost surface

- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/scenario-data/asset-fetcher.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/scenario-data/derive-scenario-data.module.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/scenario-data/derive-scenario.facade.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/scenario-data/fetch.config.ts
- api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
> feat(marxan-runner): use x-api-key when downloading assets

- api/apps/api/src/modules/scenarios/marxan-run/marxan-run.controller.ts
- api/apps/api/src/modules/scenarios/marxan-run/marxan-run.service.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
> feat(scenarios): allow to get input files via x-api-key

- api/apps/api/src/modules/geo-features/geo-feature.api.entity.ts
- api/apps/api/src/modules/geo-features/geo-feature.geo.entity.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/test/e2e.config.ts
- api/apps/api/test/fixtures/test-data.sql
- api/apps/api/test/geo-features.e2e-spec.ts
- api/apps/api/test/json-api.e2e-spec.ts
- api/apps/api/test/proxy.vector-tiles.e2e-spec.ts
- api/apps/api/test/utils/features.test.utils.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1624025983610-M2ToKm2PUAreaSize.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1624281665759-Ratio64PUAreaSize.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1625042393000-RefactorExtractDistinctPropsFromFeatures.ts
- api/apps/geoprocessing/src/modules/planning-units/planning-units.module.ts
- api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
see https://vizzuality.atlassian.net/browse/MARXAN-490
> refactor geofeatures properties query

- api/apps/geoprocessing/src/modules/scenarios/cost-template/cost-template-dumper.ts
- api/apps/geoprocessing/test/integration/planning-areas/custom-planning-area.repository.e2e-spec.ts
- api/libs/planning-area-repository/src/custom-planning-area.repository.ts
- api/libs/planning-area-repository/src/planning-area-repository.module.ts
> feat(geoprocessing): remove old planning area when project reassigned

- api/apps/api/src/modules/scenarios/input-parameter-file.provider.spec.ts
- api/apps/api/src/modules/scenarios/input-parameter-file.provider.ts
- api/apps/api/test/e2e.config.ts
- api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
- api/apps/api/test/scenario-input-files/world.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
- api/apps/api/test/steps/given-project.ts
> feat(scenario): input.dat cloud information

- api/apps/api/src/modules/scenarios/input-files/puvspr.dat.module.ts
- api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
- api/apps/api/src/modules/scenarios/input-files/puvspr.data.service.spec.ts
- api/apps/api/src/modules/scenarios/marxan-run/marxan-run.controller.ts
- api/apps/api/src/modules/scenarios/marxan-run/marxan-run.service.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/jest-e2e.json
- api/apps/geoprocessing/src/migrations/geoprocessing/1626083377982-ScenarioPuvsprView.ts
- api/libs/scenario-puvspr/src/index.ts
- api/libs/scenario-puvspr/src/scenario-puvspr.geo.entity.ts
- api/libs/scenario-puvspr/tsconfig.lib.json
- api/nest-cli.json
- api/package.json
- api/tsconfig.json
> feat(scenarios): allow to get puvspr.dat file

- api/apps/api/src/modules/queue/index.ts
- api/apps/api/src/modules/queue/queue-events.builder.ts
- api/apps/api/src/modules/queue/queue-options.provider.ts
- api/apps/api/src/modules/queue/queue.builder.ts
- api/apps/api/src/modules/queue/queue.module.ts
- api/apps/api/src/modules/queue/queue.service.ts
- api/apps/api/src/modules/queue/queue.tokens.ts
- api/apps/api/test/calculate-pu-protection-level/example.integration.e2e-spec.ts
- api/apps/api/test/project-planning-units/planning-units.e2e-spec.ts
- api/apps/api/test/project-protected-areas/steps/world.ts
- api/apps/api/test/project-scenarios.e2e-spec.ts
- api/apps/api/test/scenario-pu-change/scenario-put-change.e2e-spec.ts
- api/apps/api/test/utils/api-application.ts
- api/apps/api/test/utils/queues.ts
> refactor(api): rewrite queue module

- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/scenarios/map/component.tsx
> PU grid layer

- api/apps/api/src/modules/projects/planning-areas/__mocks__/all-planning-areas.service.fixtures.ts
- api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
- api/apps/api/src/modules/scenarios/marxan-run/run.service.ts
- api/apps/api/test/utils/queues.ts
- api/apps/geoprocessing/src/modules/scenarios/run.worker.ts
- api/apps/geoprocessing/src/modules/scenarios/scenarios.module.ts
- api/apps/geoprocessing/src/modules/worker/index.ts
- api/apps/geoprocessing/src/modules/worker/queue-events.builder.ts
- api/apps/geoprocessing/src/modules/worker/worker.module.ts
- api/apps/geoprocessing/test/integration/marxan-run/run-worker.e2e-spec.ts
- api/libs/scenario-run-queue/src/index.ts
- api/libs/utils/src/fields-of.type.ts
- api/libs/utils/src/index.ts
> feat(geoprocessing): add worker to run and cancel marxan

- app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
- app/layout/projects/new/form/planning-area-selector/planning-unit-grid/component.tsx
Very simple PR. i just added text to the Info buttons of the planning grid and planning area size
> text to info buttons

- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/most-different.service.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/most-different.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/solutions-output.module.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
> MARXAN-521 MARXAN-525 -> most diff solutions

- api/apps/api/src/modules/scenarios/dto/update-scenario-planning-unit-lock-status.dto.ts
- api/apps/api/src/modules/scenarios/solutions-result/solution-result-crud.service.ts
- api/apps/api/test/scenario-solutions/world.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1624890503611-marxanOutputEntities.ts
- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/__mocks__/include-sample.ts
- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts
See: https://vizzuality.atlassian.net/browse/MARXAN-572
> selection of pu lock status should work with single features

- api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.dto.ts
- api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.serializer.ts
- api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.e2e-spec.ts
- api/apps/api/test/scenario-input-files/scenario-cost-surface/world.ts
https://vizzuality.atlassian.net/browse/MARXAN-577
> feat(scenarios): allow to get all planning-units with their lock-status

- api/apps/api/src/modules/scenarios/marxan-run/assets.service.spec.ts
- api/apps/api/src/modules/scenarios/marxan-run/assets.service.ts
- api/apps/api/src/modules/scenarios/marxan-run/cancel.handler.ts
- api/apps/api/src/modules/scenarios/marxan-run/events.handler.ts
- api/apps/api/src/modules/scenarios/marxan-run/index.ts
- api/apps/api/src/modules/scenarios/marxan-run/marxan-run.module.ts
- api/apps/api/src/modules/scenarios/marxan-run/run-service.providers.ts
- api/apps/api/src/modules/scenarios/marxan-run/run.handler.ts
- api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
- api/apps/api/src/modules/scenarios/marxan-run/run.service.ts
- api/apps/api/src/modules/scenarios/marxan-run/tokens.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/libs/marxan-input/src/index.ts
- api/libs/marxan-input/src/marxan-parameters.ts
> feat(api): skip bound.dat file if no blm given or zero blm

- api/apps/geoprocessing/src/modules/planning-area/marxan-geo-json.ts
- api/apps/geoprocessing/src/modules/planning-area/planning-area.controller.ts
- api/apps/geoprocessing/src/modules/planning-area/planning-area.module.ts
- api/apps/geoprocessing/src/modules/planning-area/planning-area.serializer.spec.ts
- api/apps/geoprocessing/src/modules/planning-area/planning-area.serializer.ts
- api/apps/geoprocessing/src/modules/planning-area/planning-area.service.ts
- api/apps/geoprocessing/src/modules/planning-area/pu-sizes.ts
- api/apps/geoprocessing/test/integration/planning-areas/custom-planning-area.repository.e2e-spec.ts
- api/libs/planning-area-repository/src/custom-planning-area.repository.ts
- api/libs/planning-area-repository/src/index.ts
> feat(geoprocessing): return bbox and pu sizes during shapefile creation

- api/apps/api/src/modules/scenarios/scenarios.service.ts
see https://vizzuality.slack.com/archives/C01G7PRQB96/p1627470660086900
> temporarily limit response to 5 elements to mimic eventual behaviour

- app/components/projects/published-item/component.tsx
- app/hooks/projects/index.ts
- app/layout/community/published-projects/component.tsx
[Figma](https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=5460%3A7833)
[MARXAN-604](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-604&assignee=60d985f51613d50069adeabc)
> front(fix): published projects planning area + contributors [MARXAN-604]

- api/apps/api/src/modules/scenarios/dto/zip-files.serializer.ts
- api/apps/api/src/modules/scenarios/output-files/output-files.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/geo-output.repository.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/solutions-output.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-run.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1627643811485-AddFailedColumnToMarxanExecutionMetadata.ts
- api/libs/marxan-output/src/marxan-execution-metadata.geo.entity.ts
> feat(geoprocessing): store output of failed marxan runs

- api/apps/api/src/modules/scenarios/dto/scenario-metadata.dto.ts
- api/apps/api/src/modules/scenarios/scenario.api.entity.ts
https://vizzuality.atlassian.net/browse/MARXAN-628
> add support for saving scenario UI editing progress

- api/apps/api/src/modules/scenarios/input-files/input-files.module.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.ts
- api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
- api/libs/marxan-input/src/marxan-parameters.ts
> feat(api): allow to overwrite input param through scenario

- app/layout/projects/show/scenarios/settings/component.tsx
[MARXAN-600](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-600&quickFilter=71)
> front: add number of features to scenario settings [MARXAN-600]

- app/components/button/component.tsx
- app/layout/header/component.tsx
- app/layout/home/hero/component.tsx
> Improve Buttons design

- api/apps/api/src/modules/analysis/providers/shared/__mocks__/scenario-planning-unit-geo.data.ts
- api/apps/api/src/modules/analysis/providers/shared/adapters/are-puids-allowed-adapter.ts
- api/apps/api/test/scenario-pu-change/steps/world.ts
- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts
See https://vizzuality.atlassian.net/browse/MARXAN-537
> fix setting lock status of scenario pus via ids

- api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units-linker-service.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/e2e.config.ts
- api/apps/api/test/project-jobs-status/world.ts
- api/apps/api/test/project-protected-areas/steps/world.ts
- api/apps/api/test/project/project-get.e2e-spec.ts
- api/apps/api/test/scenario-input-files/scenario-cost-surface/world.ts
- api/apps/api/test/scenario-pu-change/steps/world.ts
- api/apps/api/test/scenario-run-results/world.ts
- api/apps/api/test/scenario-solutions/world.ts
see https://vizzuality.atlassian.net/browse/MARXAN-603 / https://vizzuality.atlassian.net/browse/MARXAN-623
needs tests
> attach planning units to scenario

- api/apps/api/src/modules/geo-features/geo-feature-set.service.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.ts
- api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
https://vizzuality.atlassian.net/browse/MARXAN-547
only to unblock testing of the platform for demo scenarios - lacks tests and stuff
> MVP linking of plain features to scenario

- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
see https://vizzuality.atlassian.net/browse/MARXAN-537?focusedCommentId=11997
> process inclusion/exclusion byId and byGeoJson as union

- app/components/scenarios/item/component.tsx
- app/hooks/map/index.ts
- app/hooks/scenarios/index.ts
- app/layout/scenarios/map/component.tsx
- app/layout/scenarios/map/drawing-manager/component.tsx
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/clicking/component.tsx
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/component.tsx
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/drawing/component.tsx
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/buttons/uploading/component.tsx
- app/layout/scenarios/sidebar/analysis/adjust-planning-units/component.tsx
- app/store/slices/scenarios/edit.ts
This PR adds:
- new layers (solution and frequency)
- lock status bulletproof
> More layers and lock status improvements

- api/apps/api/src/modules/specification/application/__tests__/fixtures.ts
- api/apps/api/src/modules/specification/application/__tests__/submit-specification.handler.spec.ts
- api/apps/api/src/modules/specification/application/specification.repository.ts
- api/apps/api/src/modules/specification/application/submit-specification.handler.ts
- api/apps/api/src/modules/specification/commands/specification-input.spec.ts
- api/apps/api/src/modules/specification/commands/specification-input.ts
- api/apps/api/src/modules/specification/commands/submit-specification.command.ts
- api/apps/api/src/modules/specification/feature-config.ts
- api/package.json
- api/yarn.lock
> feat(specification): submit specification - application layer

- api/apps/api/src/modules/scenario-specification/application/__tests__/assign-candidate-specification.handler.spec.ts
- api/apps/api/src/modules/scenario-specification/application/__tests__/fixtures.ts
- api/apps/api/src/modules/scenario-specification/application/assign-candidate-specification.handler.ts
- api/apps/api/src/modules/scenario-specification/application/scenario-specification.repo.ts
- api/apps/api/src/modules/scenario-specification/command/assign-candidate-specification.command.ts
- api/apps/api/src/modules/scenario-specification/sagas/specification-candidate-created.saga.ts
> feat(scenario-specification): assign specification candidate

- api/apps/api/src/modules/specification/commands/determine-features-for-scenario-specification.command.ts
- api/apps/api/src/modules/specification/determine-features/application/__tests__/determine-features.handler.spec.ts
- api/apps/api/src/modules/specification/determine-features/application/__tests__/fixtures.ts
- api/apps/api/src/modules/specification/determine-features/application/determine-features-for-scenario.handler.ts
- api/apps/api/src/modules/specification/determine-features/application/specification.repository.ts
- api/apps/api/src/utils/__mocks__/fake-logger.ts
- api/package.json
- api/yarn.lock
> feat(specification): determine features application logic

- api/apps/api/src/modules/specification/calculate-features/application/__tests__/calculate-features-for-specification.handler.spec.ts
- api/apps/api/src/modules/specification/calculate-features/application/__tests__/fixtures.ts
- api/apps/api/src/modules/specification/calculate-features/application/calculate-features-for-specification.handler.ts
- api/apps/api/src/modules/specification/calculate-features/application/specification.repository.ts
- api/apps/api/src/modules/specification/commands/calculate-features-for-specification.command.ts
- api/apps/api/src/modules/specification/commands/calculate-features.command.ts
> feat(specification): calculate features application logic

- api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units-protection-status-calculator-service.ts
https://vizzuality.atlassian.net/browse/MARXAN-660
> avoid possible division by zero

- api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units-linker-service.ts
https://vizzuality.atlassian.net/browse/MARXAN-662
> planning units are not linked to scenario for l1 and l2 admin areas

- api/apps/api/src/modules/scenarios/solutions-result/solution-result-crud.service.ts
- api/apps/api/test/scenario-solutions/get-all-solutions.e2e-spec.ts
> feat(scenario): remove hardcoded values from scenario solutions

- app/hooks/features/index.ts
> front(fix): enable get features

- api/apps/api/src/modules/geo-features/dto/geo-feature-set-specification.dto.ts
- api/apps/api/src/modules/geo-features/geo-feature-set.service.ts
- api/apps/api/src/modules/scenarios/geo-features/geo-feature-dto.mapper.spec.ts
- api/apps/api/src/modules/scenarios/geo-features/geo-feature-dto.mapper.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/src/modules/specification/application/__tests__/calculate-features.handler.fixtures.ts
- api/apps/api/src/modules/specification/application/__tests__/determine-features.handler.fixtures.ts
- api/apps/api/src/modules/specification/application/specification-input.spec.ts
- api/apps/api/src/modules/specification/application/specification-input.ts
- api/apps/api/src/modules/specification/domain/__tests__/create-candidate/fixtures.ts
- api/apps/api/src/modules/specification/domain/__tests__/determine-features/fixtures.ts
- api/apps/api/src/modules/specification/domain/__tests__/mark-as-calculated/fixtures.ts
- api/apps/api/src/modules/specification/domain/feature-config.ts
- api/apps/api/test/integration/fixtures.ts
> feat(specification): add missing parameters to specification feature config

- api/apps/api/src/modules/geo-features/geo-feature-property-sets.service.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-648
https://vizzuality.atlassian.net/browse/MARXAN-671
> fix bugs when handling empty feature specs and when no features intersect the planning area

- api/apps/api/src/modules/api-events/dto/scenario-geofeature-data-v1-alpha.ts
- api/apps/api/src/modules/api-events/events-data/scenario-geofeature-data-v1-alpha.ts
- api/apps/api/src/modules/geo-features/processing/run.service.ts
- api/apps/geoprocessing/src/modules/features/features.module.ts
- api/apps/geoprocessing/src/modules/features/processing/processing.worker.ts
- api/apps/geoprocessing/src/modules/features/processing/worker-builder.providers.ts
- api/libs/api-events/src/api-event-kinds.enum.ts
- api/libs/api-events/src/index.ts
- api/libs/geofeature-calculations/src/index.ts
> feat(api): add canceling to processing jobs

- app/components/scenarios/item/component.tsx
- app/hooks/scenarios/index.ts
- app/layout/projects/show/map/component.tsx
- app/layout/projects/show/scenarios/component.tsx
This PR adds:
- Project legend (only if scenario already run)
- Project layers (only if scenario already run)
> Project map

- app/components/scenarios/item/component.tsx
- app/layout/projects/show/scenarios/component.tsx
- app/layout/scenarios/edit/run/component.tsx
When a scenario is running now you have the possibility of canceling it. It seems that the async job takes too much to realize that you cancel it, but this is something we need to ask the API team
> Run: cancel

- app/hooks/gap-analysis/index.ts
- app/hooks/solutions/index.ts
- app/layout/scenarios/edit/analysis/gap-analysis/list/component.tsx
- app/layout/scenarios/edit/features/component.tsx
- app/layout/scenarios/edit/run/component.tsx
- app/layout/scenarios/edit/tabs/constants.ts
- app/layout/scenarios/show/analysis/adjust-planning-units/component.tsx
- app/layout/scenarios/show/analysis/cost-surface/component.tsx
- app/layout/scenarios/show/analysis/gap-analysis/list/component.tsx
- app/layout/scenarios/show/solutions/details/component.tsx
- app/layout/scenarios/show/solutions/table-form/component.tsx
- app/layout/scenarios/show/solutions/table-form/types.ts
- app/public/styles/tailwind.storybook.css
- app/utils/utils-scenarios.js
[MARXAN-666](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-666&quickFilter=71)
[MARXAN-650](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-650&quickFilter=71)
> Front(fix): best-solution [MARXAN-666][MARXAN-650]

- api/apps/api/src/modules/admin-areas/admin-areas.service.ts
- api/apps/api/src/modules/geo-features/geo-feature-property-sets.service.ts
- api/apps/api/src/modules/geo-features/geo-features.module.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/geo-features/index.ts
- api/apps/api/src/modules/geo-features/processing/copy-events.handler.ts
- api/apps/api/src/modules/geo-features/processing/features-calculated.event.ts
- api/apps/api/src/modules/geo-features/processing/index.ts
- api/apps/api/src/modules/geo-features/processing/processing.module.ts
- api/apps/api/src/modules/geo-features/processing/specification-published.handler.ts
- api/apps/api/src/modules/scenario-specification/application/__tests__/last-updated-specification.fixtures.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-data-provider.service.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-operation.service.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-query.service.ts
- api/apps/api/src/modules/scenarios-features/copy/index.ts
- api/apps/api/src/modules/scenarios-features/create-features.command.ts
- api/apps/api/src/modules/scenarios-features/create-features.handler.ts
- api/apps/api/src/modules/scenarios-features/create-features.saga.ts
- api/apps/api/src/modules/scenarios-features/features-created.event.ts
- api/apps/api/src/modules/scenarios-features/index.ts
- api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
- api/apps/api/src/modules/specification/application/__tests__/submit-specification.handler.fixtures.ts
- api/apps/api/src/modules/specification/application/calculate-features.saga.ts
- api/apps/api/src/modules/specification/application/determine-features.saga.ts
- api/apps/api/src/modules/specification/application/specification-application.module.ts
- api/apps/api/src/modules/specification/domain/__tests__/create-candidate/fixtures.ts
- api/apps/api/src/modules/specification/domain/events/specification-candidate-created.event.ts
- api/apps/api/src/modules/specification/domain/feature-config.ts
- api/apps/api/src/modules/specification/domain/specification.ts
- api/apps/api/src/modules/specification/index.ts
> feat(api): add copy operation

- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/src/modules/scenarios/specification/specification.service.ts
> feat(scenario-specification): allow to get last updated specification

- app/components/scenarios/item/component.tsx
- app/layout/projects/new/form/component.tsx
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/show/tabs/component.tsx
- app/layout/sign-in/component.tsx
- app/pages/auth/sign-in.tsx
changed the few texts they have in the shared doc so far
> first round of text changes

- api/apps/api/src/modules/geo-features/geo-feature-set.serializer.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
> fix(api): return empty specification when not found

- api/apps/api/src/migrations/api/1629195451410-AddLastModifiedAtToSpecification.ts
- api/apps/api/src/modules/scenario-specification/application/__tests__/last-updated-specification.fixtures.ts
- api/apps/api/src/modules/scenario-specification/application/last-updated-specification.handler.ts
- api/apps/api/src/modules/specification/adapters/specification.api.entity.ts
- api/apps/api/src/modules/specification/adapters/specification.repository.ts
- api/apps/api/src/modules/specification/application/__tests__/get-specification.handler.fixtures.ts
- api/apps/api/src/modules/specification/application/__tests__/get-specification.handler.spec.ts
- api/apps/api/src/modules/specification/application/__tests__/in-memory-specification.repo.ts
- api/apps/api/src/modules/specification/application/get-specification.handler.ts
- api/apps/api/src/modules/specification/application/get-specification.query.ts
- api/apps/api/src/modules/specification/application/specification.repository.ts
- api/apps/api/src/modules/specification/index.ts
> fix(api): return last updated specification instead of active one

- api/apps/api/src/modules/geo-features/dto/geo-feature-set-specification.dto.ts
- api/apps/api/src/modules/projects/job-status/jobs.enum.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-query.service.ts
- api/apps/api/src/modules/scenarios-features/create-features.handler.ts
- api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
- api/apps/api/src/modules/scenarios-features/split/index.ts
- api/apps/api/src/modules/scenarios-features/split/split-data.provider.ts
- api/apps/api/src/modules/scenarios-features/split/split-operation.service.ts
- api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
- api/apps/api/src/modules/scenarios/specification/geo-feature-dto.mapper.spec.ts
- api/apps/api/src/modules/specification/domain/__tests__/determine-features/fixtures.ts
- api/apps/api/src/modules/specification/domain/feature-config.ts
- api/apps/api/src/modules/specification/index.ts
> [MARXAN-548] split operation

- app/hooks/features/index.ts
- app/hooks/map/index.ts
- app/hooks/scenarios/index.ts
- app/layout/scenarios/edit/features/add/component.tsx
- app/layout/scenarios/edit/features/component.tsx
- app/layout/scenarios/edit/features/list/component.tsx
- app/layout/scenarios/edit/features/targets/component.tsx
- app/layout/scenarios/edit/status/component.tsx
- app/layout/scenarios/edit/status/index.ts
- app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
This PR adds:
- async jobs
- new feature spec
> Features and async jobs

- data/bots/demo-australia/bot.ts
- data/bots/demo-brazil/bot.ts
- data/bots/demo-okavango/bot.ts
This PR:
- removes long names from projects, scenarios and organizations
- add initial scenarioEditingMetadata
> Bots: improvements

- app/hooks/map/constants.tsx
- app/layout/projects/show/header/toolbar/component.tsx
- app/layout/scenarios/show/analysis/sections/component.tsx
Some more small changes to text.
I have noticed all the Help beacons are gone from the Scenarios
> second round of text changes

- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/edit/status/component.tsx
- app/layout/scenarios/show/map/component.tsx
Reverts Vizzuality/marxan-cloud#463
> Revert "Refactor PU grid layer"

- app/layout/projects/show/map/component.tsx
- app/store/slices/projects/[id].ts
Replicate the same behavior as the "scenario's map" in the "project show map".
> Project show: layer settings

- api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
> feat(api): make flag ranAtLeasOnce visible

- app/components/map/legend/item/component.tsx
- app/components/projects/published-item/component.tsx
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/community/published-projects/detail/component.tsx
- app/layout/community/published-projects/detail/map/component.tsx
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/show/map/component.tsx
- app/layout/scenarios/show/solutions/details/component.tsx
- app/pages/community/projects/[pid]/index.tsx
This PR adds map of the first scenario runned - in case it exists - to the published project detail page.
[Figma Designs](https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=4671%3A7069)
[MARXAN-683](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-683&quickFilter=71&assignee=60d985f51613d50069adeabc&assignee=UNASSIGNED_USER_ID)
> Feat/published project map [MARXAN-683]

- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/scenario-data/asset-fetcher.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
- api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
> fix(marxan-run): kill downloading assets when run is cancelled

- api/apps/api/src/modules/scenarios-features/copy/copy-data-provider.service.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-operation.service.ts
- api/apps/api/src/modules/scenarios-features/copy/copy-query.service.ts
- api/apps/api/src/modules/scenarios-features/create-features.command.ts
- api/apps/api/src/modules/scenarios-features/create-features.handler.ts
- api/apps/api/src/modules/scenarios-features/create-features.saga.ts
- api/apps/api/src/modules/scenarios-features/split/split-data.provider.ts
- api/apps/api/src/modules/scenarios-features/split/split-operation.service.ts
- api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
- api/apps/api/src/modules/specification/adapters/specification-candidate-created.handler.ts
- api/apps/api/src/modules/specification/adapters/specification.repository.ts
- api/apps/api/src/modules/specification/application/__tests__/in-memory-specification.repo.ts
- api/apps/api/src/modules/specification/application/__tests__/submit-specification.handler.fixtures.ts
- api/apps/api/src/modules/specification/application/specification.repository.ts
- api/apps/api/src/modules/specification/domain/__tests__/create-candidate/fixtures.ts
- api/apps/api/src/modules/specification/domain/__tests__/determine-features/fixtures.ts
- api/apps/api/src/modules/specification/domain/__tests__/determine-features/scenario-specification-determine-features.spec.ts
- api/apps/api/src/modules/specification/domain/events/specification-candidate-created.event.ts
- api/apps/api/src/modules/specification/domain/specification.ts
> [MARXAN-701] do not process draft specs

- api/apps/api/src/migrations/api/1629874400088-roles.ts
- api/apps/api/test/fixtures/test-init-apidb.sql
> feat(roles): migrate available roles into db

- app/components/gap-analysis/item/component.stories.tsx
- app/components/gap-analysis/item/component.tsx
- app/hooks/gap-analysis/index.ts
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/show/analysis/gap-analysis/list/component.tsx
- app/layout/scenarios/show/map/component.tsx
- app/layout/scenarios/show/solutions/gap-analysis/component.tsx
- app/layout/scenarios/show/solutions/gap-analysis/list/component.tsx
- app/layout/scenarios/show/solutions/gap-analysis/list/index.ts
- app/layout/scenarios/show/solutions/gap-analysis/toolbar/component.tsx
- app/layout/scenarios/show/solutions/gap-analysis/toolbar/index.ts
- usePreGapAnalysis
- usePostGapAnalysis
- send featureIds to map
> Gap analysis

- api/apps/api/src/modules/scenarios/cost-range-service.ts
- api/apps/api/src/modules/scenarios/dto/cost-range.dto.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.module.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/test/scenarios/cost-range.service.e2e-spec.ts
- api/apps/api/test/utils/api-application.ts
> feat(api): add cost range endpoint

- api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.serializer.ts
- api/apps/api/src/modules/scenarios/input-files/cost-surface-view.service.ts
- api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.e2e-spec.ts
- api/apps/api/test/scenario-input-files/scenario-cost-surface/world.ts
- api/libs/scenarios-planning-unit/src/scenarios-planning-unit.geo.entity.ts
> fix(scenario): pu.dat should apply default values

- api/apps/api/src/modules/geo-features/geo-features.controller.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
> fix(geo-features): move stored project to params

- api/apps/geoprocessing/src/modules/shapefiles/shapefiles.service.ts
> fix(geoprocessing): use mapshaper in a separate process

- app/components/gap-analysis/item/component.stories.tsx
- app/components/gap-analysis/item/component.tsx
- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/analysis/gap-analysis/list/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/show/analysis/gap-analysis/list/component.tsx
- app/layout/scenarios/show/map/component.tsx
- app/store/slices/scenarios/detail.ts
- app/store/slices/scenarios/edit.ts
> Front(feat) pre gap-analysis highlight layer

- app/layout/projects/all/toolbar/component.tsx
- app/layout/projects/new/form/planning-area-selector/component.tsx
- app/layout/scenarios/edit/analysis/component.tsx
- app/layout/scenarios/edit/wdpa/categories/component.tsx
- app/layout/scenarios/edit/wdpa/threshold/component.tsx
- app/layout/scenarios/show/analysis/component.tsx
- app/layout/scenarios/show/solutions/component.tsx
- app/layout/scenarios/show/solutions/details/component.tsx
latest text changes, so far up to date with their revisions
> 'latest text changes from file'

- api/apps/geoprocessing/src/migrations/geoprocessing/1630996003066-FeaturesSearchKvProps.ts
See notes https://vizzuality.atlassian.net/browse/MARXAN-717
> perf(features): reduce features results extending time during search

- api/apps/api/src/migrations/api/1631254563649-ProjectJobsStatus.ts
- api/apps/api/src/modules/projects/dto/job-status.serializer.ts
- api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
- api/apps/api/src/modules/projects/job-status/index.ts
- api/apps/api/src/modules/projects/job-status/job-status.service.ts
- api/apps/api/src/modules/projects/job-status/project-status.view.api.entity.ts
- api/apps/api/src/modules/projects/planning-unit-grid/planning-unit-grid-set.saga.ts
- api/apps/api/src/modules/projects/planning-unit-grid/planning-unit-grid.module.ts
- api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.command.ts
- api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.handler.ts
- api/apps/api/src/modules/projects/project.api.entity.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.module.ts
- api/apps/api/test/project-jobs-status/job-status.service.integration.e2e-spec.ts
- api/apps/api/test/project-jobs-status/project-job-status.e2e-spec.ts
- api/apps/api/test/project-jobs-status/world.ts
- api/libs/api-events/src/api-event-kinds.enum.ts
- unpacking shapefile and adding geometries - https://github.com/Vizzuality/marxan-cloud/pull/525
- exposing endpoint to submit & api events - https://github.com/Vizzuality/marxan-cloud/pull/527
- updating project `planning_unit_grid_shape` - https://github.com/Vizzuality/marxan-cloud/pull/529
- exposing endpoint to get the request status - https://github.com/Vizzuality/marxan-cloud/pull/528 (this)
> feat(project): include project-related jobs in status

- api/apps/api/test/fixtures/test-geodata.sql
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/feature-id-to-scenario-feature-data.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/__snapshots__/output-line-to-data.transformer.spec.ts.snap
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/output-line-to-data.transformer.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/output-line-to-data.transformer.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/id-mapper/scenario-feature-id.mapper.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/scenario-feature-run-data.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1632468999736-TotalAreaInScenarioOutputs.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1632468999737-TotalAreaInGapAnalysis.ts
- api/libs/features/src/scenario-features-output-gap-data.geo.entity.ts
- api/libs/marxan-output/src/output-scenarios-features-data.geo.entity.ts
> fix(marxan-run): calculate total-area

- api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
- api/apps/api/src/modules/scenarios/input-files/spec-dat-tsv-file.ts
- api/apps/api/src/modules/scenarios/input-files/spec.dat.service.ts
- api/apps/api/src/modules/scenarios/input-files/spec.data.service.spec.ts
- api/apps/api/test/fixtures/test-geodata.sql
- api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/feature-id-to-scenario-feature-data.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/__snapshots__/output-line-to-data.transformer.spec.ts.snap
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/output-line-to-data.transformer.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/file-reader/output-line-to-data.transformer.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/id-mapper/scenario-feature-id.mapper.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/scenario-features/scenario-feature-run-data.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1632468999736-TotalAreaInScenarioOutputs.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1632468999737-TotalAreaInGapAnalysis.ts
- api/libs/features/src/scenario-features-output-gap-data.geo.entity.ts
- api/libs/marxan-output/src/output-scenarios-features-data.geo.entity.ts
> feat(api): aggregate features in spec.dat and puvspr.dat

- app/hooks/features/index.ts
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/scenarios/edit/features/list/component.tsx
- app/layout/scenarios/edit/features/targets/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/store/slices/scenarios/edit.ts
Using split properties will filter the map features
> feat(features): split affects map

- api/apps/api/src/modules/projects/dto/project.serializer.ts
- api/apps/api/src/modules/scenarios/dto/scenario.serializer.ts
- api/apps/api/test/project-scenarios.e2e-spec.ts
- api/apps/api/test/scenarios/input-file.e2e-spec.ts
> fix(scenarios): include pagination meta back

- .github/workflows/api-e2e-tests.yml
15 minutes was starting to be tight...
> bump up e2e CI job timeout to 30m

- api/apps/api/src/migrations/api/1632999358910-AddTimestampToJobStatusView.ts
- api/apps/api/src/migrations/api/1632999473857-AddTimestampToProjectJobsStatus.ts
- api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
- api/apps/api/src/modules/projects/job-status/job-status.service.ts
- api/apps/api/src/modules/projects/job-status/job-status.view.api.entity.ts
- api/apps/api/src/modules/projects/job-status/project-status.view.api.entity.ts
- api/apps/api/test/project-jobs-status/job-status.service.integration.e2e-spec.ts
- api/apps/api/test/project-jobs-status/project-job-status.e2e-spec.ts
> feat(async-jobs): add event date

- api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
> fix(features): fix intersection and selection for splitting species

- api/apps/api/src/modules/scenarios-features/data-moved-form-preparation.event.ts
- api/apps/api/src/modules/scenarios-features/index.ts
- api/apps/api/src/modules/scenarios-features/intersect-with-pu/data-moved-form-preparation-saga.service.ts
- api/apps/api/src/modules/scenarios-features/intersect-with-pu/intersect-with-planning-units.command.ts
- api/apps/api/src/modules/scenarios-features/intersect-with-pu/intersect-with-pu-events.service.ts
- api/apps/api/src/modules/scenarios-features/intersect-with-pu/intersect-with-pu.handler.ts
- api/apps/api/src/modules/scenarios-features/intersect-with-pu/intersect-with-pu.module.ts
- api/apps/api/src/modules/scenarios-features/move-data-from-preparation.handler.ts
- api/apps/geoprocessing/src/modules/scenario-planning-units-features-aggregate/scenario-planning-units-features-aggregate-processor.ts
- api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
- api/libs/planning-unit-features/src/job-input.ts
- app/layout/scenarios/edit/status/utils.tsx
- data/Makefile
- data/data_download/Makefile
- data/data_download/wdpa/Makefile
Issues:
- no "complete" event submitted ✅ 
- tile resolving fails ✅
> feat(tiles): use feature_list for tile scenario features

- api/package.json
- api/yarn.lock
> deps: bump mapshaper to fix dropping data issue

- docs/create-project-shapefiles.md
> docs(projects): creation and shapefiles approach

- app/hooks/map/index.ts
- app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
- app/layout/projects/new/form/planning-area-uploader/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/show/map/component.tsx
- app/store/slices/scenarios/detail.ts
> Fix(front):[MARXAN-954][MARXAN-938]

- api/apps/api/src/modules/projects-acl/index.ts
- api/apps/api/src/modules/projects-acl/project-acl.module.ts
- api/apps/api/src/modules/projects-acl/project-acl.service.spec.ts
- api/apps/api/src/modules/projects-acl/project-acl.service.ts
- api/apps/api/src/modules/published-project/controllers/publish-project.controller.ts
- api/apps/api/src/modules/published-project/published-project.module.ts
- api/apps/api/src/modules/published-project/published-project.service.ts
- api/apps/api/test/project/projects.fixtures.ts
- api/apps/api/test/utils/api-application.ts
> feat(published-project): acl

- app/layout/me/reset-password/component.tsx
- app/layout/projects/new/form/component.tsx
- app/layout/projects/new/form/country-region-selector/component.tsx
- app/layout/projects/new/form/country-region-selector/types.ts
- app/layout/projects/new/form/planning-area-selector/component.tsx
- app/store/slices/scenarios/detail.ts
[MARXAN-962](https://vizzuality.atlassian.net/browse/MARXAN-962)
[MARXAN-949](https://vizzuality.atlassian.net/browse/MARXAN-949)
---
> fix(front): [MARXAN-962][MARXAN-949]

- api/apps/api/src/modules/scenarios-features/stratification/stratification-query.service.ts
> fix(api): fix calculating protected area in stratification

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/main.ts
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/apps/geoprocessing/src/main.ts
Minor adjustments to get the project running natively.
> Minor adjustments to get the project running natively

- README.md
- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/main.ts
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/apps/geoprocessing/src/main.ts
https://vizzuality.atlassian.net/browse/MARXAN-1028
> use a distinct envvar to set daemon listen ports when running Express natively

- data/bots/lib/libbot/geo-feature-shapefiles.ts
- data/bots/lib/libbot/init.ts
- data/bots/lib/libbot/shapefile-uploader.ts
https://vizzuality.atlassian.net/browse/MARXAN-1001
> add support for custom feature shapefiles [MARXAN-1001]

- app/components/forms/select/component.tsx
- app/components/forms/select/multi/component.tsx
- app/components/forms/select/single/component.tsx
[MARXAN-1030]([https://vizzuality.atlassian.net/browse/MARXAN-1030)
> Fix(front):[MARXAN-1030]

- app/hooks/scenarios/index.ts
[MARXAN-968](https://vizzuality.atlassian.net/browse/MARXAN-968)
> Fix(front): exclude-include pu on  top of default ones[MARXAN-968]

- app/hooks/features/index.ts
- app/hooks/published-projects/index.ts
- app/layout/forgot-password/component.tsx
- app/pages/api/auth/[...nextauth].ts
[MARXAN-935](https://vizzuality.atlassian.net/browse/MARXAN-935)
[MARXAN-965](https://vizzuality.atlassian.net/browse/MARXAN-965)
> Fix(front):[MARXAN-935][MARXAN-965]

- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/geo-output.repository.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/solutions/planning-unit-selection-state.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/solutions/solution-aggregation/planning-unit-selection-calculator.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/geo-output/solutions/solution-aggregation/planning-unit-state-calculator.service.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.ts
This PR adds the calculation of PU usage on a per run basis to the parsing of calculation results.
[MARXAN-810](https://vizzuality.atlassian.net/browse/MARXAN-810)
> Add calculation of PU usage for each run

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/decorators/file-interceptors.decorator.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/uploads/index.ts
- api/apps/api/src/modules/uploads/upload-limits.ts
> feat: limit uploaded files size

- app/layout/projects/show/scenarios/component.tsx
- app/layout/projects/show/scenarios/types/component.tsx
- app/layout/scenarios/edit/analysis/cost-surface/component.tsx
- app/layout/scenarios/edit/status/constants.ts
> Feat(front): change texts

- api/apps/api/src/modules/planning-units/index.ts
- api/apps/api/src/modules/planning-units/planning-units-completion.service.ts
- api/apps/api/src/modules/planning-units/planning-units-queue.provider.ts
- api/apps/api/src/modules/planning-units/planning-units.module.ts
- api/apps/api/src/modules/planning-units/planning-units.service.spec.ts
- api/apps/api/src/modules/planning-units/planning-units.service.ts
- api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.handler.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-995
> feat(project): once pu are set, trigger relevant event

- api/apps/geoprocessing/src/migrations/geoprocessing/1637668828023-AddGeometryHashToWdpa.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1637668828024-WdpaGeometryUniqueness.ts
- api/apps/geoprocessing/src/modules/protected-areas/worker/protected-area-processor.ts
- api/apps/geoprocessing/test/integration/protected-areas/steps/shapefile-for-wdpa-world.ts
- api/apps/geoprocessing/test/integration/protected-areas/upload-shapefile-for-project.e2e-spec.ts
- api/libs/shapefile-converter/src/index.ts
- api/libs/shapefile-converter/src/shapefiles/shapefile-extractor.service.ts
- api/libs/shapefile-converter/src/shapefiles/shapefiles.module.ts
> feat(protected-area): allow to add multiple areas per project

- api/apps/api/src/modules/scenarios/protected-area/cleanup/cleanup.module.ts
- api/apps/api/src/modules/scenarios/protected-area/cleanup/collect-garbage.command.ts
- api/apps/api/src/modules/scenarios/protected-area/cleanup/collect-garbage.handler.ts
- api/apps/api/src/modules/scenarios/protected-area/cleanup/collect-garbage.integration.spec.ts
- api/apps/api/src/modules/scenarios/protected-area/cleanup/index.ts
- api/apps/api/src/modules/scenarios/protected-area/cleanup/protected-area-unlinked.saga.ts
- api/apps/api/src/modules/scenarios/protected-area/protected-area.module.ts
- api/apps/api/src/modules/scenarios/protected-area/selection/selection-update.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-924
> feat(protected-area): boilerplate for collecting garbage protected areas

- api/apps/api/src/decorators/is-valid-range.decorator.ts
- api/apps/api/src/modules/blm/values/repositories/project-blm-repository.module.ts
- api/apps/api/src/modules/blm/values/repositories/typeorm-project-blm-repository.ts
- api/apps/api/src/modules/projects/blm/blm-values-policy-factory.ts
- api/apps/api/src/modules/projects/blm/change-blm-range.command.ts
- api/apps/api/src/modules/projects/blm/change-blm-range.handler.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.spec.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.ts
- api/apps/api/src/modules/projects/blm/planning-unit-area-fetcher.ts
- api/apps/api/src/modules/projects/blm/project-blm.module.ts
- api/apps/api/src/modules/projects/blm/set-project-blm-handler.ts
- api/apps/api/src/modules/projects/dto/project-blm-values-response.dto.ts
- api/apps/api/src/modules/projects/dto/update-project-blm-range.dto.ts
- api/apps/api/src/modules/projects/project.api.entity.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
- api/apps/api/test/project/update-project-calibration.e2e-spec.ts
- api/apps/api/test/project/update-project-calibration.fixtures.ts
Implements an endpoint to update the BLM range of a project, calculating its BLM values
*WIP*
[MARXAN-1000
](https://vizzuality.atlassian.net/browse/MARXAN-1000)
---
> Feat marxan 1000 patch calibration endpoint

- app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
[MARXAN-1068](https://vizzuality.atlassian.net/browse/MARXAN-1068)
> fix(front): uploading big size files to adjust planning units

- app/hooks/me/index.ts
- app/hooks/me/types.ts
- app/layout/me/sign-up-confirmation/component.tsx
- app/layout/sign-up/component.tsx
[Sign up workflow](https://docs.google.com/document/d/1kEEgckbv6K7MoCpUSClJMUl3AV9hNUsjPN52CZte9DY/edit)
[MARXAN-1071](https://vizzuality.atlassian.net/browse/MARXAN-1071)
---
> feat(front): sign up confirmation

- app/layout/scenarios/show/map/component.tsx
[MARXAN-1073](https://vizzuality.atlassian.net/browse/MARXAN-1073)
> fix(front): cost surface layer show mode[MARXAN-1073]

- data/bots/lib/libbot/cost-surface.ts
- data/bots/lib/libbot/geo-feature-shapefiles.ts
- data/bots/lib/libbot/init.ts
- data/bots/lib/libbot/logger.ts
- data/bots/lib/libbot/marxan-bot.ts
- data/bots/lib/libbot/planning-area-shapefiles.ts
- data/bots/lib/libbot/scenario-status.ts
- data/bots/lib/libbot/scenarios.ts
- data/bots/lib/libbot/shapefile-uploader.ts
- data/bots/lib/libbot/util/sleep.ts
https://vizzuality.atlassian.net/browse/MARXAN-1010
https://vizzuality.atlassian.net/browse/MARXAN-1011
> libbot: add support for cost surfaces [MARXAN-1010] [MARXAN-1011]

- data/bots/lib/libbot/cost-surface.ts
- data/bots/lib/libbot/geo-feature-shapefiles.ts
- data/bots/lib/libbot/init.ts
- data/bots/lib/libbot/planning-area-shapefiles.ts
- data/bots/lib/libbot/selection-status.ts
- data/bots/lib/libbot/shapefile-uploader.ts
https://vizzuality.atlassian.net/browse/MARXAN-1022
> libbot: add support for locking in/out planning units from GeoJSON files

- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> CanCreate in import legacy project endpoint

- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> CanEditCheck in update project endpoint

- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> CanDelete in remove project endpoint

- api/apps/api/src/modules/clone/clone.module.ts
- api/apps/api/src/modules/clone/export/adapters/export-adapters.module.ts
- api/apps/api/src/modules/clone/export/adapters/resource-pieces.adapter.ts
- api/apps/api/src/modules/clone/export/adapters/typeorm-export.repository.ts
- api/apps/api/src/modules/clone/export/application/export-application.module.ts
- api/apps/api/src/modules/clone/export/application/export-project.command.ts
- api/apps/api/src/modules/clone/export/application/export-project.handler.spec.ts
- api/apps/api/src/modules/clone/export/application/export-project.handler.ts
- api/apps/api/src/modules/clone/export/domain/events/export-all-components-finished.event.ts
- api/apps/api/src/modules/clone/export/domain/events/export-component-finished.event.ts
- api/apps/api/src/modules/clone/export/domain/export/export.ts
- api/apps/api/src/modules/clone/export/domain/index.ts
- api/apps/api/src/modules/clone/export/export.module.ts
- api/apps/api/src/modules/clone/export/index.ts
- api/apps/api/src/modules/clone/index.ts
- api/apps/api/src/modules/clone/infra/export/export-piece.events-handler.ts
- api/apps/api/src/modules/clone/infra/export/export-queue.provider.ts
- api/apps/api/src/modules/clone/infra/export/export.infra.module.ts
- api/apps/api/src/modules/clone/infra/export/piece-export-requested.saga.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.command.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.module.ts
- api/apps/api/src/modules/projects/projects.service.ts
- api/apps/geoprocessing/src/app.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/project-metadata.ts
> feat(cloning): export flow

- api/apps/api/src/modules/access-control/access-control.types.ts
- api/apps/api/src/modules/access-control/index.ts
- api/apps/api/src/modules/projects/blm/change-blm-range.command.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> CanEdit in updateBLM endpoint

- app/components/table/component.tsx
[MARXAN-1094](https://vizzuality.atlassian.net/browse/MARXAN-1094)
> fix(front): update solutions table[MARXAN-1094]

- api/apps/api/src/modules/blm/values/project-blm-repo.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> CanView in project GetBLMValues endpoint 

- api/apps/api/src/modules/projects/project-details.controller.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/src/modules/projects/projects.service.ts
- api/apps/api/test/project/delete-project.e2e-spec.ts
- api/apps/api/test/project/delete-project.fixtures.ts
- api/apps/api/test/project/project-get.e2e-spec.ts
- api/apps/api/test/project/projects.fixtures.ts
- api/apps/api/test/project/update-project-calibration.e2e-spec.ts
- api/apps/api/test/project/update-project-calibration.fixtures.ts
- api/apps/api/test/project/update-project.e2e-spec.ts
- api/apps/api/test/project/update-project.fixtures.ts
> E2E tests for ACL in projects endpoints

- data/bots/core-demos/demo-australia/core.ts
- data/bots/core-demos/demo-brazil/core.ts
- data/bots/lib/libbot/async-job-status.ts
- data/bots/lib/libbot/geo-feature-shapefiles.ts
- data/bots/lib/libbot/init.ts
- data/bots/lib/libbot/projects.ts
- data/bots/lib/libbot/selection-status.ts
https://vizzuality.atlassian.net/browse/MARXAN-979
> libbot: add support for polling project status [MARXAN-979]

- data/bots/core-demos/demo-australia/core.ts
- data/bots/core-demos/demo-australia/lib.ts
- data/bots/core-demos/demo-brazil/core.ts
- data/bots/core-demos/demo-brazil/lib.ts
- data/bots/lib/libbot/geo-features.ts
- data/bots/lib/libbot/protected-areas.ts
https://vizzuality.atlassian.net/browse/MARXAN-1101
> libbot: update ProtectedAreas module to use newest protected areas workflow [MARXAN-1101]

- api/apps/api/src/modules/clone/export/adapters/node-archive-creator.ts
- api/apps/api/src/modules/clone/export/application/export-application.module.ts
- api/apps/api/src/modules/clone/export/application/get-archive.handler.ts
- api/apps/api/src/modules/clone/export/application/get-archive.query.ts
- api/apps/api/src/modules/clone/export/index.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
> feat(cloning): get export by id

- app/layout/partners/component.tsx
- app/layout/partners/constants.ts
[FIGMA DESIGNS](https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=6694%3A10654)
> Feat(front): partners section[MARXAN-1135]

- data/bots/core-demos/demo-okavango/core.ts
- data/bots/lib/libbot/planning-area-shapefiles.ts
Maybe this is too restrictive? But given the use case, and that we
should be expecting exactly a 201, I would go for 201 only nevertheless.
https://vizzuality.atlassian.net/browse/MARXAN-1142
> throw an error if API response is not 201 [MARXAN-1142]

- app/hooks/features/index.ts
- app/layout/scenarios/edit/features/add/list/component.tsx
- app/tailwind.config.js
This PR makes it so that, in the _"Add features"_ modal, custom features (user uploaded) are shown at the very top of the list. In order to do so, it makes use of the `isCustom` property added to the respective endpoint in https://github.com/Vizzuality/marxan-cloud/pull/683. 
1. Open a project  
2. Click to _"Edit"_ a scenario  
3. Click on the _"Features"_ tab   
4. Click the _"Add features"_ button  
- Verify that any custom features (if none, upload one) are shown at the very top, before all other features  
[MARXAN-967](https://vizzuality.atlassian.net/browse/MARXAN-967)
> Show custom features in the add modal on top

- api/apps/api/src/modules/clone/export/adapters/node-archive-creator.ts
- api/apps/api/src/modules/clone/export/adapters/resource-pieces.adapter.ts
- api/apps/api/src/modules/clone/export/application/export-project.handler.spec.ts
- api/apps/api/src/modules/clone/export/domain/events/export-component-requested.event.ts
- api/apps/api/src/modules/clone/export/domain/export/export.ts
- api/apps/api/src/modules/clone/infra/export/mark-export-as-finished.handler.ts
- api/apps/api/src/modules/clone/infra/export/piece-export-requested.saga.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.command.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.ts
- api/apps/geoprocessing/src/export/export-pieces.integration.spec.ts
- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom-grid.ts
- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom.ts
- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.ts
- api/apps/geoprocessing/src/export/pieces-exporters/project-config.ts
- api/libs/cloning/src/domain/clone-piece.ts
- api/libs/cloning/src/job-input.ts
- api/libs/files-repository/src/temp-storage.repository.ts
As per https://vizzuality.atlassian.net/browse/MARXAN-1109 
This PR adds : 
*  "dummy" pieces handlers
* fix on forever-pending job (`submitted` event instead `finished`)
Unpacked export:
> feat(cloning): add export configuration

- README.md
- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/ormconfig.ts
- api/apps/api/test/utils/queues.ts
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/apps/geoprocessing/src/ormconfig.ts
> The amount of redis noise on e2e tests is too damn high

- api/libs/code-guide/src/error-handling/01-entry-point/base.module.ts
- api/libs/code-guide/src/error-handling/01-entry-point/controller.ts
- api/libs/code-guide/src/error-handling/01-entry-point/error-handling-entry-point.integration.spec.ts
- api/libs/code-guide/src/error-handling/01-entry-point/facade.ts
- api/libs/code-guide/src/error-handling/01-entry-point/legacy-service.ts
- api/libs/code-guide/src/error-handling/01-entry-point/third-party-service.ts
- api/libs/code-guide/src/error-handling/02-module-contract/base.module.ts
- api/libs/code-guide/src/error-handling/02-module-contract/controller.ts
- api/libs/code-guide/src/error-handling/02-module-contract/facade.ts
- api/libs/code-guide/src/error-handling/02-module-contract/legacy-service.ts
- api/libs/code-guide/src/error-handling/02-module-contract/third-party-service.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/base.module.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/controller.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/facade.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/legacy-service.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/serializer.ts
- api/libs/code-guide/src/error-handling/03-errors-contract/third-party-service.ts
- api/libs/code-guide/src/error-handling/README.md
- api/libs/code-guide/src/error-handling/enum-union.ts
- api/libs/code-guide/tsconfig.lib.json
- api/nest-cli.json
- api/package.json
- api/tsconfig.json
Please start with `README.md` before code - hopefully it will navigate you smoothly.
Cheers!
> docs(code-guide): error handling

- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/scenario-data/input-files-fs.ts
- api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
- api/apps/geoprocessing/test/integration/marxan-run/run-worker.e2e-spec.ts
- api/apps/geoprocessing/test/worker-module/worker-module-di-usage.e2e-spec.ts
> Fix issues with tests not running deterministically

- api/apps/api/src/modules/blm/values/scenario-calibration-repo.ts
- api/apps/api/src/modules/scenarios/dto/scenario-blm-calibration-results.dto.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-final-results.repository.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-partial-results.geo.entity.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-partial-results.repository.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1641378102736-RenameScoreColumnToCostBlmResults.ts
- api/libs/blm-calibration/src/blm-final-results.geo.entity.ts
> Blm calibration partial and final results score property replaced by cost

- api/apps/api/src/modules/projects/blm/change-blm-range.handler.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.spec.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.ts
- api/apps/api/src/modules/projects/blm/set-project-blm-handler.ts
> Fix issues with BlmValuesCalculator

- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/scenario-metadata.ts
- api/libs/cloning/src/domain/clone-piece.ts
This PR defines a new `ClonePiece` (`scenario-metadata`) and adds a `PieceProcessor` for scenario metadata
[Jira issue](https://vizzuality.atlassian.net/browse/MARXAN-842)
> MARXAN-842 export scenario metadata

- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/test/projects.e2e-spec.ts
Small bug fix by not using proper WHERE ANY clause.
> MARXAN-1178-Projects listing not working for viewers and contributors users

- app/layout/home/banner/component.tsx
- app/tailwind.config.js
Use transform properties instead of position rules
https://css-tricks.com/tale-of-animation-performance/
> Home banner: improve animations

- app/layout/projects/show/scenarios/types/component.tsx
- app/layout/projects/show/scenarios/types/constants.ts
This PR updates the text on the _"Choose scenario type"_ modal.  
I also took the liberty of moving the text into a `constants.ts` file, to match what we have going on in recent components.   
- Open a project  
- Click _"Create scenario"_  
[MARXAN-1037](https://vizzuality.atlassian.net/browse/MARXAN-1037)
> Choose scenario type modal text updates

- app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
Add support for multipolygons inside the "adjust planning unit upload file"
> Adjust planning unit: support multipolygon

- app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
This PR will add `lastJobCheck` to `scenarioEditingMetadata` if it's not set (created via api, bot)
> Scenarios: add lastJobCheck to metadata if it does not exist

- api/apps/api/src/modules/clone/export/adapters/export-adapters.module.ts
- api/apps/api/src/modules/clone/export/adapters/resource-pieces.adapter.ts
- api/apps/api/src/modules/clone/export/adapters/resource-pieces/project-resource-pieces.adapter.ts
- api/apps/api/src/modules/clone/export/adapters/resource-pieces/scenario-resource-pieces.adapter.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
This PR adds a resource pieces adapter for projects
[Jira](https://vizzuality.atlassian.net/browse/MARXAN-832)
> MARXAN-832 project resource pieces adapter

- api/apps/api/src/modules/projects/project-checker/project-checker.module.ts
> add missing imports

- api/apps/api/test/utils/event-bus.test.utils.spec.ts
- api/apps/api/test/utils/event-bus.test.utils.ts
This PR adds `EventBusTestUtils` which allows waiting for specific events while testing
> test: added event bus testing utils

- api/apps/api/src/modules/clone/export/application/complete-piece.handler.ts
- api/apps/api/src/modules/clone/infra/export/export.infra.module.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.spec.ts
- api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.ts
[Error handling when adding export-piece job to queue](https://vizzuality.atlassian.net/browse/MARXAN-1102)
> feat: error handling when adding export-piece jobs to queue

- api/apps/api/src/modules/projects/dto/export.project.response.dto.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
- api/apps/api/test/project/get-export-file.e2e-spec.ts
- api/apps/api/test/project/get-latest-export.e2e-spec.ts
- api/apps/api/test/utils/api-application.ts
[Consider storing exportId for given project](https://vizzuality.atlassian.net/browse/MARXAN-1130)
> feat: Endpoint for getting latest exportId for a given project

- api/apps/api/src/modules/clone/export/application/get-archive.handler.ts
- api/apps/api/src/modules/clone/export/application/get-archive.query.ts
- api/apps/api/src/modules/clone/export/export.module.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
[Add file streamer for repository (fetch/fs) when proxying archive](https://vizzuality.atlassian.net/browse/MARXAN-1129)
> ref: use of file stream in GetArchiveHandler

- ENV_VARS.md
- README.md
This should make the setup process clearer for newcomers. There's more that could be done, and this is not meant to be exhaustive, but I think it's a good first deliverable for our friends at TNC to take a look at, and try to run the platform - we can iterate once they give us feedback on which issues they had
> Update setup docs

- docs/ARCHITECTURE_access-control.md
https://vizzuality.atlassian.net/browse/MARXAN-1139
> add details to auth overview

- docs/features/scenario-workflow/frontend.md
[MARXAN-1141](https://vizzuality.atlassian.net/browse/MARXAN-1141)
> docs(front): new workflow endpoints[MARXAN-1141]

- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.spec.ts
- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.ts
This PR adds the implementation of `PlanningAreaGadm` export piece processor
[PieceExportProvider - PlanningAreaGadm](https://vizzuality.atlassian.net/browse/MARXAN-1148)
> feat: planning-area-gadm export piece processor

- app/components/tabs/component.tsx
- app/layout/pill/component.tsx
- app/layout/scenarios/edit/name/component.tsx
- app/layout/scenarios/edit/tabs/component.tsx
- app/layout/scenarios/edit/tabs/constants.ts
- app/utils/utils-scenarios.js
[MARXAN-1247](https://vizzuality.atlassian.net/browse/MARXAN-1247)
> feat(front): new workflow tabs[MARXAN-1247]

- app/public/robots.txt
- app/public/sitemap.xml
[MARXAN-819](https://vizzuality.atlassian.net/browse/MARXAN-819)
[MARXAN-820](https://vizzuality.atlassian.net/browse/MARXAN-820)
> Feat(front): SEO[MARXAN-819][MARXAN-820]

- app/components/tabs/component.stories.tsx
- app/layout/scenarios/edit/analysis/component.tsx
- app/layout/scenarios/edit/features/add/component.tsx
- app/layout/scenarios/edit/features/component.tsx
- app/layout/scenarios/edit/features/list/component.tsx
- app/layout/scenarios/edit/features/targets/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/edit/planning-unit/component.tsx
- app/layout/scenarios/edit/status/actions/failure.tsx
- app/layout/scenarios/edit/tabs/constants.ts
- app/layout/scenarios/edit/wdpa/component.tsx
- app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
- app/utils/tabs.ts
Refactor name of tabs and subtabs.
Still old names for subtabs in analysis and solutions
> front(refactor): tabs and subtabs naming

- docs/download-upload-clone/brief.md
- docs/download-upload-clone/storage/brief.md
- docs/download-upload-clone/storage/high-level-design.md
https://vizzuality.atlassian.net/browse/MARXAN-816
> storage for cloning/import/export: brief and high-level design [MARXAN-816]

- docs/features/role-based-access-control/managing-roles/brief.md
https://vizzuality.atlassian.net/browse/MARXAN-1124
> add brief for user workflow: adding users to projects/scenarios [MARXAN-1124]

- api/apps/api/src/modules/projects/block-guard/marxan-block-guard.service.spec.ts
- api/apps/api/src/modules/projects/block-guard/marxan-block-guard.service.ts
- api/apps/api/src/modules/projects/project-checker/marxan-project-checker.service.ts
- api/apps/api/src/modules/projects/project-checker/project-checker.service.spec.ts
- api/apps/api/src/modules/scenarios/scenario-checker/marxan-scenario-checker.service.ts
- api/apps/api/src/modules/scenarios/scenario-checker/scenario-checker.service.spec.ts
- api/apps/api/test/project/request-project-export.e2e-spec.ts
- api/apps/api/test/utils/project-checker.service-fake.ts
- api/apps/api/test/utils/scenario-checker.service-fake.ts
This PR adds pending import checks to `MarxanBlockGuard` and implements some missing tests
> feat: added pending import checking in MarxanBlockGuard

- data/bots/lib/libbot/geo-feature-shapefiles.ts
https://vizzuality.atlassian.net/browse/MARXAN-1292
> decouple filename from name in GeoFeatureMetadata [MARXAN-1292]

- api/apps/api/src/decorators/shapefile.decorator.ts
- api/apps/api/src/modules/projects/dto/planning-area-response.dto.ts
- api/apps/api/src/modules/scenarios/dto/shapefile.geojson.response.dto.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1641582332000-FixUniquenessOfPuGeoms.ts
https://vizzuality.atlassian.net/browse/MARXAN-1304
> add typing on geojson response and apply right() wrapping

- app/layout/home/banner/component.tsx
- app/layout/home/features/component.tsx
- app/layout/home/features/item/component.tsx
- app/layout/home/features/item/index.ts
- app/layout/home/partners/component.tsx
- app/layout/home/support/component.tsx
- app/layout/home/support/item/component.tsx
- app/layout/home/support/item/index.ts
- app/pages/index.tsx
Use of react-intersection-observer and frame-motion in order to have smoother entry to homepage sections when scrolling.
[MARXAN-1300](https://vizzuality.atlassian.net/browse/MARXAN-1300)
> Feat(front): homepage sections entry animations [MARXAN-1300]

- docs/features/compare-scenarios-difference-maps/high-level-design.md
- docs/features/compare-scenarios-difference-maps/requirements.md
> hld and requirements for difference maps

- docs/features/map-tiles-custom-areas/high-level-design.md
- docs/features/map-tiles-custom-areas/requirements.md
> custom areas tiles hld

- api/apps/api/test/scenario-protected-areas/fixtures.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1641582332000-FixUniquenessOfPuGeoms.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1643983434000-FixUniquenessOfCustomProtectedAreas.ts
- api/apps/geoprocessing/src/modules/protected-areas/worker/protected-area-processor.ts
- api/apps/geoprocessing/test/integration/protected-areas/steps/shapefile-for-wdpa-world.ts
- api/apps/geoprocessing/test/integration/protected-areas/upload-shapefile-for-project.e2e-spec.ts
- api/apps/geoprocessing/test/tiles/protected-area.fixtures.ts
https://vizzuality.atlassian.net/browse/MARXAN-1245
> upsert when uploading same protected area for project [MARXAN-1245]

- docs/process/development.md
> docs(process): development flow

- api/api.Dockerfile
- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/geo.Dockerfile
- infrastructure/main.tf
- infrastructure/modules/firewall/main.tf
- infrastructure/modules/node_pool/main.tf
- infrastructure/modules/node_pool/variables.tf
- infrastructure/modules/redis/outputs.tf
- infrastructure/outputs.tf
- kubernetes/main.tf
- kubernetes/modules/api/main.tf
- kubernetes/modules/api/variable.tf
- kubernetes/modules/api/versions.tf
- kubernetes/modules/database/main.tf
- kubernetes/modules/secrets/main.tf
- kubernetes/modules/secrets/variable.tf
> API deployment

- app/hooks/features/index.ts
- app/layout/scenarios/edit/features/set-up/add/add-modal/list/component.tsx
- app/layout/scenarios/edit/features/set-up/add/add-modal/uploader/component.tsx
Also refetch method is removed and added projectId to invalidate query after uploaded. See comment on code.
[MARXAN-1287](https://vizzuality.atlassian.net/browse/MARXAN-1287)
> fix(front): loader on upload custom features [MARXAN-1287]

- app/layout/projects/new/form/component.tsx
- app/layout/projects/new/form/planning-area-selector/component.tsx
- app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
- app/layout/projects/new/form/planning-area-selector/planning-unit-grid/component.tsx
[Figma Designs](https://www.figma.com/file/DpHfvKRBNQylK71c0nq2FD/Marxan-Visual_Internal?node-id=6713%3A10958)
[MARXAN-1240](https://vizzuality.atlassian.net/browse/MARXAN-1240)
> fix(front): min and max area size validator 

- api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
- api/apps/geoprocessing/src/import/pieces-importers/planning-area-gadm.piece-importer.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/planning-area-gadm.ts
This PR adds piece importer for `PlanningAreaGAdm`
> feat: planning area gadm piece importer

- api/apps/api/src/modules/scenarios/protected-area/selection/selection-update.service.integration.spec.ts
- api/apps/api/src/modules/webshot/webshot.service.ts
- api/package.json
- api/yarn.lock
- docker-compose.yml
- webshot/Dockerfile
- webshot/src/domain/solutions-report/solutions-report.ts
- webshot/src/domain/solutions-report/wait-function.ts
- webshot/src/main.ts
https://vizzuality.atlassian.net/browse/MARXAN-1314
> wait for report page to be ready for webshot via waitForFunction

- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
- api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom-grid.piece-exporter.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/planning-area-grid-custom.ts
This PR adds piece exporter for `PlanningAreaGridCustom` clone piece
> feat: planning area grid custom piece exporter

- api/apps/api/src/modules/projects/project.api.entity.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
https://vizzuality.atlassian.net/browse/MARXAN-1336
> expose the public status of projects in singular and plural project requests [MARXAN-1336]

- docs/features/role-based-access-control/implicit-roles/brief.md
- docs/features/role-based-access-control/implicit-roles/high-level-design.md
https://vizzuality.atlassian.net/browse/MARXAN-1164
> docs(api): implicit roles - documentation [MARXAN-1164]

- api/apps/api/src/modules/users/dto/create.user.dto.ts
- api/apps/api/src/modules/users/dto/update.user.dto.ts
- api/apps/api/src/modules/users/users.controller.ts
- api/apps/api/src/modules/users/users.service.ts
- api/apps/api/test/users.e2e-spec.ts
-Adds users endpoint to search for full email.
-Adds tests for this endpoint.
> MARXAN-1124-add-users-to-project-workflow

- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/project-custom-protected-areas.piece-exporter.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-protected-areas.ts
This PR adds project custom protected areas piece exporter
[export piece (project): custom protected areas](https://vizzuality.atlassian.net/browse/MARXAN-1318)
> feat: project custom protected areas piece exporter

- api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
- api/apps/geoprocessing/src/import/pieces-importers/planning-area-custom.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/project-custom-protected-areas.piece-importer.ts
This PR adds project custom protected areas piece importer
[import piece (project): custom protected areas](https://vizzuality.atlassian.net/browse/MARXAN-1321)
> feat: project custom protected areas importer

- api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-protected-areas.piece-importer.ts
This PR adds piece importer for `ScenarioProtectedAreas` `ClonePiece`. 
[import piece (scenario): protected area selection (IUCN categories and custom protected area ids) + threshold](https://vizzuality.atlassian.net/browse/MARXAN-1322)
> feat: scenario protected areas piece importer

- api/apps/geoprocessing/src/import/pieces-importers/scenario-protected-areas.piece-importer.ts
This PR fixes a bug of `ScenarioProtectedAreasPieceImporter` that was causing import process failures. PostgreSQL `IN` operator doesn't work with empty arrays
> fix: scenario protected areas piece importer

- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/scenario-run-results.piece-exporter.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/scenario-run-results.ts
This PR adds  scenario run results piece exporter
[export piece (scenario): previous run results](https://vizzuality.atlassian.net/browse/MARXAN-1354)
> feat: scenario run results piece exporter

- api/apps/geoprocessing/src/migrations/geoprocessing/1646314135070-AlterPlanningUnitsTables.ts
https://vizzuality.atlassian.net/browse/MARXAN-1385
> remove constraint over `geometry`-type column

- api/apps/api/src/bootstrap-app.ts
- api/libs/webshot/src/webshot.dto.ts
- webshot/src/domain/solutions-report/report-options.dto.ts
- webshot/src/domain/solutions-report/solutions-report.ts
https://vizzuality.atlassian.net/browse/MARXAN-1407
> accept solutionId for summary report webshot requests [MARXAN-1407]

- api/apps/api/src/migrations/api/1648642114880-AddClonePieceForScenarioFeatures.ts
- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/project-custom-features.piece-exporter.ts
- api/apps/geoprocessing/src/import/db-cleanup/db-cleanup.module.ts
- api/apps/geoprocessing/src/import/db-cleanup/db-cleanup.processor.ts
- api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
- api/apps/geoprocessing/src/import/pieces-importers/project-custom-features.piece-importer.ts
- api/libs/cloning/src/domain/clone-piece.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-features.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/scenario-features-data.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/user-uploaded-features.ts
This PR adds piece exporter and piece importer for `ClonePiece.ProjectCustomFeatures`
- [export piece (project): custom features](https://vizzuality.atlassian.net/browse/MARXAN-1320)
- [import piece (project): custom features](https://vizzuality.atlassian.net/browse/MARXAN-1323)
> Feat marxan 1320 and 1323/export and import project custom features

- api/apps/api/src/modules/scenarios/input-files/spec.dat.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-812
> enforce `target` as null in generated spec.dat files [MARXAN-812]

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/src/filters/all-exceptions.exception.filter.ts
- api/apps/api/src/modules/admin-areas/admin-areas.service.ts
- api/apps/api/src/modules/api-events/api-events.service.ts
- api/apps/api/src/modules/countries/countries.service.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/organizations/organizations.service.ts
- api/apps/api/src/modules/projects/projects-crud.service.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
- api/apps/api/src/modules/published-project/published-project-crud.service.ts
- api/apps/api/src/modules/scenarios-features/scenario-features-gap-data.service.ts
- api/apps/api/src/modules/scenarios-features/scenario-features-output-gap-data.service.ts
- api/apps/api/src/modules/scenarios-features/scenario-features.service.ts
- api/apps/api/src/modules/scenarios-planning-unit/scenarios-planning-unit.service.ts
- api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
- api/apps/api/src/modules/scenarios/solutions-result/solution-result-crud.service.ts
- api/apps/api/src/modules/users/users.service.ts
- api/apps/api/src/utils/config.utils.ts
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/apps/geoprocessing/src/filters/all-exceptions.exception.filter.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-shared/workspace/shared-storage.ts
- api/apps/geoprocessing/src/modules/protected-areas/worker/protected-area-processor.ts
- api/apps/geoprocessing/src/modules/scenarios/cost-template/cost-template-generator.ts
- api/apps/geoprocessing/src/utils/config.utils.ts
- api/libs/shapefile-converter/src/shapefiles/shapefile-extractor.service.ts
- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/modules/geoprocessing/main.tf
- infrastructure/kubernetes/modules/geoprocessing/variable.tf
https://vizzuality.atlassian.net/browse/MARXAN-1446
> allow to preserve temporary files [MARXAN-1446]

- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/variables.tf
- infrastructure/kubernetes/vars/terraform.tfvars
> Add additional config var for container registry name

- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
- api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
- api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
- api/apps/geoprocessing/src/export/pieces-exporters/scenario-features-specification.piece-exporter.ts
- api/apps/geoprocessing/test/integration/clonning/fixtures.ts
- api/apps/geoprocessing/test/integration/clonning/scenario-features-specification.piece-exporter.e2e-spec.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/features-specification.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/scenario-features-specification.ts
This PR adds scenario features specification piece exporter
[export piece (scenario): features specification](https://vizzuality.atlassian.net/browse/MARXAN-1346)
> feat: scenario features specification piece exporter

- infrastructure/base/modules/network/main.tf
- infrastructure/base/modules/node_pool/variables.tf
- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/modules/api/main.tf
- infrastructure/kubernetes/modules/api/variable.tf
- infrastructure/kubernetes/modules/geoprocessing/main.tf
- infrastructure/kubernetes/modules/geoprocessing/variable.tf
https://vizzuality.atlassian.net/browse/MARXAN-1450
> bump up resources

- api/apps/api/src/modules/users/users.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/marxan-sandbox-blm-runner.service.ts
- api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
- Fixes wrong projectId being used on URL for webshot.
- Adds isAdmin flag to GET /users
> Fix - Webshot URL - Adds IsAdmin to findAll Users request

- api/apps/api/src/modules/users/users.controller.ts
- api/apps/api/src/modules/users/users.service.ts
- api/apps/api/test/users.e2e-spec.ts
-Adds 2 new endpoints: to block and unblock users by Id.
-Adds tests for those endpoints.
> Admins block users endpoints

- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/scenarios/edit/map/component.tsx
Check if "_selected features_" would be the most appropriate name and if the color is clear to the user.
[MARXAN-1313](https://vizzuality.atlassian.net/browse/MARXAN-1313)
---
> feat(front): features highlight legend on gap-analysis[MARXAN-1313]

- app/cypress/integration/home__test__.js
- app/hooks/projects/index.ts
- app/hooks/projects/types.ts
- app/layout/projects/show/header/toolbar/component.tsx
- app/layout/projects/show/status/actions/done.tsx
- app/layout/projects/show/status/actions/failure.tsx
- app/layout/projects/show/status/constants.ts
[MARXAN-1477](https://vizzuality.atlassian.net/browse/MARXAN-1477)
---
> feat(front): download project[MARXAN-1477]

- app/layout/scenarios/edit/status/actions/done.tsx
- app/layout/scenarios/edit/status/actions/failure.tsx
- app/layout/scenarios/edit/status/constants.ts
[MARXAN-1251](https://vizzuality.atlassian.net/browse/MARXAN-1251)
---
> feat(front): update protected areas after uploading custom[MARXAN-1251]

- api/apps/api/src/modules/users/users.controller.ts
- api/apps/api/src/modules/users/users.service.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-partial-results.repository.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/marxan-runner.factory.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/marxan-sandbox-blm-runner.service.ts
-Adds projectId to puuid filtering to avoid getting puids from a different project.
-Adds search to users GET endpoint.
> ProjectId-PUnits-usersSearch

- api/apps/api/src/migrations/api/1649833978405-AddClonningEvents.ts
- api/apps/api/src/modules/clone/export/application/export-project.handler.ts
- api/apps/api/src/modules/clone/export/domain/events/export-requested.event.ts
- api/apps/api/src/modules/clone/export/domain/export/export.ts
- api/apps/api/src/modules/clone/import/domain/events/all-pieces-imported.event.ts
- api/apps/api/src/modules/clone/import/domain/import/import.ts
- api/apps/api/src/modules/clone/infra/export/archive-ready.saga.ts
- api/apps/api/src/modules/clone/infra/export/export-started.saga.ts
- api/apps/api/src/modules/clone/infra/export/export.infra.module.ts
- api/apps/api/src/modules/clone/infra/export/mark-clone-as-submitted.command.ts
- api/apps/api/src/modules/clone/infra/export/mark-clone-as-submitted.handler.ts
- api/apps/api/src/modules/clone/infra/export/mark-export-as-failed.handler.ts
- api/apps/api/src/modules/clone/infra/import/all-pieces-imported.saga.ts
- api/apps/api/src/modules/clone/infra/import/import.infra.module.ts
- api/apps/api/src/modules/clone/infra/import/mark-clone-as-finished.command.ts
- api/apps/api/src/modules/clone/infra/import/mark-clone-as-finished.handler.ts
- api/apps/api/src/modules/clone/infra/import/mark-import-as-failed.handler.ts
- api/apps/api/src/modules/projects/job-status/job-status.view.api.entity.ts
- api/apps/api/src/modules/projects/job-status/project-status.view.api.entity.ts
- api/libs/api-events/src/api-event-kinds.enum.ts
This PR adds clone api events and emits them
[add cloning api events](https://vizzuality.atlassian.net/browse/MARXAN-1481)
> feat: add  clone api events and emit them

- api/apps/api/src/modules/clone/export/application/export-project.handler.ts
- api/apps/api/src/modules/clone/export/application/export-scenario.handler.ts
- api/apps/api/src/modules/scenarios/dto/scenario-clone.dto.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/geoprocessing/src/export/pieces-exporters/scenario-run-results.piece-exporter.ts
- api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts
This PR adds an endpoint for cloning scenarios
[API endpoint /api/v1/scenarios/:scenarioId/clone](https://vizzuality.atlassian.net/browse/MARXAN-1465)
> feat: clone scenario endpoint

- api/apps/api/src/modules/clone/import/application/export-config-reader.ts
- api/apps/api/test/project/clone-project.e2e-spec.ts
- api/apps/api/test/project/import-project.e2e-spec.ts
- api/apps/api/test/scenarios/clone-scenario.e2e-spec.ts
This PR adds test for cloning project and scenario endpoints
> feat : add clone project and clone scenario e2e test

- api/apps/api/src/modules/users/user-requests-info.ts
- api/apps/api/src/ormconfig.ts
- api/apps/geoprocessing/src/ormconfig.ts
https://vizzuality.atlassian.net/browse/MARXAN-1489
> use AppConfig.getBoolean(), avoid breaking if config is not set [MARXAN-1489]

- api/api.Dockerfile
- api/geo.Dockerfile
> Compile specific nest app on each docker image

- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
This reverts commit c6791d2b8bb15312de3335a99b9ec301d4dd623f as this is now obsolete (after merging #1009)
> Revert "(delete) add api config items to geoprocessing service" [MARXAN-1490]

- app/hooks/projects/index.ts
- app/hooks/projects/types.ts
- app/hooks/published-projects/index.ts
- app/hooks/scenarios/index.ts
- app/layout/community/published-projects/detail/component.tsx
- app/layout/community/published-projects/list/table/component.tsx
- app/layout/community/published-projects/list/table/item/component.tsx
- app/layout/footer/component.tsx
- app/layout/home/intro/component.tsx
- app/layout/projects/show/header/toolbar/publish-btn/component.tsx
- app/layout/projects/show/header/toolbar/publish-btn/publish-modal/component.tsx
- app/pages/api/publish/[pid]/index.ts
- app/pages/api/reports/scenarios/[sid]/blm.ts
- app/pages/community/projects/index.tsx
This PR adds:
- proxy to send Cookies to the publish endpoint
> Published project proxy

- api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
This PR fixes a bug regarding project planning unit grid creation. Now, projects pu are created per chunks of 1000 units to avoid reaching parameter limits
[Creating a grid with over X planning units fails](https://vizzuality.atlassian.net/browse/MARXAN-1473)
> fix: PlanningUnitsJobProcessor projects pu creation

- api/apps/api/src/modules/scenarios/cost-surface/application/cost-surface-application.module.ts
- api/apps/api/src/modules/scenarios/cost-surface/application/set-initial-cost-surface.command.ts
- api/apps/api/src/modules/scenarios/cost-surface/application/set-initial-cost-surface.handler.ts
- api/apps/api/src/modules/scenarios/cost-surface/infra/surface-cost.events-handler.spec.ts
- api/apps/api/src/modules/scenarios/cost-surface/infra/surface-cost.events-handler.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
- api/apps/api/src/utils/acl.utils.ts
- api/apps/geoprocessing/src/modules/surface-cost/adapters/available-planning-units-repository.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/__mocks__/area.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/__mocks__/job.data.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-processor.spec.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-processor.ts
- api/apps/geoprocessing/src/modules/surface-cost/ports/available-planning-units/get-available-planning-units.ts
- api/libs/scenario-cost-surface/src/surface-cost-job-input.ts
This PR refactors how cost surface initialization is made. The cost of each planning unit is equal to the area in km2
[default PU cost should equal PU area](https://vizzuality.atlassian.net/browse/MARXAN-1502)
> ref: cost surface initialization

- api/apps/geoprocessing/config/staging.json
Part of https://vizzuality.atlassian.net/browse/MARXAN-1514
> configure webshot service url for geoprocessing service in k8s clusters [MARXAN-1514]

- api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts
- api/apps/geoprocessing/test/integration/cloning/piece-importers/project-metadata.piece-importer.e2e-spec.ts
This PR updates how imported project are named
[BE - Upload project name](https://vizzuality.atlassian.net/browse/MARXAN-1517)
> feat: imported project names

- app/layout/scenarios/edit/parameters/advanced-settings/constants.tsx
This fixes a tiny typo, as reported by TNC while testing
> fix typo (lenght->length)

- api/apps/geoprocessing/src/modules/scenarios/cost-template/cost-template-generator.ts
https://vizzuality.atlassian.net/browse/MARXAN-1518
> use more descriptive prefix for cost surface template shapefile component files

- api/apps/api/src/modules/scenarios/cost-surface/infra/surface-cost.events-handler.ts
- api/apps/geoprocessing/src/modules/surface-cost/adapters/available-planning-units-repository.ts
- api/apps/geoprocessing/src/modules/surface-cost/adapters/typeorm-cost-surface.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/__mocks__/cost-surface-repo.fake.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/__mocks__/get-available-puids.fake.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-processor.spec.ts
- api/apps/geoprocessing/src/modules/surface-cost/application/surface-cost-processor.ts
- api/apps/geoprocessing/src/modules/surface-cost/ports/available-planning-units/get-available-planning-units.ts
- api/apps/geoprocessing/src/modules/surface-cost/ports/persistence/cost-surface-persistence.port.ts
- api/apps/geoprocessing/test/integration/cost-surface/cost-surface-repo/cost-surface-update.e2e-spec.ts
This PR fixes and refactors how initial cost surfaces are generated
[unknown issue with cost surface](https://vizzuality.atlassian.net/browse/MARXAN-1513)
> fix: initial surface cost generation

- api/apps/api/src/migrations/api/1651666472019-RemoveFeatureSetFromScenarios.ts
- api/apps/api/src/modules/scenarios/scenario.api.entity.ts
- api/apps/api/src/modules/scenarios/scenarios.service.ts
This PR removes unnecessary column from `scenarios` table: `feature_set`
[remove feature_set column from scenarios table](https://vizzuality.atlassian.net/browse/MARXAN-1522)
> ref: remove feature set column from scenarios

- api/apps/api/src/migrations/api/1652099652734-AddImportLegacyProjectsApiEvents.ts
- api/apps/api/src/modules/projects/job-status/project-status.view.api.entity.ts
- api/libs/api-events/src/api-event-kinds.enum.ts
This PR adds api events for legacy project imports
[Add legacy project import api events](https://vizzuality.atlassian.net/browse/MARXAN-1531)
> feat: import legacy projects api events

- api/apps/api/src/migrations/api/1652344048139-AddLegacyProjectImportTables.ts
- api/apps/api/src/modules/legacy-project-import/application/legacy-project-import.application.module.ts
- api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import-component.ts
- api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.repository.ts
- api/apps/api/src/modules/legacy-project-import/infra/entities/legacy-project-import-component.api.entity.ts
- api/apps/api/src/modules/legacy-project-import/infra/entities/legacy-project-import-file.api.entity.ts
- api/apps/api/src/modules/legacy-project-import/infra/entities/legacy-project-import.api.entity.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import-memory.repository.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import-typeorm.repository.ts
- api/apps/api/src/modules/legacy-project-import/legacy-project-import.module.ts
- api/apps/api/test/integration/typeorm-legacy-project-import.repository.integration.e2e-spec.ts
This PR adds `LegacyProjectImportRepository`
[Create legacy project import repository port. Implement typeorm and memory adapters](https://vizzuality.atlassian.net/browse/MARXAN-1542)
> feat: legacy project imports repository

- api/apps/api/src/modules/legacy-project-import/application/complete-import-legacy-project-piece.command.ts
- api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-piece-as-failed.command.ts
- api/apps/api/src/modules/legacy-project-import/infra/import-legacy-project-piece.events-handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/infra/import-legacy-project-piece.events-handler.ts
- api/libs/legacy-project-import/src/job-output.ts
This PR adds `ImportLegacyProjectPieceEventsHandler`
[Implement events handler for import legacy project piece jobs](https://vizzuality.atlassian.net/browse/MARXAN-1546)
> feat: import legacy project piece events handler

- api/apps/api/src/modules/legacy-project-import/application/legacy-project-import.application.module.ts
- api/apps/api/src/modules/legacy-project-import/application/start-legacy-project-import.command.ts
- api/apps/api/src/modules/legacy-project-import/application/start-legacy-project-import.handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/application/start-legacy-project-import.handler.ts
- api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import-memory.repository.ts
This PR adds start legacy project import command and command handler
[Create command handler for starting a legacy project import](https://vizzuality.atlassian.net/browse/MARXAN-1543)
> feat: add start legacy project import command and handler

- api/apps/geoprocessing/src/export/pieces-exporters/scenario-features-data.piece-exporter.ts
This PR fixes a bug of `scenario-features-data` piece exporter
[Export fails when making project public](https://vizzuality.atlassian.net/browse/MARXAN-1564)
> fix: scenarios features data piece exporter

- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/modules/api/main.tf
- infrastructure/kubernetes/modules/api/variable.tf
- infrastructure/kubernetes/modules/geoprocessing/main.tf
- infrastructure/kubernetes/modules/geoprocessing/variable.tf
- infrastructure/kubernetes/modules/ingress/main.tf
- infrastructure/kubernetes/modules/storage/main.tf
- infrastructure/kubernetes/modules/storage/variable.tf
- infrastructure/kubernetes/modules/volumes/main.tf
- infrastructure/kubernetes/modules/volumes/variable.tf
- infrastructure/kubernetes/variables.tf
- infrastructure/kubernetes/vars/terraform.tfvars
https://vizzuality.atlassian.net/browse/MARXAN-1453
> Terraform config for PVC for shared storage for project cloning [MARXAN-1453]

- api/apps/geoprocessing/src/import/pieces-importers/scenario-features-specification.piece-importer.ts
This PR fixes `features-specification` piece importer
[Fix features specification piece importer](https://vizzuality.atlassian.net/browse/MARXAN-1570)
> fix: scenario features specification piece importer

- app/layout/scenarios/edit/parameters/blm-calibration/chart/component.tsx
- app/layout/scenarios/edit/parameters/blm-calibration/results/component.tsx
Please, see discussion on JIRA.
[MARXAN-1392](https://vizzuality.atlassian.net/browse/MARXAN-1392)
> fix(front): BLM chart improvements [MARXAN-1392]

- app/components/scenarios/item/component.tsx
- app/components/scenarios/item/settings/component.tsx
- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/layout/projects/show/scenarios/component.tsx
- app/layout/scenarios/edit/status/actions/done.tsx
- app/layout/scenarios/edit/status/actions/failure.tsx
- app/layout/scenarios/edit/status/constants.ts
This PR adds:
- Cloning button inside list scenario settings
> Scenario: cloning

- api/apps/geoprocessing/src/export/pieces-exporters/scenario-features-specification.piece-exporter.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-features-data.piece-importer.ts
- api/apps/geoprocessing/test/integration/cloning/piece-importers/scenario-features-data.piece-importer.e2e-spec.ts
This PR fixes a bug in `scenario-features-data` piece importer
[Error when exporting a project already exported](https://vizzuality.atlassian.net/browse/MARXAN-1575)
> fix: scenario features data piece importer

- app/components/map/component.tsx
- app/components/map/controls/loading/component.stories.tsx
- app/components/map/controls/loading/component.tsx
- app/components/map/controls/loading/index.ts
- app/layout/projects/new/map/component.tsx
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/new/map/component.tsx
- app/layout/scenarios/reports/blm/map/component.tsx
- app/layout/scenarios/reports/blm/webshot-status/component.tsx
- app/layout/scenarios/reports/frequency/map/component.tsx
- app/layout/scenarios/reports/frequency/webshot-status/component.tsx
- app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
- app/layout/scenarios/reports/solutions/solution-frequency-page/map/component.tsx
- app/layout/scenarios/reports/solutions/webshot-status/component.tsx
This PR adds:
- map loader
- map loader control
- report maps set ready when the tiles are loaded
> Map loader

- app/hooks/scenarios/index.ts
- app/layout/projects/all/list/component.tsx
This PR:
- add a double check when you try to duplicate to be sure that there aren't no running jobs
> Duplicate: no running jobs

- app/layout/scenarios/edit/planning-unit/protected-areas/categories/component.tsx
[Figma prototype](https://www.figma.com/file/DpHfvKRBNQylK71c0nq2FD/Marxan-Visual_Internal?node-id=6694%3A10654)
[MARXAN-1578](https://vizzuality.atlassian.net/browse/MARXAN-1578)
> feat(front): add credentials [MARXAN-1578]

- api/apps/api/src/modules/blm/values/repositories/project-blm/memory-project-blm-repository.ts
- api/apps/api/src/modules/blm/values/repositories/project-blm/project-blm.api.entity.ts
- api/apps/api/src/modules/blm/values/repositories/project-blm/typeorm-project-blm-repository.ts
- api/apps/api/src/modules/blm/values/repositories/scenario-blm/memory-scenario-blm-repository.ts
- api/apps/api/src/modules/blm/values/repositories/scenario-blm/scenario-blm.api.entity.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.spec.ts
- api/apps/api/src/modules/projects/blm/domain/blm-values-calculator.ts
- api/apps/api/src/modules/projects/dto/project-blm-values-response.dto.ts
- api/apps/api/src/modules/projects/dto/update-project-blm-range.dto.ts
- api/apps/api/src/modules/scenarios/dto/blm-range.dto.ts
- api/apps/api/src/modules/scenarios/dto/start-scenario-blm-calibration.dto.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
- api/apps/api/test/scenarios/start-scenario-calibration.fixtures.ts
This PR changes default blm range
[Update BLM by default values](https://vizzuality.atlassian.net/browse/MARXAN-1551)
> ref: change blm default range

- api/apps/api/src/modules/legacy-project-import/application/legacy-project-import.application.module.ts
- api/apps/api/src/modules/legacy-project-import/application/run-legacy-project-import.handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/infra/import-legacy-project-piece.events-handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import-piece-requested.saga.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import.infra.module.ts
- api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import.repository.module.ts
- api/apps/api/src/modules/legacy-project-import/infra/schedule-legacy-project-import-piece.command.ts
- api/apps/api/src/modules/legacy-project-import/infra/schedule-legacy-project-import-piece.handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/infra/schedule-legacy-project-import-piece.handler.ts
- api/libs/legacy-project-import/src/job-input.ts
- api/libs/legacy-project-import/src/job-output.ts
This PR adds legacy project import piece requested saga and the scheduler for legacy project import pieces
[Implement LegacyProjectImportPieceRequested saga](https://vizzuality.atlassian.net/browse/MARXAN-1561)
> feat: add legacy project import piece requested saga and scheduler

- api/apps/api/src/modules/projects/dto/legacy-project-import.dto.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
This PR adds `/api/v1/projects/legacy-project-import/start` endpoint
[Add endpoint for starting a legacy project import](https://vizzuality.atlassian.net/browse/MARXAN-1592)
> feat: endpoint for starting legacy project imports

- .github/workflows/api-e2e-tests.yml
- Makefile
https://vizzuality.atlassian.net/browse/MARXAN-1599
> split api e2e from geoprocessing e2e tests [MARXAN-1599]

- api/apps/api/src/modules/legacy-project-import/application/add-file-to-legacy-project-import.handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/application/run-legacy-project-import.command.ts
- api/apps/api/src/modules/legacy-project-import/application/run-legacy-project-import.handler.spec.ts
- api/apps/api/src/modules/legacy-project-import/application/run-legacy-project-import.handler.ts
- api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
- api/apps/api/src/modules/projects/dto/legacy-project-import.dto.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
This PR adds an endpoint for running a legacy project import
[Add endpoint for running a legacy project import](https://vizzuality.atlassian.net/browse/MARXAN-1594)
> feat : add endpoint for running a legacy project import

- app/layout/admin/published-projects/table/cells/email/component.tsx
- app/layout/beta/component.tsx
- app/layout/header/component.tsx
- app/pages/index.tsx
[MARXAN-1607](https://vizzuality.atlassian.net/browse/MARXAN-1607)
> fix(front): fixed beta header

- app/hooks/solutions/index.ts
- app/layout/scenarios/edit/solutions/component.tsx
- app/layout/scenarios/edit/solutions/overview/component.tsx
- app/layout/scenarios/edit/solutions/overview/types.ts
- app/layout/sections/component.tsx
- app/layout/solutions/selected/component.tsx
This PR adds: 
- possibility to change the run on every solution section
> Solutions: new design

- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/projects/new/map/component.tsx
- app/layout/projects/show/header/toolbar/publish-btn/publish-modal/component.tsx
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/new/map/component.tsx
- app/layout/scenarios/reports/blm/map/component.tsx
- app/layout/scenarios/reports/frequency/map/component.tsx
- app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
- app/layout/scenarios/reports/solutions/selection-frequency-page/map/component.tsx
This PR adds aa BBOX hook that will convert the bbox to a valid one
> Maps: useBBOX hook

- app/components/gap-analysis/item/component.tsx
This PR adds visual styles for not met features target
> Features: not met target styles

- api/apps/api/src/migrations/api/1654005845323-AddInputPieceToLegacyProjectImportPieceEnum.ts
- api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
- api/apps/api/test/legacy-project-import/legacy-project-import.e2e-spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/file-readers.module.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/input-dat.reader.spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/input-dat.reader.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/input.legacy-piece-importer.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/legacy-piece-importers.module.ts
- api/apps/geoprocessing/src/modules/legacy-project-import-files-repository/geo-legacy-project-import-files-repository.module.ts
- api/apps/geoprocessing/src/modules/legacy-project-import-files-repository/index.ts
- api/apps/geoprocessing/test/integration/legacy-project-import/input.legacy-piece-importer.e2e-spec.ts
- api/libs/legacy-project-import/src/domain/legacy-project-import-piece.ts
- api/libs/utils/src/readable-to-buffer.ts
This PR adds input legacy project import piece and its piece importer
[Add a piece for importing input.dat file](https://vizzuality.atlassian.net/browse/MARXAN-1622)
> Feat/marxan 1622 add a piece for importing input.dat file

- api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1653650018540-AddAmountFromLegacyProjectToScenarioFeaturesData.ts
- api/libs/features/src/scenario-features-data.geo.entity.ts
- api/package.json
- Adds column to `scenarios_feature_data`.
- Changes how puvsprdat.service creates file.
> MARXAN-1610-amount_from_legacy_projects

- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features-specification.legacy-piece-importer.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/legacy-piece-importers.module.ts
- api/apps/geoprocessing/test/integration/legacy-project-import/features-specification.legacy-piece-importer.e2e-spec.ts
This PR fixes `FeaturesSpecificationLegacyProjectPieceImporter`
> fix: features specification legacy piece importer

- app/hooks/map/constants.tsx
> fix: change highlight features color [MARXAN-1313]

- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/input-dat.reader.spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/input-dat.reader.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/solutions.legacy-piece-importer.ts
- api/apps/geoprocessing/test/integration/legacy-project-import/input.legacy-piece-importer.e2e-spec.ts
This PR fixes an error in solutions legacy piece importer and in input-dat reader( was using wrong character for new lines)
> fix solutions legacy piece importer and input-dat reader

- app/pages/api/publish/[pid]/index.ts
https://vizzuality.atlassian.net/browse/MARXAN-1595
> avoid sending headers once response has been sent

- api/apps/api/src/migrations/api/1655731147185-AddCountryColumnUsers.ts
- api/apps/api/src/migrations/api/1655841236000-DropFeaturesToUsersFk.ts
- api/apps/api/src/modules/blm/values/repositories/scenario-calibration/typeorm-scenario-calibration-repository.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/asset-factory.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-1665
> explicitly select columns we need in response [MARXAN-1665]

- api/apps/api/src/modules/users/users.controller.ts
- api/apps/api/src/modules/users/users.service.ts
- api/apps/api/src/utils/csv.utils.ts
- api/apps/api/test/users.e2e-spec.ts
-Adds endpoint to download user data in CSV format.
-Adds tests for the endpoint.
> MARXAN-1647-download-user-data-csv

- api/apps/api/src/utils/csv.utils.ts
https://vizzuality.atlassian.net/browse/MARXAN-1672
> include display_name in CSVs with user data [MARXAN-1672]

- api/apps/geoprocessing/src/legacy-project-import/legacy-db-cleanup/legacy-db-cleanup.module.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-db-cleanup/legacy-db-cleanup.processor.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-db-cleanup/legacy-db-cleanup.worker.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-project-import.module.ts
This PR adds legacy db clean up worker and processor.
[Failed legacy project import cleanup](https://vizzuality.atlassian.net/browse/MARXAN-1641)
> add legacy db cleanup worker and processor

- infrastructure/kubernetes/modules/database/main.tf
- infrastructure/kubernetes/modules/database/values.yaml
> Update postgres helm chart

- api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
I <3 trial and error programming :P
> Avoid test timeout

- api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvspr.dat.legacy-project.ts
This PR fixes error detected in features filter in getLegacyAndMarxanFeatures method.
> fix: filter features in getLegacyAndMarxanFeatures method

- api/apps/api/src/modules/authentication/authentication.service.ts
- api/apps/api/src/modules/authentication/password-recovery/password-recovery.service.ts
- api/apps/api/src/modules/authentication/password-recovery/password-recovery.spec.ts
-Adds password validation when user changes their password.
> MARXAN-1484-changePassword-validation

- api/apps/api/config/custom-environment-variables.json
- api/apps/api/config/default.json
- api/apps/api/config/production.json
- api/apps/geoprocessing/config/custom-environment-variables.json
- api/apps/geoprocessing/config/default.json
- api/apps/geoprocessing/config/production.json
- api/apps/geoprocessing/src/ormconfig.ts
- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/modules/api/main.tf
- infrastructure/kubernetes/modules/api/variable.tf
https://vizzuality.atlassian.net/browse/MARXAN-1663
> make pg connection pooling configurable [MARXAN-1663]

- api/apps/api/src/app.module.ts
- api/apps/api/src/modules/authentication/authentication.controller.ts
- api/apps/api/src/modules/authentication/authentication.module.ts
- api/apps/api/src/modules/authentication/password-recovery/password-recovery.controller.ts
-Changes global guard for throttling limit for endpoint-specific guard
> MARXAN-1484-substitute-global-throttle-guard-for-specific-guard

- api/apps/api/src/app.module.ts
- api/apps/api/src/modules/export-cleanup/export-cleanup.service.ts
suggestion about moving some ops to sql
> identify expired resources+andrea hacks [MARXAN-1649]

- data/bots/lib/libbot/geo-feature-shapefiles.ts
- data/bots/lib/libbot/planning-area-shapefiles.ts
- data/bots/lib/libbot/util/http.ts
https://vizzuality.atlassian.net/browse/MARXAN-1709
> libbot: remove feature tags [MARXAN-1709]

- app/components/features/raw-item/component.tsx
- app/components/features/selected-item/component.tsx
- app/components/map/component.stories.tsx
- app/components/tag/component.stories.tsx
- app/hooks/features/index.ts
- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/scenarios/edit/features/set-up/add/add-modal/filters/component.tsx
- app/layout/scenarios/edit/features/set-up/add/add-modal/uploader/component.tsx
- app/layout/scenarios/edit/features/set-up/add/intersect/component.tsx
- app/layout/scenarios/edit/features/set-up/add/intersect/list/component.tsx
- app/layout/scenarios/edit/map/component.tsx
> feat(front): split unify feature layers

- api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts
- Do you know how many features Marxan has? This is to blame for this fix.
> GEO-CLEANUP-fix-wrong-features-table-apiDB

- data/data_download/world_terrestrial_ecosystems/Makefile
https://vizzuality.atlassian.net/browse/MARXAN-1698
> remove reference to features.tag column that was recently dropped [MARXAN-1698]

- api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts
-Adds table alias to avoid query errors.
> Fix-features-api-cleanup-query-error

- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/layout/scenarios/edit/solutions/overview/component.tsx
- app/utils/units.ts
Now solutions report has more readable title:
`project_${projectName}-scenario_${scenarioName}-run_${runId}.pdf`
[MARXAN-1426](https://vizzuality.atlassian.net/browse/MARXAN-1426)
> fix(front): change solutions-report pdf name[MARXAN-1426]

- app/layout/beta/component.tsx
- app/layout/community/component.tsx
- app/layout/footer/component.tsx
- app/layout/statics/contact/component.tsx
Added company contact email to an env var.
(Vercel is also already configured in all environments)
[MARXAN-1721](https://vizzuality.atlassian.net/browse/MARXAN-1721)
---
> fix(front): add company contact email to an env var [MARXAN-1721]

- api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
This PR fixes the calculation of `total_area` and `current_pa` made in split query service. The idea is to have the same logic in both, copy and split query services for these columns as they should be independent from the operation kind
[Strange gap analysis values with split features](https://vizzuality.atlassian.net/browse/MARXAN-1718)
> fix: split query service current_pa calculation

- app/layout/projects/all/list/component.tsx
- app/layout/projects/show/header/toolbar/publish-btn/publish-modal/component.tsx
[MARXAN-1695](https://vizzuality.atlassian.net/browse/MARXAN-1695)
[MARXAN-1724](https://vizzuality.atlassian.net/browse/MARXAN-1724)
> feat(front): projects dashboard + publish projects disclaimers [MARXAN-1695][MARXAN-1724]

- api/apps/api/src/migrations/api/1657544835000-RemoveFeatureTags.ts
- api/apps/api/src/modules/scenarios/delete-scenario/delete-scenario.handler.spec.ts
- api/apps/geoprocessing/src/import/pieces-importers/planning-units-grid.piece-importer.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/spec-dat.reader.spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/spec-dat.reader.ts
- api/apps/geoprocessing/src/ormconfig.ts
- api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
https://vizzuality.atlassian.net/browse/MARXAN-1733
> allow prop=0 in legacy spec.dat [MARXAN-1733]

- app/hooks/map/index.ts
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/edit/planning-unit/protected-areas/categories/component.tsx
- app/layout/scenarios/edit/planning-unit/protected-areas/component.tsx
[MARXAN-1727](https://vizzuality.atlassian.net/browse/MARXAN-1727)
> fix(front): enable save non protected areas[MARXAN-1727]

- api/apps/api/src/utils/file-uploads.utils.ts
https://vizzuality.atlassian.net/browse/MARXAN-1732
> lower maximum default file size for uploads to 10MB [MARXAN-1732]

- app/components/features/target-spf-item/component.tsx
- app/components/gap-analysis/item/component.tsx
> Features: name tooltip

- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/projects/dto/legacy-project-import.dto.ts
- api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.ts
- api/apps/api/src/modules/scenarios/input-files/puvspr.data.service.spec.ts
- api/apps/api/test/legacy-project-import/legacy-project-import.e2e-spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/puvspr-dat.reader.spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/spec-dat.reader.spec.ts
- api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-single/solutions-output/geo-output/scenario-features/scenario-features-data.service.ts
- api/apps/geoprocessing/test/integration/cloning/fixtures.ts
https://vizzuality.atlassian.net/browse/MARXAN-1683
> explicitly filter out geoprocessed features [MARXAN-1683]

- app/layout/header/component.tsx
Remove all references to beta for deploying to prod. 
**We MUST maintain it in marxan.vercel.app (`vercel-production` branch)**
> Beta: remove

- api/apps/api/src/modules/projects/projects.controller.ts
- api/libs/shapefile-converter/src/shapefiles/shapefiles.service.ts
https://github.com/Vizzuality/marxan-cloud/pull/new/chore/api/MARXAN-1731_allow-feature-shapefiles-with-overlapping-geometries
> allow overlaps of (gis) features in feature shapefiles [MARXAN-1731]

- api/apps/api/src/modules/geo-features/geo-features.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-1744
> avoid expensive spatial intersection over features that will never be relevant to the project [MARXAN-1744]

- api/apps/api/src/modules/scenarios-features/scenario-features-gap-data.service.ts
- api/apps/api/src/modules/scenarios-features/scenario-features-output-gap-data.service.ts
https://vizzuality.atlassian.net/browse/MARXAN-1745
> make search by feature name case insensitive (gap analysis, target achievements) [MARXAN-1745]

- app/layout/scenarios/edit/features/set-up/add/add-modal/uploader/component.tsx
- app/layout/sign-in/component.tsx
[MARXAN-1746](https://vizzuality.atlassian.net/browse/MARXAN-1746)
> upload features button: add info button to modal

- app/layout/scenarios/edit/features/set-up/add/add-modal/uploader/component.tsx
- app/layout/scenarios/edit/planning-unit/adjust-planning-units/buttons/uploading/component.tsx
- app/layout/scenarios/edit/planning-unit/protected-areas/categories/pa-uploader/component.tsx
[MARXAN-1512](https://vizzuality.atlassian.net/browse/MARXAN-1512)
> enhancement(front): add upload shapefiles extra info [MARXAN-1512]

- app/hooks/admin/index.ts
- app/layout/scenarios/edit/features/set-up/add/list/component.tsx
[MARXAN-1751](https://vizzuality.atlassian.net/browse/MARXAN-1751)
> enhancement(front): extra caution removing features [MARXAN-1751]

- app/layout/projects/new/map/component.tsx
- app/layout/projects/show/header/toolbar/publish-btn/publish-modal/component.tsx
- app/layout/projects/show/map/component.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/new/map/component.tsx
- app/layout/scenarios/reports/blm/map/component.tsx
- app/layout/scenarios/reports/frequency/map/component.tsx
- app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
- app/layout/scenarios/reports/solutions/selection-frequency-page/map/component.tsx
`transformRequest` from Mapbox only initializes when you create the Map. If you have outside params that you are using inside this function it won't update.
> Map: reload map if accessToken changes

- app/layout/projects/all/toolbar/upload-btn/legacy-upload-modal/upload-files/constants.ts
https://vizzuality.atlassian.net/browse/MARXAN-1762
> (chore) allow legacy puvspr.dat files up to 10MB [MARXAN-1762]

- .github/workflows/api-e2e-tests.yml
- .github/workflows/deploy-to-kubernetes.yml
- .github/workflows/publish-marxan-docker-images.yml
- .github/workflows/publish-webshot-docker-images.yml
- .github/workflows/webshot-build.yml
- docker-compose-test-e2e.ci.yml
- docker-compose-test-e2e.yml
- docker-compose-test-unit.yml
https://vizzuality.atlassian.net/browse/MARXAN-1770
> use latest ubuntu-22.04 images for gh actions runners [MARXAN-1770]

- api/apps/api/src/modules/projects/dto/create.project.dto.ts
https://vizzuality.atlassian.net/browse/MARXAN-1764
> narrow ability to accept nonsense [MARXAN-1764]

- app/utils/units.ts
https://vizzuality.atlassian.net/browse/MARXAN-1782
This PR adds:
```js
/**
* @param blm blm value
* @returns blm formatted value
*/
export const blmFormat = (blm: number): string => {
if (blm < 10) {
return format(',.3~f')(blm);
}
if (blm < 100) {
return format(',.2~f')(blm);
}
return format(',.0~f')(blm);
};
```
> BLM: improve formatting

- app/layout/scenarios/edit/features/set-up/add/add-modal/component.tsx
https://vizzuality.atlassian.net/browse/MARXAN-1778
> Features: fix bug that when you search it removes the other features

- app/layout/scenarios/edit/parameters/advanced-settings/component.tsx
https://vizzuality.atlassian.net/browse/MARXAN-1781
> Parameters: allow 0 as default value

- api/apps/api/src/main.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-features-specification.piece-importer.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.comma-or-tab-finder.ts
https://vizzuality.atlassian.net/browse/MARXAN-1780
https://vizzuality.atlassian.net/browse/MARXAN-1784
> Fix/api/marxan 1780+marxan 1784 fixes for legacy imports

- api/apps/api/src/decorators/file-interceptors.decorator.ts
- api/apps/api/src/modules/clone/infra/import/generate-export-from-zip-file.handler.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/utils/file-uploads.utils.ts
- api/apps/geoprocessing/src/import/pieces-importers/marxan-execution-metadata.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/planning-units-grid.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/project-puvspr-calculations.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-features-data.piece-importer.ts
- api/apps/geoprocessing/src/import/pieces-importers/scenario-run-results.piece-importer.ts
- api/apps/geoprocessing/test/integration/cloning/piece-importers/marxan-execution-metadata.piece-importer.e2e-spec.ts
https://vizzuality.atlassian.net/browse/MARXAN-1786
https://vizzuality.atlassian.net/browse/MARXAN-1787
> chunk saving in piece importers + raise size limits for Marxan Cloud archives for project imports

- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.reader.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/pu-dat.reader.ts
- api/libs/scenarios-planning-unit/src/scenarios-planning-unit.geo.entity.ts
- app/layout/forgot-password/component.tsx
https://vizzuality.atlassian.net/browse/MARXAN-1793
> accept Marxan lock status codes and map them to internal codes [MARXAN-1793]

- api/apps/api/src/modules/scenarios/input-files/input-files.module.ts
- api/apps/api/src/modules/scenarios/input-files/spec-dat-tsv-file.ts
- api/apps/api/src/modules/scenarios/input-files/spec.dat.service.ts
- api/apps/api/src/modules/scenarios/input-files/spec.data.service.spec.ts
- api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features-specification.legacy-piece-importer.ts
- api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/pu-dat.reader.ts
- api/apps/geoprocessing/test/integration/legacy-project-import/features-specification.legacy-piece-importer.e2e-spec.ts
https://vizzuality.atlassian.net/browse/MARXAN-1796
> include feature names in downloadable archives [MARXAN-1796]

- api/apps/geoprocessing/src/modules/surface-cost/adapters/typeorm-cost-surface.ts
https://vizzuality.atlassian.net/browse/MARXAN-1798
> apply rounding correctly to calculated area when calculating initial cost surface [MARXAN-1798]

- api/apps/api/src/modules/authentication/password-recovery/password-recovery.service.ts
- api/apps/api/src/modules/authentication/password-recovery/password-recovery.spec.ts
- api/apps/api/src/modules/authentication/password-recovery/user.service.ts
- api/apps/geoprocessing/src/modules/scenario-protected-area-calculation/scenario-protected-area-calculation-processor.ts
- app/layout/forgot-password/component.tsx
https://vizzuality.atlassian.net/browse/MARXAN-1811
https://vizzuality.atlassian.net/browse/MARXAN-1812
> only allow password resets for activated accounts [MARXAN-1811] [MARXAN-1812]

- .github/workflows/cypress.yml
- app/README.md
> updates documentation of NextAuth environmental variables

- api/apps/api/src/modules/geo-features/dto/update-feature-name.dto.ts
- api/apps/api/src/modules/geo-features/geo-features.module.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.module.ts
- api/apps/api/test/project/update-project-feature-name.e2e-spec.ts
Adds a new endpoint to allow update a feature name of a given project, with permission checks for editability.
---
> feat(Features): Allow updating Feature Name [MRXN23-26]

- api/apps/api/src/modules/access-control/projects-acl/project-access-control.ts
- api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
- api/apps/api/src/modules/geo-features/geo-features.module.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/scenarios-features/scenario-features.service.ts
- api/apps/api/test/project/delete-project-feature.e2e-spec.ts
> feat(Features): Adds Delete Feature for Project endpoint [MRXN23-24]

- api/apps/api/src/modules/analysis/providers/planning-units/update-planning-units.service.ts
- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
My suggestions would not fit in the margin of the original PR, so I created this branch instead with just a couple of commits with my suggestions.
> update scenario planning units inclusion processor+ar suggestions [MRXN23-78]

- docs/features/tagging/brief.md
- docs/features/tagging/high-level-design.md
> docs(Features): High Level design for Feature tagging

- api/apps/api/src/app.module.ts
- api/apps/api/src/migrations/api/1685458802957-AddFeatureTagTable.ts
- api/apps/api/src/modules/geo-feature-tags/geo-feature-tag.api.entity.ts
- api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.module.ts
- api/apps/api/test/project/delete-project-feature.e2e-spec.ts
- api/apps/api/test/project/update-project-feature-name.e2e-spec.ts
- api/package.json
- api/yarn.lock
- docs/features/tagging/high-level-design.md
> feat(Feature Tags): Adds Migration and Entity files for Geo Feature Tags

- api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.service.ts
- api/apps/api/src/modules/geo-features/geo-features.controller.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/test/geo-features/geo-feature-tags.acl.e2e-spec.ts
- api/apps/api/test/geo-features/geo-feature-tags.e2e-spec.ts
- api/apps/api/test/geo-features/geo-feature-tags.fixtures.ts
> feat(Feature Tags): Adds DELETE endpoint to untag features

- api/apps/api/src/modules/geo-feature-tags/dto/update-geo-feature-tag.dto.ts
- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/projects/dto/upload-shapefile.dto.ts
- api/apps/api/test/upload-feature/upload-feature.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature.fixtures.ts
> feat(Feature Tags): Extends the upload feature shapefile endpoint to accept tags

- api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.module.ts
- api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/projects/projects.service.ts
- api/apps/api/src/utils/acl.utils.ts
- api/apps/api/test/geo-features/geo-feature-tags.e2e-spec.ts
- api/apps/api/test/project/project-tags-acl.e2e-spec.ts
- api/apps/api/test/project/project-tags.e2e-spec.ts
- api/apps/api/test/project/project-tags.fixtures.ts
> feat(Project Tags): Adds DELETE endpoint to remove a tag from a project

- app/tailwind.config.js
Updates the files regex TailwindCSS should look into to get the classes.
---
> tailwindcss: updates content to parse

- api/apps/geoprocessing/src/export/pieces-exporters/project-custom-features.piece-exporter.ts
- api/apps/geoprocessing/src/import/pieces-importers/project-custom-features.piece-importer.ts
- api/apps/geoprocessing/test/integration/cloning/piece-exporters/project-custom-features.piece-exporter.e2e-spec.ts
- api/apps/geoprocessing/test/integration/cloning/piece-importers/project-custom-features.piece-importer.e2e-spec.ts
- api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-features.ts
> feat(Tags): Adds Tag property to Geo Feature piece exporter/importer

- app/pages/api/reports/scenarios/[sid]/blm.ts
- app/pages/api/reports/scenarios/[sid]/solutions.ts
https://vizzuality.atlassian.net/browse/MRXN23-161
---
> [MRXN23-161]: webshot fix

- app/pages/api/publish/[pid]/index.ts
This PR is an extension of https://github.com/Vizzuality/marxan-cloud/pull/1349, where we fix some issues with the token session when the requests are proxied by the internal API. In this case, it fixes the process of publishing a project.
–
Check the button _publish project_ works as expected.
https://vizzuality.atlassian.net/browse/MRXN23-161
---
> [MRXN23-161] fixes internal publish project endpoint

- api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
- api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
- In ScenarioPlanningUnitsInclusionProcessor - If there are overlaps between opposing claims byId (of each specific kind) and byGeoJSON (of all the kinds at once), claims by Ids will be ignored.
- Minor refactor of ScenarioPlanningUnitsInclusionProcessor
- New test for the case
---
> [MRXN23-213] Allow overlaps of contrasting claims from Ids and from GeoJson 

- docs/README_implementation-conventions-for-API-tasks.md
This is my attempt at consolidating various rants and advice discussed while onboarding new backend engineers to the project.
It should cove most of what is important to know and take into account in terms of implementation, sticking to conventions that emerged through the lifetime of the first phase of this project, and acknowledging that there will be lots of divergent implementations especially for earlier code.
I haven't tried to synthesize everything everywhere all at once: I wanted this to be a good entrypoint and checklist for new and seasoned developers alike, to avoid having to keep in mind a lot of details that should really be a checklist, freeing up our neurons for higher value-added work.
https://vizzuality.atlassian.net/browse/MRXN23-202
> documentation: Implementation conventions for typical API tasks [MRXN23-202]

- app/hooks/scenarios/index.ts
- app/layout/project/navigation/index.tsx
- app/layout/scenarios/edit/status/component.tsx
- app/layout/scenarios/edit/status/utils.tsx
- app/types/job.ts
- app/types/scenario.ts
[Figma](https://www.figma.com/file/0xD4gR9pCqU7NROnlSW6ck/Marxan-Layout---Redesign?node-id=521%3A58009&mode=dev)
- It should not appear if at least we have not selected a feature.
- Once the scenario is running, the button will disappear until the run is over and it will become visible again.
[MRXN23-236](https://vizzuality.atlassian.net/browse/MRXN23-236)
[MRXN23-236]: https://vizzuality.atlassian.net/browse/MRXN23-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (feat): run scenario

- app/layout/project/sidebar/project/inventory-panel/cost-surface/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/index.tsx
- app/layout/project/sidebar/project/inventory-panel/protected-areas/index.tsx
- app/pages/projects/[pid]/index.tsx
> basic organisation for sidebar content

- app/hooks/projects/index.ts
- app/hooks/scenarios/index.ts
- app/hooks/solutions/index.ts
- app/layout/admin/users/table/component.tsx
- app/layout/scenarios/edit/solutions/overview/component.tsx
- app/layout/scenarios/edit/solutions/overview/types.ts
- app/layout/scenarios/edit/status/utils.tsx
- app/utils/download.ts
[Prototype](https://www.figma.com/proto/0xD4gR9pCqU7NROnlSW6ck/Marxan-Layout---Redesign?type=design&node-id=1164-22557&t=pjVI4O604lLLtc6b-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=147%3A6605&show-proto-sidebar=1)
Run a scenario and then try to export solutions. You should obtain a zip folder with summed and best solutions.
[MRXN23-224](https://vizzuality.atlassian.net/browse/MRXN23-224)
[MRXN23-224]: https://vizzuality.atlassian.net/browse/MRXN23-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MRXN23-224]: (feat) download best and summed solutions summary

- app/hooks/features/index.ts
- app/layout/project/sidebar/project/inventory-panel/features/bulk-action-menu/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/bulk-action-menu/utils.ts
- app/layout/project/sidebar/project/inventory-panel/features/list/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/list/item/actions/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/list/item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/delete/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/edit-type/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/edit/index.tsx
- app/types/feature.ts
- app/types/project-model.ts
This PR updates the PATCH feature endpoint from `PATCH /api/v1/projects/:projectId/features/:featureId` to `PATCH /api/v1/geo-features/:featureId`.
It also updates the `ProjectFeature` type as it does not make any sense: there is a single `Feature` entity handled at project and scenario levels. And, finally, updates the name of some functions to reflect what they really do.
–
–
---
> [MRXN23-238]: updates PATCH feature endpoint

- app/layout/project/sidebar/project/inventory-panel/features/list/item/actions/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/list/item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/delete/index.tsx
Makes sure only custom features (`isCustom: true`) and without any scenario associated (`scenarioUsageCount === 0`) are deletable. If a non-custom (platform-wide) feature is selected to be deleted through the bulk menu, it will be filtered automatically as the API will reject its deletion no matter what.
---
> makes only custom feature removable

- api/apps/api/src/migrations/api/1690477596000-MakeProjectIdPrimaryKeyForOutputProjectSummaries.ts
- api/apps/api/src/modules/projects/output-project-summaries/output-project-summaries.service.ts
- api/apps/api/src/modules/projects/output-project-summaries/output-project-summary.api.entity.ts
- api/apps/api/test/project/output-project-summaries.e2e-spec.ts
Executing Marxan multiple times (same or different scenarios) within a project should now work without errors.
https://vizzuality.atlassian.net/browse/MRXN23-260
---
> [api] fix: upsert output project summaries correctly [MRXN23-260]

- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/test/geo-features/update-project-feature-name.e2e-spec.ts
> [MRXN23-257] fix(GeoFeatures): Allows updating feature with same name

- infrastructure/base/versions.tf
- infrastructure/kubernetes/main.tf
- infrastructure/kubernetes/modules/api/versions.tf
- infrastructure/kubernetes/modules/backup/versions.tf
- infrastructure/kubernetes/modules/cert_manager/main.tf
- infrastructure/kubernetes/modules/cert_manager/versions.tf
- infrastructure/kubernetes/modules/client/versions.tf
- infrastructure/kubernetes/modules/cloud_secrets/versions.tf
- infrastructure/kubernetes/modules/database/versions.tf
- infrastructure/kubernetes/modules/email-templates/versions.tf
- infrastructure/kubernetes/modules/geoprocessing/versions.tf
- infrastructure/kubernetes/modules/ingress/versions.tf
- infrastructure/kubernetes/modules/k8s_namespaces/versions.tf
- infrastructure/kubernetes/modules/kubernetes_secrets/versions.tf
- infrastructure/kubernetes/modules/storage/versions.tf
- infrastructure/kubernetes/modules/volumes/versions.tf
- infrastructure/kubernetes/modules/webshot/versions.tf
- infrastructure/kubernetes/versions.tf
- infrastructure/remote-state/main.tf
because I can't be bothered to downgrade my local binary 😬
> require latest terraform

- app/hooks/features/index.ts
- app/layout/project/sidebar/project/inventory-panel/features/modals/edit-bulk/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/edit/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
A user should be able to tag a feature uploaded via shapefile.
[Figma design](https://www.figma.com/file/0xD4gR9pCqU7NROnlSW6ck/Marxan-Layout---Redesign?node-id=568%3A40525&mode=dev)
Go to inventory panel features and try to upload a feature tagging it, by choosing and existing tag or creating a new one: https://marxan-git-mrxn23-285-tag-uploaded-feature-vizzuality1.vercel.app/projects/4e4fab36-354f-4e2e-8cd4-1d3d3def6bf9?tab=features
[Here are some features](https://github.com/marxan-cloud/tnc-training-bots/tree/main/2021-12_rwanda/features) you can download to test in Rwanda project we have in dashboard.
[MRXN23-285](https://vizzuality.atlassian.net/browse/MRXN23-285)
[MRXN23-285]: https://vizzuality.atlassian.net/browse/MRXN23-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> FE (feat): tag uploaded feature [MRXN23 285] 

- app/hoc/scenarios.ts
- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/layout/header/title/component.tsx
- app/layout/project/navigation/constants.ts
- app/layout/project/navigation/hooks.tsx
- app/layout/project/navigation/index.tsx
- app/layout/project/navigation/submenu/index.tsx
- app/layout/project/sidebar/project/scenarios-list/index.tsx
- app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/results/component.tsx
- app/layout/projects/show/scenarios/component.tsx
- app/layout/scenarios/new/name/index.tsx
- app/layout/sidebar/submenu/index.tsx
[MRXN23-321](https://vizzuality.atlassian.net/browse/MRXN23-321)
[MRXN23-321]: https://vizzuality.atlassian.net/browse/MRXN23-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [fe]: Disable solutions when scenario have not ran an scenario [MRXN23-321]

- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
[MRXN23-317](https://vizzuality.atlassian.net/browse/MRXN23-317)
[MRXN23-317]: https://vizzuality.atlassian.net/browse/MRXN23-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [fe] (fix): Remove actions menu and checkbox from non custom features [MRXN23-317]

- app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/uploader/component.tsx
This PR fixes an issue where after uploading a feature via shapefile (from a scenario), the feature list in the modal was not updated with the new feature.
- Go to `/projects/{id}/scenarios/{id}/edit?tab=features`, and click on `Add features` button,
- In the modal, click on `Upload your own features` button and upload a shapefile.
- When the shapefile is uploaded correctly, the list of features should reflect the new feature automatically.
https://vizzuality.atlassian.net/browse/MRXN23-409
---
> [MRXN23-409]: updates list of features correctly after uploading shapefile

- api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/test/geo-features/geo-feature-tags.e2e-spec.ts
Update ` PATCH :projectId/features/:featureId/tags` to return updated feature
---
> [api] update geo feature tag patch endpoint to return updated feature [MRXN23-259]

- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
- api/apps/api/src/modules/protected-areas/dto/rename.protected-area.dto.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.module.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
- api/apps/api/src/modules/protected-areas/protected-areas.controller.ts
- api/apps/api/src/modules/scenarios/scenarios.controller.ts
- api/apps/api/src/utils/acl.utils.ts
- api/apps/api/test/protected-areas/delete-protected-area.e2e-spec.ts
- api/apps/api/test/protected-areas/protected-areas.acl.e2e-spec.ts
- api/apps/api/test/protected-areas/protected-areas.fixtures.ts
- api/apps/api/test/protected-areas/update-protected-area-name.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature-csv.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature.fixtures.ts
Patch and Delete endpoints for protected-areas module.
Integration tests
---
> [api] Add endpoint to rename and delete custom protected area [MRXN23-269] [MRXN23-270]

- app/components/forms/label/component.tsx
`classnames` messing it up 🤷🏻‍♂️ 
- Go to `/projects/{pid}/scenarios/{sid}/edit?tab=solutions`, and click on `View solutions table` button,
- In the table, the sentence `View 5 most different solutions` should be visible again.
https://vizzuality.atlassian.net/browse/MRXN23-425
---
> [MRXN23-425]: fixes wrong class in text

- api/apps/api/src/modules/projects/project-protected-areas.service.ts
- api/apps/api/src/modules/projects/projects.controller.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.module.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
- api/apps/api/test/scenario-protected-areas/fixtures.ts
- api/libs/protected-areas/src/protected-areas.geo.entity.ts
Update the endpoint to return global protected areas as well, add new property 'kind' to attributes to distinguish global PAs from custom project ones.
---
> [api] Update project protected areas endpoint to include global areas [MRXN23-411]

- api/apps/geoprocessing/src/modules/features/features.service.ts
- api/apps/geoprocessing/test/index.html
preview tiles for amounts ready.  
For FE implementation, there is a property called ammount_value that serves the amount number.
> dev preview of toles for feature amounts per PU [MRXN23-203]; tweak tolerance for st_repeatedpoints dynamically [MRXN23-281]

- api/apps/api/src/modules/cost-surface/cost-surface.service.ts
- api/apps/api/src/modules/cost-surface/dto/update-cost-surface.dto.ts
- api/apps/api/src/modules/cost-surface/dto/upload-cost-surface-shapefile.dto.ts
- api/apps/api/src/modules/projects/project-cost-surface.controller.ts
- api/apps/api/src/utils/acl.utils.ts
- api/apps/api/test/project/project-cost-surface.controller.acl.e2e-spec.ts
- api/apps/api/test/project/project-cost-surface.controller.e2e-spec.ts
- api/apps/api/test/project/project-cost-surface.controller.fixtures.ts
For now, only the name is updated
---
> feat(CostSurface): Adds new endpoint to update a Cost Surface [MRXN23-29]

- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/header-item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
- app/package.json
- app/yarn.lock
> [N/A] removes lucide-react

- api/apps/api/src/modules/projects/project-protected-areas.controller.ts
- api/apps/api/src/modules/projects/project-protected-areas.service.ts
- api/apps/api/src/modules/protected-areas/dto/protected-areas-request-info.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.module.ts
- api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
- api/apps/api/test/scenario-protected-areas/fixtures.ts
- api/apps/api/test/scenario-protected-areas/list-project-protected-ares.e2e-spec.ts
Implements nestjs base service filter and other tools, adds search option following the logic of features endpoints.
Tests for new use cases.
---
> [api] implements search and filter for GET project protected areas endpoint [MRXN23-428]

- app/components/map/component.stories.tsx
- app/components/map/component.tsx
- app/components/map/controls/component.tsx
- app/layout/project/sidebar/constants.ts
- app/layout/project/sidebar/index.tsx
- app/layout/projects/new/map/component.tsx
- app/layout/projects/show/map/index.tsx
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/new/map/component.tsx
- app/package.json
- app/types/map.d.ts
- app/utils/map.ts
- app/yarn.lock
Test that the map is centered on the 4 maps that converge with the sidebar. These are:
[MRXN23-449](https://vizzuality.atlassian.net/browse/MRXN23-449)
[MRXN23-449]: https://vizzuality.atlassian.net/browse/MRXN23-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE(fix): center map related sidebar [MRXN23-449] 

- app/hooks/wdpa/index.ts
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/modals/delete/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/modals/edit/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
- app/types/api/wdpa.ts
Go to Inventory Panel and test if you can search by protected area name and order by name in both directions.
[MRXN23-239](https://vizzuality.atlassian.net/browse/MRXN23-239)
[MRXN23-239]: https://vizzuality.atlassian.net/browse/MRXN23-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE (feat): Inventory Protected Areas params [MRXN23-239]

- app/layout/project/navigation/index.tsx
For some reason, we were not tracking run scenario anymore. This PR re-include it.
> FE: recover run scenario goal

- api/apps/api/src/modules/scenarios/protected-area/getter/selection-get.service.ts
- api/apps/api/test/scenario-protected-areas/fixtures.ts
- api/apps/api/test/scenario-protected-areas/list-project-protected-ares.e2e-spec.ts
Changes requested in https://vizzuality.atlassian.net/browse/MRXN23-461
---
> [api] Update wdpa names in protected areas list endpoint [MRXN23-461]

- app/layout/project/sidebar/header/title/index.tsx
- app/layout/project/sidebar/project/scenarios-list/index.tsx
- app/layout/projects/show/scenarios/component.tsx
Improved overall styling for title edition:
- better space management
- updated button styles according to UI kit.
–
---
> [N/A]: improves styling of title edition

- api/apps/api/src/modules/scenarios/protected-area/getter/selection-get.service.ts
- api/apps/geoprocessing/src/migrations/geoprocessing/1696234928674-CreateDanglingCostSurfaces.ts
- api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts
- api/apps/geoprocessing/test/integration/cost-surface/cleanup.fixtures.ts
- api/apps/geoprocessing/test/integration/cost-surface/cost-surface-cleanup.e2e-spec.ts
Adds Cost Surfaces clean up to CleanupTasksService and new table for dangling Cost Surfaces
---
> [api] Add dangling cost surfaces garbage collector [MRXN23-119]

- app/layout/projects/new/form/component.tsx
> disables save button while project creation

- app/components/confirmation-prompt/component.tsx
- app/hooks/map/index.ts
- app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
- app/layout/projects/show/map/legend/hooks/index.ts
> syncs protected areas visibility

- app/components/modal/component.tsx
- app/layout/projects/new/form/component.tsx
- app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
https://vizzuality.atlassian.net/browse/MRXN23-484
---
> [MRXN23-484]: notifies user about project creation ongoing

- api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
- api/apps/api/test/upload-feature/upload-feature-csv.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature.fixtures.ts
> Undoes hack of setting legacy_import to project for puvspr shapefile uploads [MRXN23-247]

- app/hooks/scenarios/index.ts
- app/layout/project/sidebar/project/inventory-panel/cost-surfaces/bulk-action-menu/utils.ts
- app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/cost-surface/index.tsx
- app/layout/projects/show/map/legend/hooks/index.ts
- app/layout/scenarios/edit/map/component.tsx
- app/store/slices/projects/[id].ts
- app/types/api/scenario.ts
https://vizzuality.atlassian.net/browse/MRXN23-489
---
> [MRXN23-489]: link cost surface to scenario

- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/hooks/map/types.ts
- app/layout/projects/show/map/index.tsx
- app/layout/projects/show/map/legend/hooks/index.ts
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/edit/map/legend/hooks/index.ts
https://vizzuality.atlassian.net/browse/MRXN23-435
---
> [MRXN23-435]: abundance feature layer

- api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
> Removes unnecessary code on listForProject method that would fail on deletions [MRXN23-490]

- app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-492
---
> [MRXN23-492]: fixes cost surfaces sorting

- api/apps/api/src/modules/projects/output-project-summaries/output-project-summaries.service.ts
- api/apps/api/test/projects/project-summaries/output-project-summaries.e2e-spec.ts
> fix(OutputSummary): Fixes bug generating output summary with not correct run at least once criteria [MRXN-474]

- app/hooks/cost-surface/index.ts
- app/hooks/features/index.ts
- app/hooks/gap-analysis/index.ts
- app/hooks/scenarios/index.ts
- app/hooks/wdpa/index.ts
- app/layout/projects/show/map/legend/hooks/index.ts
- app/layout/scenarios/edit/map/legend/hooks/index.ts
Disables default pagination (25 per page) for lists.
---
> [N/A]: disables pagination for most of lists

- app/hooks/features/index.ts
- app/hooks/features/types.ts
- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/layout/project/sidebar/project/inventory-panel/features/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/add/list/component.tsx
- app/layout/projects/show/map/index.tsx
- app/layout/projects/show/map/legend/hooks/index.ts
- app/layout/scenarios/edit/map/component.tsx
- app/layout/scenarios/edit/map/legend/hooks/index.ts
- app/store/slices/projects/[id].ts
- app/store/slices/scenarios/edit.ts
> [N/A]: fixes continuous feature layers

- api/apps/api/src/modules/geo-features/geo-features.service.ts
- api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
- api/apps/api/src/modules/scenarios-features/compute-area.service.spec.ts
- api/apps/api/src/modules/scenarios-features/compute-area.service.ts
- api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
> feature(FeatureAmounts): Adds setting min/max on ComputeArea service for shapefiles too [MRXN23-494]

- app/hooks/features/index.ts
- app/hooks/scenarios/index.ts
- app/layout/scenarios/reports/solutions/advanced-settings/index.tsx
- app/layout/scenarios/reports/solutions/cost-surface/index.tsx
- app/layout/scenarios/reports/solutions/cost-surface/map/index.tsx
- app/layout/scenarios/reports/solutions/webshot-status/index.tsx
- app/types/api/cost-surface.ts
This PR fixes an issue fetching features to elaborate the solutions report.
https://vizzuality.atlassian.net/browse/MRXN23-502
---
> [MRXN23-502]: fixes timeout in webshooting solutions report

- app/layout/scenarios/edit/map/legend/hooks/index.ts
https://vizzuality.atlassian.net/browse/MRXN23-495
---
> [MRXN23-495]: filters features in scenario legend based on saved features in sidebar

- app/hooks/wdpa/index.ts
- app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
- app/layout/projects/show/map/index.tsx
- app/layout/projects/show/map/legend/hooks/index.ts
- app/layout/scenarios/edit/map/legend/hooks/index.ts
https://vizzuality.atlassian.net/browse/MRXN23-501
---
> [MRXN23-501]: delays cache invalidation of WDPAs

- app/layout/project/sidebar/project/inventory-panel/features/index.tsx
- app/layout/project/sidebar/project/inventory-panel/features/modals/delete/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-507
---
> [MRXN23-507]: excludes platform-wide features from selected counter and bulk operation

- app/layout/project/sidebar/project/scenarios-list/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-508
---
> [MRXN23-508]: invalidates features cache after deleting scenario

- app/layout/toast/component.tsx
https://vizzuality.atlassian.net/browse/MRXN23-509
---
> [MRXN23-509]: fixes glitch with toast visibility when a modal is visible

- app/components/button/component.tsx
- app/components/features/raw-item/component.tsx
- app/components/forms/select/constants/theme.ts
- app/layout/project/sidebar/project/scenarios-list/index.tsx
- app/layout/projects/show/map/index.tsx
- app/layout/scenarios/edit/map/component.tsx
https://vizzuality.atlassian.net/browse/MRXN23-510
https://vizzuality.atlassian.net/browse/MRXN23-517
---
> [MRXN23-510/517]: adjusts button styles

- app/layout/project/sidebar/scenario/grid-setup/protected-areas/threshold/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-514
---
> [MRXN23-514]: stays in scenario/protected-areas after applying changes

- app/hooks/cost-surface/index.ts
- app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
- app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
> [MRXN23-512]: hides floating menu after deletion process

- app/hooks/map/constants.tsx
- app/hooks/map/index.ts
- app/layout/project/sidebar/scenario/grid-setup/gap-analysis/list/index.tsx
- app/layout/scenarios/edit/map/legend/hooks/index.ts
https://vizzuality.atlassian.net/browse/MRXN23-515
https://vizzuality.atlassian.net/browse/MRXN23-516
---
> [MRXN23-515/516]: fixes management of gap-analysis features

- app/layout/project/sidebar/project/scenarios-list/types/index.tsx
- app/layout/projects/all/toolbar/upload-btn/component.tsx
- app/layout/projects/show/scenarios/types/component.tsx
https://vizzuality.atlassian.net/browse/MRXN23-526
---
> [MRXN23-526]: minor visual regression in scenario type modal

- app/layout/project/sidebar/project/inventory-panel/cost-surfaces/modals/upload/index.tsx
- app/layout/projects/show/status/actions/done.tsx
- app/layout/projects/show/status/component.tsx
- app/layout/projects/show/status/utils.tsx
https://vizzuality.atlassian.net/browse/MRXN23-524
---
> [MRXN23-524]: waits for API to refetch cost surfaces

- api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.handler.ts
- api/apps/api/test/projects/crud/projects.e2e-spec.ts
- api/apps/api/test/projects/projects.fixtures.ts
- api/apps/geoprocessing/test/integration/cloning/fixtures.ts
https://vizzuality.atlassian.net/browse/MRXNM-31
> avoid relinking planning areas already used for a project [MRXNM-31]

- app/README.md
- app/components/features/selected-item/component.tsx
- app/components/upload-tabs/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-537
---
> [MRXN23-537] enables permanently feature splitting and CSV upload

- app/components/map/legend/item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
[MRXN23-539](https://vizzuality.atlassian.net/browse/MRXN23-539)
[MRXN23-539]: https://vizzuality.atlassian.net/browse/MRXN23-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE](fix): tiny styles[MRXN23-539]

- api/apps/geoprocessing/src/export/pieces-exporters/project-feature-amounts-per-planning-unit.piece-exporter.ts
- api/apps/geoprocessing/test/integration/cloning/piece-exporters/project-feature-amounts-per-planning-unit.piece-exporter.e2e-spec.ts
> [MRXN23-518] Workaround for exporting Feature Amounts when a feature has been previously deleted

- app/layout/project/sidebar/scenario/grid-setup/features/add/list/component.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx
- app/layout/project/sidebar/scenario/grid-setup/protected-areas/threshold/index.tsx
[MRXN23-547](https://vizzuality.atlassian.net/browse/MRXN23-547)
[MRXN23-551](https://vizzuality.atlassian.net/browse/MRXN23-551)
[MRXN23-547]: https://vizzuality.atlassian.net/browse/MRXN23-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MRXN23-551]: https://vizzuality.atlassian.net/browse/MRXN23-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE](fix): [MRXN23-551][MRXN23-547]

- app/hooks/map/constants.tsx
[MRXN23-549](https://vizzuality.atlassian.net/browse/MRXN23-549)
[MRXN23-549]: https://vizzuality.atlassian.net/browse/MRXN23-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE(fix): remove frequency NaNs [MRXN23-549]

- app/layout/project/sidebar/project/scenarios-list/index.tsx
[MRXN23-554](https://vizzuality.atlassian.net/browse/MRXN23-554)
[MRXN23-554]: https://vizzuality.atlassian.net/browse/MRXN23-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE(fix): add scroll to create first sceanrio dashboard[MRXN23-554]

- app/layout/help/tooltip/component.tsx
[MRXN23-553](https://vizzuality.atlassian.net/browse/MRXN23-553)
[MRXN23-553]: https://vizzuality.atlassian.net/browse/MRXN23-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE(fix): change color text on help tooltip content [MRXN23-553]

- app/README.md
- app/components/features/selected-item/component.tsx
Hides splitting feature behind `split` feature flag.
https://vizzuality.atlassian.net/browse/MRXN23-564
---
> [MRXN23-564] restores split feature flag

- app/layout/project/index.tsx
- app/layout/projects/new/form/component.tsx
- app/layout/projects/new/form/constants.ts
https://vizzuality.atlassian.net/browse/MRXN23-565
---
> [MRXN23-565] fixes project creation after swapping way to set location

- app/layout/projects/show/status/actions/failure.tsx
- app/layout/projects/show/status/component.tsx
- app/layout/projects/show/status/utils.tsx
- app/types/api/project.ts
Fixes error condition when clicking on _close_ button after a process failed wouldn't do anything. Not it should close.
https://vizzuality.atlassian.net/browse/MRXN23-538
---
> [MRXN23-538] fixes error callbacks condition for project statuses

- app/docs/roadmap.md
- app/hooks/scenarios/index.ts
- app/hooks/scenarios/types.ts
- app/hooks/wdpa/index.ts
- app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/pa-uploader/index.tsx
- app/layout/projects/show/status/constants.ts
- app/layout/scenarios/edit/status/constants.ts
Removes WDPA upload endpoint associated to scenario route.
This PR unblocks https://github.com/Vizzuality/marxan-cloud/pull/1577
https://vizzuality.atlassian.net/browse/MRXN23-506
---
> [MRXN23-506]: removes WDPA upload endpoint associated to scenario

- api/apps/api/src/modules/geo-feature-tags/dto/update-geo-feature-tag.dto.ts
- api/apps/api/src/modules/projects/dto/update-project-tag.dto.ts
- api/apps/api/src/modules/projects/dto/upload-shapefile.dto.ts
- api/apps/api/test/geo-features/geo-feature-tags.e2e-spec.ts
- api/apps/api/test/projects/project-feature-tags/project-tags.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature.e2e-spec.ts
> fix(tags): Tags are now trimmed down of white spaces before updating them [MRXN23-567]

- app/layout/project/sidebar/header/title/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/types.ts
- app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
- app/layout/project/sidebar/project/inventory-panel/features/index.tsx
- app/layout/project/sidebar/project/inventory-panel/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/target-spf/targets-spf-table/row-item/index.tsx
Allows the user to filter features by tag as we already do in the scenario.
https://vizzuality.atlassian.net/browse/MRXN23-566
---
> [MRXN23-566] inventory panel: allows filtering features by tag

- api/apps/api/src/modules/cost-surface/cost-surface.service.ts
- api/apps/api/test/projects/cost-surfaces/project-cost-surface.fixtures.ts
- data/scripts/cost-surface/cost-surface-data-migration.py
> [MRXN23-568] Changes name of default Cost Surface to be more descriptive

- app/layout/upcoming-changes/index.ts
- app/layout/upcoming-changes/index.tsx
Updates text of _upcoming changes_ banner.
–
---
> [N/A] updates text of upcoming changes banner

- app/layout/project/navigation/user-menu/index.tsx
Adds admin panel link to user menu.
–
---
> [N/A] adds admin panel link to user menu

- app/hooks/features/index.ts
- app/hooks/gap-analysis/index.ts
- app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/modals/edit/index.tsx
- app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx
- app/layout/scenarios/edit/status/actions/done.tsx
Adds edition of Target/SPF for custom selections.
https://vizzuality.atlassian.net/browse/MRXN23-566
---
> [MRXN23-566]: allows editing target/spf of custom selection

- app/hooks/wdpa/index.ts
- app/layout/scenarios/reports/solutions/resume/index.tsx
Displays the list of WDPAs applied in the scenario, not the whole list.
https://vizzuality.atlassian.net/browse/MRXN23-573
---
> [MRXN23-573] solutions report: displays only selected WDPA in scenario

- app/hooks/map/index.ts
This PR solves an issue where WDPA filters weren't applied correctly in the WDPA Preview layer.
https://vizzuality.atlassian.net/browse/MRXN23-579
---
> [MRXN23-579] applies correctly filter WDPA filter to WDPA Preview layer

- app/layout/project/sidebar/scenario/solutions/overview/table/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-570
---
> [MRXN23-570] solutions table: updates color of button

- app/components/features/raw-item/component.tsx
https://vizzuality.atlassian.net/browse/MRXN23-542
---
> grid setup features: updates text of button

- app/layout/project/sidebar/project/scenarios-list/index.tsx
https://vizzuality.atlassian.net/browse/MRXN23-615
---
> [MRXN23-615] updates text of export scenario

- app/components/features/raw-item/component.tsx
- app/layout/project/sidebar/project/scenarios-list/index.tsx
- app/yarn.lock
> production deployment

- app/components/features/raw-item/component.tsx
- app/layout/project/sidebar/project/scenarios-list/index.tsx
- app/yarn.lock
> deploy staging

- .github/workflows/deploy-to-kubernetes.yml
- .github/workflows/publish-marxan-docker-images.yml
- .github/workflows/publish-webshot-docker-images.yml
PEBKAC in my previous PR for this (#1669), apologies 😬
> fix: use vars.blah, not env.blah 🤦 [MRXNM-39]

- api/apps/api/src/migrations/api/1713199859318-RefactorFeatureImportApiEventKinds.ts
- api/apps/api/src/modules/geo-features/adapters/feature-shapefile-upload-api-events.ts
- api/apps/api/src/modules/geo-features/import/feature-csv-import.events.ts
- api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
- api/apps/api/src/modules/projects/job-status/project-status.view.api.entity.ts
- api/apps/api/test/upload-feature/upload-feature-csv.e2e-spec.ts
- api/apps/api/test/upload-feature/upload-feature.fixtures.ts
- api/libs/api-events/src/api-event-kinds.enum.ts
- app/hooks/features/index.ts
- app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
- app/layout/projects/show/status/actions/done.tsx
- app/layout/projects/show/status/component.tsx
- app/types/api/project.ts
This PR adds callbacks for CSV/shapefile feature importation as well as refactoring the feature upload related api_event_kinds. This will allow to block the UI with the splash screen while importation is ongoing.
https://vizzuality.atlassian.net/browse/MRXN23-617
https://vizzuality.atlassian.net/browse/MRXN23-623
---
> [MRXN23-617/MRXN23-622/MRXN23-623] adds callbacks for CSV/Shapefile feature import

- .github/workflows/deploy-to-kubernetes.yml
- .github/workflows/publish-marxan-docker-images.yml
- .github/workflows/publish-webshot-docker-images.yml
No warnings about out of date actions and Node engines used in actions should be shown when actions run in GH
https://vizzuality.atlassian.net/browse/MRXNM-54
---
> update GH Actions to latest versions [MRXNM-54]

- infrastructure/CHANGELOG.md
- infrastructure/kubernetes/modules/cert_manager/main.tf
https://vizzuality.atlassian.net/browse/MRXNM-53
---
> use latest v1.12.x cert-manager Helm chart [MRXNM-53]

- .github/workflows/e2e-client.yml
- app/package.json
- app/yarn.lock
> [N/A] bumps next@13.5.11
