app/components/modal/component.stories.tsx
app/components/modal/component.tsx
app/components/modal/index.ts
app/package.json
app/styles/tailwind.css
app/yarn.lock

This PR adds a modal component to the project and Storybook.
<p align="center">
</p>
Multiple example of modals can be found in [Figma](https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=1523%3A8942).
Each of the modals of the visuals has a different size so I categorised them into 3 categories: narrow (e.g. prompts), default and wide (e.g. modals with a table inside).
Due to the limits of Tailwind, I've tried my best to keep the design's average sizes (~400px, ~520px and ~800px) as stable as possible for all screen sizes. Though, because the modal's size is a percentage of the viewport, the modal's size around the breakpoints differs vastly. If your screen is 1280px wide, that's when you'll see the modal closer to it's target size.
In Figma, the overlay is also …

Add a modal component

---

app/components/forms/component.stories.tsx
app/components/forms/label/component.tsx
app/components/forms/slider/component.stories.tsx
app/components/forms/slider/component.tsx
app/components/forms/slider/index.ts
app/components/forms/slider/thumb/component.tsx
app/components/forms/slider/thumb/index.ts
app/package.json
app/styles/tailwind.css
app/yarn.lock

This PR adds a new Slider component that is to be used inside of forms.
<p align="center">
</p>
In the provided Storybook story, you can see the minimum requirements (props) that are necessary. In summary, the 3 essential pieces are:
- An external `<label />` that must have a `for` attribute (or `htmlFor` prop) and is saved in a React ref
- An `id` prop passed to `<Slider />` that has the same value as the label's `for` attribute
- A `labelRef` prop passed to `<Slider />` that is the ref to the `<label />` element
The slider can be found in the [Figma project](https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=1523%3A2317), on the artboard Marxan 07a.
The component is available in the Storybook both in Forms / Slider / Default and Forms / Form where you can see it …

Slider component

---

Makefile
docker-compose.yml
env.default

Update docker-compose configuration, restoring what we had commented out.
Services that are not needed now will not start anymore if we use `make start-api`.
`make start` will attempt to spin up all the services, though the `app` one is not fully configured yet, so this target should not be used for now.
Additionally, it's now trivial to enter a `psql` console both for the API db (`make psql-api`) and for the geoprocessing db (`make psql-geo`).
N/A
Stop all the Marxan services (`make stop`).
`make start-api` should start api and geoprocessing services, plus their backing pg services and the redis-api service (not used yet, but we may soon).
`make psql-api` and `make psql-geo` should lead to the psql console for the api and geoprocessing db, respectively.
N/A
---
deploying to …

chore: update docker compose config and make targets for API development (API and geoprocessing)

---

app/components/dropdowns/menu/component.tsx
app/components/dropdowns/multi/component.tsx
app/components/dropdowns/single/component.tsx
app/components/dropdowns/toggle/component.tsx
app/components/dropdowns/types.d.ts
app/components/forms/checkbox/component.stories.tsx
app/components/forms/checkbox/component.tsx
app/components/forms/field/component.tsx
app/components/forms/input/component.stories.tsx
app/components/forms/input/component.tsx
app/components/forms/radio/component.stories.tsx
app/components/forms/radio/component.tsx
app/components/forms/select/component.stories.tsx
app/components/forms/slider/component.stories.tsx
app/components/forms/slider/component.tsx
app/components/forms/slider/thumb/component.tsx
app/components/forms/textarea/component.stories.tsx
app/components/forms/textarea/component.tsx

This PR adds:
- renaming
- onFocus and onBlur added to select

Form: rename status

---

api/CHANGELOG.md
api/src/app.module.ts
api/src/filters/all-exceptions.exception.filter.ts
api/src/main.ts
api/src/modules/authentication/authentication.controller.ts
api/src/modules/authentication/authentication.service.ts
api/src/modules/authentication/dto/sign-up.dto.ts
api/src/modules/organizations/organizations.service.ts
api/src/modules/scenarios/dto/create.scenario.dto.ts
api/src/modules/scenarios/scenario.api.entity.ts
api/src/modules/scenarios/scenarios.service.ts
api/test/app.e2e-spec.ts
api/test/e2e.config.ts
api/test/organizations.e2e-spec.ts
api/test/scenarios.e2e-spec.ts

Basic but hopefully effective catch-all exception filter.
Catches all uncaught exceptions that inherit from the base `Error` exception class.
Logs errors to logs.
In non-development environments, sends error code, message, request path and timestamp in API response for requests that trigger errors.
In development environments, also sends raw exception and stack trace 🚀 
I suppose we could avoid ever sending this info in the HTTP response and just log it. I'd keep it as is for now (it may help frontend devs to report issues without having to go and look at logs), and we can revisit later on.
N/A
Send some malformed requests to random API endpoints (maybe easier if a POST one) - error details should show in the API logs and in the response. …

[MARXAN-2] catch-all exceptions filter

---

api/src/modules/countries/countries.controller.ts
api/src/modules/organizations/organizations.controller.ts
api/src/modules/projects/projects.controller.ts
api/src/modules/scenarios/scenarios.controller.ts
api/src/utils/app-base.service.ts
api/test/app.e2e-spec.ts
api/test/organizations.e2e-spec.ts
api/test/scenarios.e2e-spec.ts

Fixes https://vizzuality.atlassian.net/browse/MARXAN-81 and updates all current controllers (GET :id, POST, PATCH) to return the correct data shape.
N/A
See acceptance tests in issue, but basically the e2e should do the work - they are updated to check what the acceptance tests ask.
```
docker-compose exec api yarn test:e2e test
```
https://vizzuality.atlassian.net/browse/MARXAN-81
---

[MARXAN-81] return object vs singleton in single responses

---

api/src/app.module.ts
api/src/migrations/api/1611329857558-initialDataMetadataEntities.ts
api/src/migrations/api/1613988195000-UpdateNullableColumnsForProjectsAndScenarios.ts
api/src/modules/projects/dto/create.project.dto.ts
api/src/modules/projects/project.api.entity.ts
api/src/modules/scenarios/dto/create.scenario.dto.ts
api/src/modules/scenarios/scenario.api.entity.ts
api/test/auth.e2e-spec.ts
api/test/e2e.config.ts
api/test/organizations.e2e-spec.ts
api/test/projects.e2e-spec.ts
api/test/scenarios.e2e-spec.ts

Remove not-needed constraints on creation of scenarios. Only the fields listed below are now required.
N/A
`make test-e2e-api`. It includes a new test that makes sure a scenario is created successfully with only the minimum set of compulsory props (`name`, `projectId`, `type`).
https://vizzuality.atlassian.net/browse/MARXAN-105
---

[MARXAN-105] API - scenarios: only enforce minimum prop set as compulsory

---

app/layout/header/component.tsx
app/layout/header/title/component.tsx
app/layout/header/title/index.ts
app/layout/scenarios/sidebar/name/component.tsx
app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
app/pages/projects/[pid]/scenarios/[sid]/index.tsx

This PR adds:
- Scenario creation by typing name
- Navigate to edit page
- Header title depending on Project and Scenario loader
https://www.figma.com/file/hq0BZNB9fzyFSbEUgQIHdK/Marxan-Visual_V02?node-id=1523%3A1468
http://localhost:3000/projects/b0a14339-732a-430b-a01d-6bc06494b05f/scenarios/new
https://marxan-git-feature-scenarios-name-vizzuality1.vercel.app/projects/b0a14339-732a-430b-a01d-6bc06494b05f/scenarios/new
try one of them to create a new scenario
https://vizzuality.atlassian.net/browse/MARXAN-105

Scenarios: header title and navigate between pages

---

api/src/main.ts
api/src/modules/admin-areas/admin-area.geo.entity.ts
api/src/modules/authentication/authentication.module.ts
api/src/modules/authentication/authentication.service.ts
api/src/modules/countries/country.geo.entity.ts
api/src/modules/users/dto/create.user.dto.ts
api/src/modules/users/users.module.ts
api/src/modules/users/users.service.ts
api/test/auth.e2e-spec.ts
api/test/countries.e2e-spec.ts
api/test/e2e.config.ts
api/test/organizations.e2e-spec.ts
api/test/projects.e2e-spec.ts
api/test/scenarios.e2e-spec.ts
api/test/users.e2e-spec.ts

`DELETE /api/v1/users/me` should (soft-) delete one's own user
Basically we set `isActive = false` and `isDeleted = true`, which flags the user for deletion **and** prevents them from logging in, while keeping the actual user account in the db.
We don't deal with the details of physically deleting the user at this stage - this would mean taking some decisions on "detaching" the user account from db entities it may be linked to. We may need to do something here because of data protection compliance, but we could also potentially deal with this by removing personal identification data from users flagged for deletion, without having to deal with more complexity which could be avoided in this phase.
N/A
`DELETE /api/v1/users/me` should succeed for logged-in users
After this, any existing and …

[MARXAN-128] Allow to delete one's own user

---

api/CHANGELOG.md
api/src/migrations/api/1614252349000-UpdateProjectsTable.ts
api/src/modules/admin-areas/admin-area.geo.entity.ts
api/src/modules/projects/dto/create.project.dto.ts
api/src/modules/projects/project.api.entity.ts
api/src/modules/projects/projects.service.ts
api/test/countries.e2e-spec.ts
api/test/e2e.config.ts

**This PR is ready for review, but it will need to be rebased on `develop` before merging**
Adds ability to supply l1 and l2 area ids, PU grid shape (`square`, `hexagon` or `from_shapefile` - though we don't handle shapefile uploads yet), and PU area.
N/A
We have e2e tests in `test/projects.e2e-spec.ts`, but something like this is what should be tested (`organizationId` need to match a real id on the target instance):
```
curl --location --request POST 'https://marxan49.westeurope.cloudapp.azure.com/api/v1/projects' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>' \
--data-raw '{
"name": "test project 29423409",
"organizationId": "bd1689c8-8246-42d5-9005-4aaa8aeb0049",
"description": "A Description For A Great Project",
"countryId": "ESP", …
```

[MARXAN-138] Update project creation and update endpoints with props required by design

---

app/hooks/auth/index.ts
app/layout/protected/component.tsx
app/layout/sign-in/component.tsx
app/layout/sign-up/component.tsx
app/pages/api/auth/[...nextauth].ts

Redirect to referral URL after login.
1. Ensure you are able to sign-in in the page going directly to the URL `/auth/sign-in`.
2. Ensure you are able to sign-in using the Sign-in button on the menu.
3. Ensure you are redirected to sign-in page trying to open a protected page such as `/projects`.
4. You have to see a new param `callbackUrl` in the URL bar. It will be used to redirect to that page after login is success.
5. Ensure you are redirected to `/projects` after Sign up.
[MARXAN-122](https://vizzuality.atlassian.net/browse/MARXAN-122?atlOrigin=eyJpIjoiODEwZGVjNGRkMTYxNGMzZThlYWZiYzE5YjVmMWNiZTkiLCJwIjoiaiJ9)

Redirect to referral URL after login

---

app/components/forms/select/menu/component.tsx
app/components/forms/select/multi/component.tsx
app/components/forms/select/single/component.tsx
app/components/forms/select/types.d.ts

This PR fixes issues where the select's options and choices would not be correctly announced to screen reader users.
1. Open http://192.168.10.161:6006/iframe.html?id=components-forms-select--default&viewMode=story in Safari
2. Activate Voiceover: <kbd>fn</kbd> + <kbd>⌘</kbd> + <kbd>F5</kbd>
3. Press the tab key <kbd>⇥</kbd> to focus on the component
4. Open the menu: <kbd>control ^</kbd> + <kbd>option ⌥</kbd> + <kbd>space</kbd>
5. Move to an option by pressing <kbd>control ^</kbd> + <kbd>option ⌥</kbd> + <kbd>down arrow ⬇️</kbd>
Make sure the option is correctly announced by the screen reader.
6. Toggle on and off an option by pressing:  <kbd>control ^</kbd> + <kbd>option ⌥</kbd> + <kbd>space</kbd>
Make sure the screen reader correctly announce when the option is removed or selected.
7. …

Fix accessibility issues with the Select component

---

app/components/button/component.tsx
app/layout/header/component.tsx

After a small discussion about how to do it, we decided to use the same Button component where we will decide depending on the `href` property how to render it. So, when href property exists it will be rendered using `<Link>`, in case of external links it will be `<a>`. And by default, and when href doesn't exist it will be a regular <Button>.
There are some links you can check on `/layout/header/component.tsx`.
Also, you can play with it on the Storybook site.
[MARXAN-142](https://vizzuality.atlassian.net/browse/MARXAN-142)
---

[MARXAN-142] Changed Button component to support Links as Buttons

---

README.md

when running "make start" using a .env based on the existing docs, computer says no

Add missing var docs to README

---

docker-compose.yml

On startup, the postgres docker images create a DB named after POSTGRES_DB env var, falling back to the POSTGRES_USER if POSTGRES_DB was not defined. As POSTGRES_DB was not passed explicitly, the DB would always have the name of the DB user, which is fine unless you specify different values for user and db on the project's .env file, for example
https://registry.hub.docker.com/_/postgres/
Also, added a few empty lines to this very dense docker compose file. seems like those are free, and they really help my 6:30AM brain read the file.

Add missing postgres db name env vars

---

api/src/ormconfig.ts

In some scenarios, when running the api natively, TypeORM will load the "compiled" entities (.js file from the dist folder) and thus will fail to load some entities.

Fix issue with TypeORM loading entities from the dist folder

---

api/src/filters/all-exceptions.exception.filter.spec.ts

Most importantly, this also avoids having to explicitly type `this`.
This PR basically lets the changed code work with the fully strict TS settings we just introduced (the change was not included in the PR where we introduced fully strict settings because the code affected by this was merged after creating the fully-strict branch)

use mockReturnThis() for convenience

---

Makefile
Makefile-ci
README.md
api/config/custom-environment-variables.json
api/package.json
api/src/filters/all-exceptions.exception.filter.ts
api/src/main.ts
api/src/migrations/api/1619711501000-DropNotNullsOnTimeUserMetadataColumns.ts
api/src/modules/admin-areas/admin-areas.service.ts
api/src/modules/api-events/api-events.service.ts
api/src/modules/countries/countries.service.ts
api/src/modules/geo-features/geo-features.service.ts
api/src/modules/organizations/organizations.service.ts
api/src/modules/projects/projects.service.ts
api/src/modules/protected-areas/protected-areas.service.ts
api/src/modules/scenarios-features/scenario-features.service.ts
api/src/modules/scenarios/scenarios.service.ts
api/src/modules/users/users.service.ts
api/src/utils/app-base.service.ts
api/test/proxy.vector-tiles.e2e-spec.ts
api/yarn.lock
geoprocessing/src/filters/all-exceptions.exception.filter.ts

- Allow to mute all logging irrespective of Node env and other settings that would affect Logger verbosity, via `API_LOGGING_MUTE_ALL` envvar
e.g. `docker-compose run -e API_LOGGING_MUTE_ALL=true api yarn test:e2e`
- Backport (manually for now) today's updates to `seed-geoapi-with-test-data` Makefile recipe to local and ci e2e recipes
Missing (moving them to future PRs):

various fixes/improvements to CI workflow

---

docs/README_API_development_workflow.md

Replaces https://github.com/Vizzuality/marxan-cloud/pull/168

API development workflow proposal

---

api/src/migrations/api/1621341638168-CostSurfaceEvents.ts
api/src/modules/api-events/api-event.api.entity.ts
api/src/modules/api-events/api-events.module.ts
api/src/modules/api-events/api-events.service.ts
api/src/modules/scenarios/cost-surface/__mocks__/adjust-cost-service-fake.ts
api/src/modules/scenarios/cost-surface/__mocks__/cost-surface-events-fake.ts
api/src/modules/scenarios/cost-surface/__mocks__/shapefile-converter-fake.ts
api/src/modules/scenarios/cost-surface/__mocks__/surface-cost.data.ts
api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.spec.ts
api/src/modules/scenarios/cost-surface/adapters/cost-surface-api-events.ts
api/src/modules/scenarios/cost-surface/adapters/geoprocessing-cost-from-shapefile.ts
api/src/modules/scenarios/cost-surface/cost-surface-events.port.ts
api/src/modules/scenarios/cost-surface/cost-surface.facade.spec.ts
api/src/modules/scenarios/cost-surface/cost-surface.facade.ts
api/src/modules/scenarios/cost-surface/resolve-pu-with-cost.ts
api/src/modules/scenarios/scenarios.controller.ts
api/src/modules/scenarios/scenarios.module.ts

Part of `Users should be able to upload shapefiles of scenario cost surfaces` - subtask https://vizzuality.atlassian.net/browse/MARXAN-413
---

feat(api): cost-surface: application logic

---

Makefile

So far we've been ignoring non-zero exit codes from the two test runs for each of unit and e2e test recipes in GH Action, leading to tests being shown as always passing even if one or both of the test runs failed.
This PR adds `--keep-going` to avoid stopping the recipe, while propagating error conditions to the make exit code.
Good luck 😬 - I suggest to test locally by breaking one of the e2e tests for the API service on purpose (as these run before the geoprocessing e2e tests), and verifying that the geoprocessing tests still run, and that final teardown happens, but make exits with a non-zero exit code.

keep going when single test runs fail, but exit make signaling error

---

docs/adr/0002_file-uploads.md

See https://vizzuality.atlassian.net/browse/MARXAN-438

ADR for file uploads

---

api/apps/api/src/ormconfig.ts
api/apps/geoprocessing/src/ormconfig.ts

refactor: allow to pick up entities from shared libraries

---

e2e-product-testing/cypress.json

Just 2 options in `cypress.json`
"screenshotOnRunFailure": true,    // Default is true, but letting this here if anytime anyone needs to change it
"videoUploadOnPasses": false

Disable generate reports on test success

---

api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/scenarios/dto/scenario-feature.serializer.ts
api/apps/api/src/modules/scenarios/dto/scenario.serializer.ts
api/apps/api/src/modules/scenarios/scenario.service.ts
api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-pu-change/scenario-put-change.e2e-spec.ts
api/apps/api/test/scenario-pu-change/steps/world.ts

Similar to `projects`:
* move current service to `crud-service` and wrap existing functions,
* the ones that act on a given `scenarioId` received existing `guard` which verifies existence of given Scenario,
* move serializers to standalone classes
* leaves space for ACL stuff
* "fixed" spec for changing planning unit's inclusivity (by id / geo) - it was running without existing scenario id, added check prevents that

MARXAN - 448 Cost surface - scenarioId guard

---

api/apps/api/src/modules/projects/dto/job-status.serializer.ts
api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
api/apps/api/src/modules/projects/job-status/job-status.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts

feat(api): projects: job-status api serializer

---

api/apps/api/src/modules/scenarios-features/scenario-features.service.ts
api/apps/api/test/scenario-features/get-scenario-features.e2e-spec.ts
api/apps/api/test/scenario-features/steps/when-scenario-has-pre-gap-data.ts

test(api): scenario-features: pre-gap data formatting & enable spec

---

api/apps/api/src/migrations/api/1623311716713-AddJobStatusView.ts
api/apps/api/src/modules/projects/dto/job-status.serializer.ts
api/apps/api/src/modules/projects/dto/project-jobs-status.dto.ts
api/apps/api/src/modules/projects/job-status/index.ts
api/apps/api/src/modules/projects/job-status/job-status-target-events.ts
api/apps/api/src/modules/projects/job-status/job-status.service.ts
api/apps/api/src/modules/projects/job-status/job-status.view.api.entity.ts
api/apps/api/src/modules/projects/job-status/jobs.enum.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
api/apps/api/test/project-jobs-status/job-status.service.integration.e2e-spec.ts
api/apps/api/test/project-jobs-status/project-job-status.e2e-spec.ts
api/apps/api/test/project-jobs-status/world.ts
api/apps/api/test/steps/given-api-event.ts
api/apps/api/test/steps/given-scenario-exists.ts
api/libs/api-events/src/api-event-kinds.enum.ts

feat(api): projects: jobs status

---

api/apps/api/src/modules/scenarios/dto/create.scenario.dto.ts
api/apps/api/src/modules/scenarios/dto/scenario-metadata.dto.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/project-scenarios.e2e-spec.ts
api/libs/marxan-input/src/index.ts
api/libs/marxan-input/src/marxan-parameters.ts

Marxan Input parameters are separated on purpose from the dto itself:
* (future) difference in dto shape
* allow to validate regardless of the transport layer (and validation pipe flag in our case as well)

feat(scenario): validate marxan input

---

api/apps/api/src/modules/scenarios/dto/scenario-solution-result.dto.ts
api/apps/api/src/modules/scenarios/dto/scenario-solution.serializer.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/src/modules/scenarios/solutions-result/solution-result-crud.service.ts
api/apps/api/test/scenario-solutions/get-all-solutions.e2e-spec.ts
api/apps/api/test/scenario-solutions/world.ts
api/libs/scenarios-planning-unit/src/index.ts
api/libs/scenarios-planning-unit/src/scenarios-output-results.geo.entity.ts

This PR mainly touches base implementation of an API layer and leaves space for actual implementation; includes:
* entity 
* dtos
* crud-service based on AppBaseService
It may happen that some `runId` or other fields aren't correct (according to discussion on slack) but I would opt in for leaving it for future PR once it is well settled.

feat(api): allow to get scenarios solutions results

---

api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
api/apps/geoprocessing/test/index.html

With BBox present there is no need to simplify.

---

app/hooks/administrative-areas/index.ts
app/hooks/countries/index.ts
app/layout/projects/new/form/component.tsx
app/layout/projects/new/form/planning-area-selector/component.tsx
app/layout/projects/new/form/planning-area-selector/country-region-selector/component.tsx
app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/component.tsx
app/layout/projects/new/form/planning-area-selector/planning-unit-area-size/types.ts
app/layout/projects/new/form/planning-area-selector/types.ts
app/store/slices/projects/new.ts
app/types/country-model.ts

This PR adds:
- min / max set by admin areas

Max min area size

---

api/apps/api/test/scenarios/input-file.e2e-spec.ts

test(api): add e2e test for setting and getting marxan input

---

api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/business-critical/marxan-run/execute-marxan-run.e2e-spec.ts
api/apps/api/test/business-critical/marxan-run/fixtures.ts
api/apps/api/test/steps/given-project.ts
api/apps/api/test/steps/given-scenario-exists.ts

Fundamentals for full process of running marxan

feat(marxan-run): expose endpoints for starting/cancelling marxan execution

---

api/apps/api/test/scenario-cost-template/bull-mq-integration.e2e-spec.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1625037619200-AddIndicesToPlanningArea.ts
api/apps/geoprocessing/test/integration/planning-areas/custom-planning-area.repository.e2e-spec.ts
api/libs/planning-area-repository/src/custom-planning-area.repository.ts
api/libs/planning-area-repository/src/planning-area.geo.entity.ts

[MARXAN-446] planning area assigning

---

api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/metadata/metadata-exection-metadata.repository.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.spec.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/result-parser.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/solutions-output.module.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/solutions-output/solutions-output.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandboxed-runner.module.ts
api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
api/libs/marxan-output/src/execution-result.ts
api/libs/marxan-output/src/index.ts

feat(marxan-run): return parsed output

---

api/apps/api/config/custom-environment-variables.json
api/apps/api/config/default.json
api/apps/api/src/modules/scenarios/marxan-run/assets.service.spec.ts
api/apps/api/src/modules/scenarios/marxan-run/assets.service.ts
api/apps/api/src/modules/scenarios/marxan-run/index.ts
api/apps/api/src/modules/scenarios/marxan-run/input-parameter-file.provider.spec.ts
api/apps/api/src/modules/scenarios/marxan-run/input-parameter-file.provider.ts
api/apps/api/src/modules/scenarios/marxan-run/io-settings.ts
api/apps/api/src/modules/scenarios/marxan-run/marxan-files.service.ts
api/apps/api/src/modules/scenarios/marxan-run/marxan-run.controller.ts
api/apps/api/src/modules/scenarios/marxan-run/marxan-run.module.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/jest-e2e.json
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
api/apps/geoprocessing/test/jest-e2e.json
api/libs/scenario-run-queue/src/index.ts
api/libs/scenario-run-queue/tsconfig.lib.json
api/nest-cli.json
api/package.json
api/tsconfig.json

feat(api): pass assets to marxan run job

---

e2e-product-testing/cypress/integration/AdjustPlanningUnits.feature
e2e-product-testing/cypress/integration/Features.feature
e2e-product-testing/cypress/integration/GapAnalysis.feature
e2e-product-testing/cypress/integration/LogIn.feature
e2e-product-testing/cypress/integration/Project.feature
e2e-product-testing/cypress/integration/ProtectedAreas.feature
e2e-product-testing/cypress/integration/RunScenario.feature
e2e-product-testing/cypress/integration/Scenario.feature
e2e-product-testing/cypress/integration/Solutions.feature

Given that wiring up specs to actual testing behaviour will take a while, I have tried to focus on the happy-path scenarios which should be key for MVP (I did overdo a bit towards the end of the user journey, from feature selection onwards, I think, but we can trim further as we go).
The idea here is to start wiring up the `@happypath` scenarios, leaving the rest for later, while still keeping, in the meanwhile, all the specs as a useful documentation of what we expect users to be able to do on the platform, in a language which is both machine and human friendly (I know, I never hear anyone in daily life talking in Gherkin given-when-then style, but I would say it's at least understandable if not really friendly 😅 ).

tag happy-path scenario specs

---

api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/marxan-directory.service.spec.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/workspace/ports/temporary-directory.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/workspace/shared-storage.spec.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/workspace/shared-storage.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/workspace/workspace.module.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters/workspace/workspace.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/ports/workspace.ts

feat(marxan-runner): use output directory provided via input.dat

---

api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/projects.e2e-spec.ts

feat(api): add q-search in projects

---

api/apps/api/src/modules/scenarios/input-files/index.ts
api/apps/api/src/modules/scenarios/input-files/input-files-archiver.service.spec.ts
api/apps/api/src/modules/scenarios/input-files/input-files-archiver.service.ts
api/apps/api/src/modules/scenarios/input-files/input-files.module.ts
api/apps/api/src/modules/scenarios/input-files/input-files.service.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
api/apps/api/test/scenario-input-files/world.ts

feat(scenarios): create input zip archive from files

---

api/apps/api/src/modules/analysis/providers/planning-units/__mocks__/api-events.mock.ts
api/apps/api/src/modules/analysis/providers/planning-units/update-planning-units.service.spec.ts
api/apps/api/src/modules/analysis/providers/planning-units/update-planning-units.service.ts
api/apps/api/src/modules/analysis/providers/shared/adapters/are-puids-allowed-adapter.ts
api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts

fix(scenario): planning units lockin change

---

api/apps/geoprocessing/src/migrations/geoprocessing/1626682903111-OutputScenariosPuDataAggregate.ts

This will be needed in instances that run this migration while already having some seed data in the `output_scenarios_pu_data` table to avoid a not null constraint violation.

provide temporary column default

---

api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-run.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/progress.spec.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/progress.ts
api/apps/geoprocessing/src/modules/scenarios/run.worker.ts
api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
api/apps/geoprocessing/test/integration/marxan-run/run-worker.e2e-spec.ts

feat(geoprocessing): report progress of the marxan run

---

api/apps/api/src/modules/projects/projects-crud.service.ts

fix planning area assignment

---

app/.eslintrc.js
app/package.json
app/yarn.lock

Test to sort imports by path groups using an eslint plugin. We would need to align if this is the order we want and add all the dependencies

feat: order imports eslint configs

---

app/hooks/projects/index.ts
app/hooks/projects/types.ts
app/hooks/scenarios/index.ts
app/hooks/scenarios/types.ts
app/layout/community/published-projects/detail/component.tsx
app/layout/community/published-projects/duplicate-button/component.tsx
app/layout/projects/all/list/component.tsx
app/layout/projects/show/scenarios/component.tsx

At the moment only posting a project id to be able to generate a response of this data project with a "duplicate key" and "user who duplicates it".
[MARXAN-599](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-599&quickFilter=71)

feat(front): duplicate projects and scenarios [MARXAN-599]

---

app/layout/projects/new/form/planning-area-uploader/component.tsx

[MARXAN-542](https://vizzuality.atlassian.net/secure/RapidBoard.jspa?rapidView=38&projectKey=MARXAN&modal=detail&selectedIssue=MARXAN-542&quickFilter=71)

front: add data on upload shapefile when create project [MARXAN-542]

---

api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.data.service.spec.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1627980508000-AddIndexesForPuVSprQueries.ts
api/libs/scenario-puvspr/src/scenario-puvspr.geo.entity.ts

as discussed with Alicia - implementation based on view (which I have kept for the moment) does not allow (as far as I can think...) to prefilter by `scenarioId` - with the implementation proposed in this PR I have been able to get query times down from ~4min with test data to ~20secs (most of the deal is actually indexes, but still, we also filter out data we won't need)

improve puvspr.dat queries

---

api/apps/api/src/modules/projects/project.api.entity.ts
api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units-linker-service.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1628277500000-AddSupportForCustomPlanningUnitGrids.ts
api/apps/geoprocessing/src/modules/planning-units/dto/create.regular.planning-units.dto.ts
api/libs/planning-unit-geometry/src/planning-units.geo.entity.ts

https://vizzuality.atlassian.net/browse/MARXAN-663
Totally mixing concerns, but while at this, I have added the new column to link back custom PU grid geometries to projects as discussed in https://vizzuality.atlassian.net/browse/MARXAN-279, just because the logic in this PR references that column (even if the corresponding code path can't yet be triggered in practice).
I have also updated `PlanningUnitGridShape.fromShapefile` to match what we have in the `shape_type` pg type (`irregular`) - this would not affect the current PR, but once we add support for irregular grids, linking them to scenarios would trigger a db error without this change. I checked if this could affect other parts of the code - I don't think it would, and it doesn't seem to break any tests, but 🤷🏼.
To test this, we …

fix queries in scenario/pu linker to properly support custom planning areas

---

app/hoc/scenarios.ts
app/hooks/gap-analysis/index.ts
app/hooks/map/index.ts
app/hooks/map/types.ts
app/hooks/solutions/index.ts
app/hooks/solutions/mock.ts
app/layout/scenarios/edit/features/component.tsx
app/layout/scenarios/edit/map/component.tsx
app/layout/scenarios/edit/run/component.tsx
app/layout/scenarios/edit/run/constants.tsx
app/layout/scenarios/edit/tabs/component.tsx
app/layout/scenarios/edit/tabs/constants.ts
app/layout/scenarios/edit/wdpa/component.tsx
app/layout/scenarios/edit/wdpa/threshold/component.tsx
app/layout/scenarios/show/analysis/adjust-planning-units/component.tsx
app/layout/scenarios/show/analysis/cost-surface/component.tsx
app/layout/scenarios/show/map/component.tsx
app/layout/scenarios/show/solutions/details/component.tsx
app/layout/scenarios/show/solutions/table-form/component.tsx
app/layout/scenarios/show/solutions/table/component.tsx
app/pages/projects/[pid]/scenarios/[sid]/edit.tsx
app/pages/projects/[pid]/scenarios/[sid]/index.tsx
app/public/styles/tailwind.storybook.css
app/store/slices/scenarios/detail.ts
app/types/project-model.ts

This PR adds:
- withScenario HOC to prefetch scenarios from server
- use wdpaIucnCategories and wdpaThreshold from scenario data

WDPA: read them from scenario instead of store in certain cases

---

api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/__mocks__/include-sample.ts
api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts

It probably isn't most optimal solution (could make conditional update but honestly, it would be even slower).
Also all `to be included` features should have the flag turned on within specs but I haven't found easy way to implicite turn it only for one without turning the whole spec upside down.

feat(planning-units): lock-in areas protected by default

---

api/apps/api/src/migrations/api/1629874400088-roles.ts
api/apps/api/src/modules/projects/control-level/users-projects.api.entity.ts
api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/src/modules/users/role.api.entity.ts
api/apps/api/test/fixtures/test-init-apidb.sql
api/apps/api/test/project/project-get.e2e-spec.ts
api/apps/api/test/project/user-projects.e2e-spec.ts
api/apps/api/test/project/user-projects.fixtures.ts
api/apps/api/test/steps/given-user-is-logged-in.ts

MARXAN-582 restrict list of projects returned to user to their own projects only
migration (instead of seeds) will have a followup PR (please don't merge this one now)..
Implementation details:
Options were:
1. Add relations and cascade create
1. pros: transactional
2. cons: project itself knowing about roles/privileges; possible issues with adding further roles ([…roles, newRole])
2. Extracting roles/privileges into standalone (sub)module
1. pros: clear separation
2. cons: would require fine amount of changes to keep it in transaction; we don’t know the full shape of rbac/acl
3. Attaching to ~BaseService’s `actionAfterCreate`
1. pros: pretty straightforward, easy to „remove”; failed non-transactional insert into user_projects may leave orphaned projects
2. cons: overextending …

feat(projects): find returns only projects created by user

---

api/apps/api/src/modules/scenarios/marxan-run/output.repository.ts

(bug for keeping old ones is in tracking system)

fix(marxan-run): score/cost values should be persisted

---

api/apps/api/src/modules/scenarios/marxan-run/output.repository.ts

Ideally it should be done in transaction... in future

fix(marxan-run): remove old summaries of a scenario run

---

app/components/forms/select/toggle/component.tsx
app/components/info-button/component.tsx
app/components/map/controls/fit-bounds/component.tsx
app/components/map/controls/zoom/component.tsx
app/components/map/legend/item/component.tsx
app/components/search/component.tsx
app/components/tabs/component.tsx
app/components/toast/component.tsx
app/layout/header/component.tsx
app/layout/header/user/component.tsx
app/layout/help/beacon/component.tsx
app/layout/me/profile/avatar/component.tsx
app/layout/partners/component.tsx
app/layout/projects/new/form/planning-area-uploader/component.tsx
app/layout/projects/show/header/contributors/component.tsx
app/layout/scenarios/edit/analysis/cost-surface/component.tsx
app/layout/scenarios/edit/analysis/gap-analysis/component.tsx
app/layout/scenarios/edit/features/component.tsx
app/layout/scenarios/edit/wdpa/categories/component.tsx
app/layout/scenarios/show/analysis/gap-analysis/component.tsx
app/layout/scenarios/show/solutions/details/component.tsx
app/layout/scenarios/show/solutions/gap-analysis/component.tsx
app/layout/scenarios/show/solutions/list/component.tsx
app/layout/scenarios/show/solutions/table-form/component.tsx
app/layout/sections/item/component.tsx
app/layout/statics/contact/component.tsx
app/pages/_document.tsx

Front(fix) texts and performance

---

api/apps/api/src/modules/scenarios/marxan-run/events.handler.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-run.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/marxan-sandbox-runner.service.ts
api/apps/geoprocessing/src/modules/scenarios/run.worker.ts
api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts

Reason for using `string` within `new Error(...)` is that `bullmq` assumes such format so that the job data contains `failedReason` property derived from this very type (i.e. if processor finished throwing an error)
source: https://github.com/taskforcesh/bullmq/issues/537#issuecomment-836601738

fix(marxan-run): in case of any error, handle it and use failed-reason

---

api/apps/api/src/modules/scenarios/marxan-run/cancel.handler.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts

feat(api): mark scenario run as failed while canceled

---

api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-pu-change/scenario-pu-reset.integration.e2e-spec.ts
api/apps/api/test/steps/given-scenario-pu-data-exists.ts

feat(scenario-pu): allow to reset lock status to default

---

api/apps/api/src/modules/projects/planning-unit-grid/planning-unit-grid-set.saga.ts
api/apps/api/src/modules/projects/planning-unit-grid/planning-unit-grid.module.ts
api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.command.ts
api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.handler.ts
api/apps/api/src/modules/projects/project.api.entity.ts

- unpacking shapefile and adding geometries - https://github.com/Vizzuality/marxan-cloud/pull/525
- exposing endpoint to submit & api events - https://github.com/Vizzuality/marxan-cloud/pull/527
- updating project `planning_unit_grid_shape` - https://github.com/Vizzuality/marxan-cloud/pull/529 (this)
- exposing endpoint to get the request status - https://github.com/Vizzuality/marxan-cloud/pull/528

feat(custom-pu-grid): set project grid shape once geometries were set

---

api/apps/api/test/project/create-project-wdpa-area-filter.e2e-spec.ts
api/apps/api/test/project/create-project-wdpa-area-filter.fixtures.ts

fix(scenarios): wdpa filters

---

api/apps/api/src/dto/async-job-tag.ts
api/apps/api/src/dto/async-job-type.ts
api/apps/api/src/dto/async-job.dto.ts
api/apps/api/src/dto/inline-job-tag.ts
api/apps/api/src/modules/geo-features/geo-feature-set.api.entity.ts
api/apps/api/src/modules/geo-features/geo-feature-set.serializer.ts
api/apps/api/src/modules/projects/dto/project-grid-request.dto.ts
api/apps/api/src/modules/projects/dto/project.serializer.ts
api/apps/api/src/modules/projects/project.api.entity.ts
api/apps/api/src/modules/projects/projects-listing.controller.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/scenarios/dto/scenario.serializer.ts
api/apps/api/src/modules/scenarios/scenario.api.entity.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/test/project-grid/project-grid.fixtures.ts
api/apps/api/test/project-protected-areas/project-protected-areas-upload-shapefile.e2e-spec.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/projects.e2e-spec.ts
api/apps/api/test/scenario-pu-change/scenario-put-change.e2e-spec.ts

We should be carefully when serializing stuff.
1. "meta" is already included when pagination is defined
2. neither "meta" nor "pagination" is defined within swagger / classes, thus using `plainToClass` removes it
3. I haven't refactored "mixing" them, nor the OpenApi docs.
We should consider redesign of creating OpenApi definitions, meta inclusion/mixing, responsibilities and serialization itself.
-  Project create / upload - MAY create an actions
-  projects/:id/protected-areas/shapefile
-  projects/:id/grid
- projects/:id/features/shapefile (API-side)
- projects/:id/planning-area/shapefile („inline” proxy go Geoprocessing)
 
- Create / update scenario (CalculatePlanningUnitsProtectionLevel)
- scenarios/:id/marxan
- scenarios/:id/planning-units
- scenarios/:id/cost-surface/shapefile
- …

feat(api): include async job status in all relevant endpoints

---

api/apps/geoprocessing/src/modules/scenario-protected-area-calculation/scenario-protected-area-calculation-processor.ts

Without this constraint, all rows (of any scenarios in any project) would be overwritten.
For rows of the scenario being processed, the value of `protected_area` would be set to the correct value; for all other rows (other scenarios in any project), `protected_area` would be silently set to null as there is no data coming in via the CTE for rows that don't belong to the scenario being processed.
https://vizzuality.atlassian.net/browse/MARXAN-791
I still need to check whether all tiles now include the `percentageProtected` data, which should not have happened in any case at least for the scenario I was actively working on while triaging this issue.

[MARXAN-791] fix missing constraint leading to updating of rows that don't belong to the scenario being processed

---

api/apps/api/src/modules/geo-features/geo-feature-set.service.ts
api/apps/api/src/modules/geo-features/geo-features.module.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
app/hooks/features/index.ts

refactor(geo-features): remove unused code

---

api/apps/api/src/modules/geo-features/geo-feature-property-sets.service.ts
api/apps/api/src/modules/geo-features/geo-features-request-info.ts
api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/geo-features/index.ts
api/apps/api/src/modules/projects/project-requests-info.ts
api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/geo-features.e2e-spec.ts

PR is hard to read in one diff - recommended way it commit-by-commit.
First one contains a little re-organization of "AppInfoDTO" thingy to keep known properties really known - during that it proved that some property is "used" but not really created/added at any point, thus leading to not using project id correctly
Second is another fix - previously the `OR like ...` was out of the other conditions, totally ignoring project limitations. Thanks @Sikora00 for spotting this!
With search param:

fix(geo-features): searching via name should include project-id

---

app/hooks/map/index.ts
app/hooks/map/types.ts
app/layout/projects/new/form/component.tsx
app/layout/projects/new/form/constants.ts
app/layout/projects/new/form/planning-area-grid-uploader/component.tsx
app/layout/projects/new/form/planning-area-uploader/component.tsx
app/layout/projects/new/map/component.tsx
app/layout/projects/new/map/types.ts

This PR contains:
[Client feedback](https://projects.invisionapp.com/share/7G11WET8YM5H#/screens/459985293/comments)
Create a project with a planning area custom grid: "_Yes, I have a planning unit shapefile_" option. Then creates an scenario.
Shapefile is available attached to [MARXAN-950](https://vizzuality.atlassian.net/jira/software/c/projects/MARXAN/boards/38?modal=detail&selectedIssue=MARXAN-950)
[MARXAN-952](https://vizzuality.atlassian.net/jira/software/c/projects/MARXAN/boards/15?modal=detail&selectedIssue=MARXAN-952&assignee=60d985f51613d50069adeabc)
[MARXAN-950](https://vizzuality.atlassian.net/jira/software/c/projects/MARXAN/boards/38?modal=detail&selectedIssue=MARXAN-950)
[MARXAN-938](https://vizzuality.atlassian.net/jira/software/c/projects/MARXAN/boards/15?modal=detail&selec …

Fix(front): planning area [MARXAN-952][MARXAN-950][MARXA-938]

---

api/apps/api/src/modules/scenarios/dto/upload.shapefile.dto.ts
api/apps/api/src/modules/scenarios/protected-area/protected-area.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/geoprocessing/src/modules/protected-areas/worker/protected-area-processor.ts
api/apps/geoprocessing/test/integration/protected-areas/steps/shapefile-for-wdpa-world.ts
api/apps/geoprocessing/test/integration/protected-areas/upload-shapefile-for-project.e2e-spec.ts
api/libs/protected-areas/src/add-protected-area-input.ts

This PR adds the possibility of providing (optionally) a `name` when uploading shapefile for a project scenario using the endpoint `POST api/v1/scenarios/':id/protected-areas/shapefile')`.
If no `name` is provided, the current behavior is kept - the file name is used and inserted in the DB as `fullName`.
1. Call the `POST api/v1/scenarios/':id/protected-areas/shapefile')` endpoint, providing only the shapefile - the inserted row in the `wdpa` table in the `geo` database should have `fullName` set to the name of the uploaded file (existing behavior).
2. Call the `POST api/v1/scenarios/':id/protected-areas/shapefile')` endpoint, providing the shapefile and a `name` in the request body - the inserted row in the `wdpa` table in the `geo` database should have `fullName` set to the provided …

Allow uploaded protected area to be given a name

---

docs/features/boundary-length-modifier/brief.md
docs/features/boundary-length-modifier/development-plan.md
docs/features/boundary-length-modifier/high-level-design.md

This PR updates the BLM calibration brief describing the current/latest functional requirements, whereby users are asked to supply only a `[min, max]` range, from which we derive the intermediate values on a linear scale.

derive BLM calibration values from min,max range [MARXAN-890]

---

api/apps/api/src/app.module.ts
api/apps/api/src/modules/blm/blm.module.ts
api/apps/api/src/modules/blm/index.ts
api/apps/api/src/modules/blm/values/blm-values.module.ts
api/apps/api/src/modules/blm/values/index.ts
api/apps/api/src/modules/blm/values/project-blm-repository.ts
api/apps/api/src/modules/blm/values/typeorm-project-blm-repository.ts
api/apps/api/src/modules/projects/blm/change-blm-range.command.ts
api/apps/api/src/modules/projects/blm/change-blm-range.handler.ts
api/apps/api/src/modules/projects/blm/index.ts
api/apps/api/src/modules/projects/blm/project-blm.module.ts
api/apps/api/src/modules/projects/blm/project-blm.saga.ts
api/apps/api/src/modules/projects/blm/set-project-blm-handler.ts
api/apps/api/src/modules/projects/blm/set-project-blm.ts
api/apps/api/src/modules/projects/projects.module.ts
api/libs/planning-units-grid/src/index.ts
api/libs/planning-units-grid/src/planning-unit-set.event.ts

This PR includes a "skeleton" of application shape. The main purpose of it is to fulfill requirements related to calculating default BLM values after project has been created (as its grid/planning units). 
Once its merged, the following tasks/pieces should be relatively easy to complete in isolation:
https://vizzuality.atlassian.net/browse/MARXAN-995
https://vizzuality.atlassian.net/browse/MARXAN-996
https://vizzuality.atlassian.net/browse/MARXAN-997
https://vizzuality.atlassian.net/browse/MARXAN-998
https://vizzuality.atlassian.net/browse/MARXAN-999
https://vizzuality.atlassian.net/browse/MARXAN-1000 (🚀)

feat(blm): project defaults skeleton

---

api/apps/api/config/default.json
api/apps/api/src/modules/authentication/authentication.controller.ts
api/apps/api/src/modules/authentication/authentication.service.ts
api/apps/api/src/modules/authentication/dto/user-account.validation.dto.ts
api/apps/api/src/modules/authentication/password-recovery/mailer.ts
api/apps/api/src/modules/authentication/password-recovery/password-recovery.spec.ts
api/apps/api/test/users.e2e-spec.ts

This PR adds the user account confirmation flow, as described [in this document](https://docs.google.com/document/d/1kEEgckbv6K7MoCpUSClJMUl3AV9hNUsjPN52CZte9DY/edit?usp=sharing).
After signing-up, an email should be sent to the new user with instructions on how to confirm their account:
1. If the user does not click on the confirm link in the email, they should not be able to log in to the platform;
2. If the user clicks on the confirm link in the email, they should be taken to the front end of the platform, where their account will be activated and they will be able to log in.
[MARXAN-947](https://vizzuality.atlassian.net/browse/MARXAN-947)
---

User account confirmation after signing up

---

api/apps/api/src/modules/authentication/password-recovery/mailer.ts
api/apps/api/test/users.e2e-spec.ts

This PR adds `userId` to the confirmation URL sent via Sparkpost, so that it can be used by the FE when validating the account. 
The confirmation URL included in sign up confirmation URL sent via email to the user should include the ID of the user trying to log in as query parameter (`userId`).
[MARXAN-947](https://vizzuality.atlassian.net/browse/MARXAN-947)
---

Provide user id to Sparkpost template data on sign up confirmation

---

api/apps/api/test/access-control/project-acl-delete.e2e-spec.ts
api/apps/api/test/access-control/project-acl-get.e2e-spec.ts
api/apps/api/test/access-control/project-acl-patch.e2e-spec.ts
api/apps/api/test/access-control/project-acl.fixtures.ts
api/apps/api/test/fixtures/test-data.sql
api/apps/api/test/utils/projects-acl.test.utils.ts

- Split tests into get / patch / delete tests.
- Usage of already created projects to check GET actions without unnecessary steps
- Changes how cleanup is processed for e2e tests
Part of [MARXAN-1076](https://vizzuality.atlassian.net/browse/MARXAN-1076)

test: adds fixtures, improvements in project-acl e2e tests

---

README.md
api/apps/api/config/custom-environment-variables.json
api/apps/api/config/default.json
api/apps/api/src/modules/authentication/password-recovery/mailer.ts
api/apps/api/test/users.e2e-spec.ts
env.default

This PR enables the sign up confirmation URL to be configurable through an environment variable (`SIGNUP_CONFIRMATION_TOKEN_PREFIX`). This variable should take the appropriate value according to the environment where the code is deployed.
[MARXAN-947](https://vizzuality.atlassian.net/browse/MARXAN-947)

Sign-up confirmation base URL configurable through env var

---

app/hooks/map/index.ts
app/hooks/wdpa/index.ts
app/hooks/wdpa/types.ts
app/layout/scenarios/edit/map/component.tsx
app/layout/scenarios/edit/status/actions/done.tsx
app/layout/scenarios/edit/status/actions/failure.tsx
app/layout/scenarios/edit/status/component.tsx
app/layout/scenarios/edit/status/constants.ts
app/layout/scenarios/edit/tabs/component.tsx
app/layout/scenarios/edit/wdpa/categories/component.tsx
app/layout/scenarios/edit/wdpa/categories/pa-uploader/component.tsx
app/layout/scenarios/edit/wdpa/component.tsx
app/layout/scenarios/edit/wdpa/pa-selected/component.tsx
app/layout/scenarios/edit/wdpa/threshold/component.tsx
app/layout/scenarios/show/map/component.tsx
app/layout/scenarios/show/wdpa/component.tsx

Add custom protected areas when user creates scenarios.
1. Connect to m56 env.
2. Create a Botswana project.
3. Create a scenario.
4. Upload a custom protected area with custom name.
5. Add custom area to scenario.
6. Set a low threshold (PAs shapefile are very small).
7. Fill rest of the parameters o a scenario.
8. Run scenario.
9. Create an other scenario with same custom protected area shapefile. 
10. Try to edit first scenario created adding new protected areas 
[MARXAN-743](https://vizzuality.atlassian.net/browse/MARXAN-743)
---

Feat(front): upload and update protected areas[MARXAN-743]

---

api/apps/api/src/modules/projects/projects-crud.service.ts

This PR removes the `users` field returned in project endpoints, which previously contained the users assigned to a project. Users assigned to a project should now be fetched from the `GET /api/v1/roles/projects/{id}/users` endpoint, which applies the proper ACL checks to see if the request user is authorized to see the project users.
[MARXAN-1075](https://vizzuality.atlassian.net/browse/MARXAN-1075)

Not returning project users on project endpoints

---

api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.service.ts

- Use of check inside the project-service correspondent method.
- Use of monad to handle errors.

CanCreateProject check in project endpoint

---

api/apps/api/src/app.module.ts
api/apps/api/test/files-repository/files-repository.e2e-spec.ts
api/apps/api/test/files-repository/some-file.json
api/apps/api/test/jest-e2e.json
api/apps/api/test/utils/api-application.ts
api/apps/geoprocessing/test/jest-e2e.json
api/libs/files-repository/src/file-repo.config.ts
api/libs/files-repository/src/file-repository.module.ts
api/libs/files-repository/src/file-upload.service.spec.ts
api/libs/files-repository/src/file.repository.ts
api/libs/files-repository/src/index.ts
api/libs/files-repository/src/temp-storage.repository.ts
api/libs/files-repository/tsconfig.lib.json
api/nest-cli.json
api/package.json
api/tsconfig.json
api/yarn.lock

Introduces FileRepository to be used within `cloning` feature (and possibly others).
Provides "local" development implementation - but may as well become "target" one.
Environment variable isn't read from existing `AppConfig` for reasons:
* duplicating json configs
* FileRepository is a library
* avoids "global" config with everything inside - focuses on per-module needs
* leverages from built-in NestJS tooling
* consider remove/unlink to be "standalone" - to avoid allowing removal of non-owned files (?) - to be discussed, who should be responsible and when this should happen (for example: add `remove` indeed to this module but each feature, like cloning, would have a wrapped storing all related files, may be even for given resource...)
* when deleting, be aware of path traversal issues …

feat(cloning): file repository

---

api/apps/api/src/migrations/api/1638358277397-AddFeatureIsCustom.ts
api/apps/api/src/modules/geo-features/geo-feature.api.entity.ts
api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/test/geo-features.e2e-spec.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts

This PR adds a new column `is_custom` to the `features` table in the API DB. This column is calculated according to whether the row has set a `project_id` or not. This column is returned as the attribute `isCustom` when requesting features, and it will allow the FE to easily sort the returned features by whether they were user imported or not.
[MARXAN-967](https://vizzuality.atlassian.net/browse/MARXAN-967)

Add is_custom calculated column to features

---

api/apps/api/src/modules/access-control/access-control.types.ts
api/apps/api/src/modules/access-control/index.ts
api/apps/api/src/modules/access-control/projects-acl/project-access-control.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.service.spec.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
api/apps/api/src/modules/blm/values/project-blm-repo.ts
api/apps/api/src/modules/projects/blm/change-blm-range.command.ts
api/apps/api/src/modules/projects/project-details.controller.ts
api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/project/delete-project.e2e-spec.ts
api/apps/api/test/project/delete-project.fixtures.ts
api/apps/api/test/project/project-get.e2e-spec.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/project/update-project-calibration.e2e-spec.ts
api/apps/api/test/project/update-project-calibration.fixtures.ts

This PR would only include basic changes made to use the ACL inside the projects-controller.
Future PRs would be apply to this one for each endpoint, so it is easier to follow and review the ACL included.

Initial setup for 1007 and projects-acl

---

api/apps/api/src/modules/access-control/projects-acl/dto/user-role-project.dto.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.controller.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
api/apps/api/test/access-control/project-acl-get.e2e-spec.ts
api/apps/api/test/access-control/project-acl.fixtures.ts

This PR implements improvements to the `GET api/v1/roles/projects/{id}/users` endpoint, as described in [MARXAN-1121](https://vizzuality.atlassian.net/browse/MARXAN-1121).
[MARXAN-1121](https://vizzuality.atlassian.net/browse/MARXAN-1121)

Improvements to get project users endpoint

---

app/layout/scenarios/edit/features/add/component.tsx
app/layout/scenarios/edit/features/component.tsx
app/layout/scenarios/edit/features/list/component.tsx

When adding/removing features from a scenario, `ScenariosFeaturesList` enters an update loop which causes performance degradation _and_ can lock up the view in certain circumstances/computers. 
The fix was implemented as follows: 
1. Moving the `Modal` handling from [`ScenariosSidebarEditFeatures`](https://github.com/Vizzuality/marxan-cloud/pull/692/files#diff-8d1bd50c9307a357124e27ccfdd79b11d5266619d8e982e1eff3c8df6c29cd57L241) to the [`ScenariosFeaturesAdd`](https://github.com/Vizzuality/marxan-cloud/pull/692/files#diff-effaabfcc4f6e69aab32945a98d86c667fd719d9e0573e7c3815de5299ef4ecdR174) component. 
By having the Modal open/close state handling in `ScenariosSidebarEditFeatures`, the whole component would be re-rendered, including the list, causing unnecessary updates and, more …

Fixing scenario features list update loop

---

app/components/forms/slider/component.stories.tsx
app/components/forms/slider/component.tsx
app/components/forms/slider/value/component.tsx
app/components/forms/slider/value/index.ts
app/styles/tailwind.css

This PR makes it so that the user can input a value for a slider directly, instead of having to drag its handle.  
In order to do so, the user can simply click on the value displayed above the thumb (hovering over it will display the "I-Beam" cursor we usually see when hovering over editable text) and input the desired value. The user can press the `Enter` key or click somewhere else to set the value, or use the `Escape` key to cancel edition. 
Verify that:  
- Clicking on a slider's value label allows you to input a value and:   
- If the value is within range (eg: protected areas threshold 0-100), it is set  
- If the value is not within the range, it will not be set  
- Pressing `Enter` when adjusting a value sets it  
- Pressing `Escape` closes the adjustment input and reverts the …

Allowing sliders' values to be editable via label [MARXAN-1153]

---

app/layout/home/partners/component.tsx

Quick fix for a missing `key` prop in the logos/partners section of the frontend
[MARXAN-1172](https://vizzuality.atlassian.net/browse/MARXAN-1172)

Fixing missing key prop in the logos/partners section of the homepage

---

app/components/scenarios/item/component.tsx
app/hooks/scenarios/index.ts
app/layout/projects/show/scenarios/component.tsx
app/layout/projects/show/scenarios/filters/component.tsx
app/layout/projects/show/scenarios/toolbar/component.tsx

This PR adds Scenario (`run`) job status filtering.  
Filtering via API is not yet available, so the filtering is done on the frontend.   
**Notes:**  
- Filtering is currently done in the respective hook, so that we have it available seamlessly throughout the app   
- The commented out modal code was kept virtually unchanged  
- The filters (only the `status` one) are not sent to the backend, as it'd return no results  
- Each scenario's run status is currently pulled from `api/v1/projects/{$projectId}/scenarios/status`, `run` job  
- The original property `status` returned by the backend is not being used, nor overwritten as one would be inclined to do. Couple reasons for this:  
- Prevent conflicts when the backend implements that property  
- The `ScenariosList` deals with all sorts …

Adding scenario status filters on the frontend

---

app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx

This PR comes to solve a problem of failure when adding or removing planning units to a scenario by uploading a file.
The problem was in the way the data was sent, so the solution has been to parse it.
[MARXAN-1182](https://vizzuality.atlassian.net/browse/MARXAN-1182)

fix(front): adjust PU by uploading[MARXAN-1182]

---

app/layout/scenarios/edit/features/add/list/component.tsx
app/layout/scenarios/edit/features/add/uploader/component.tsx

This PR contains the fix of an error related to updating all the features in the modal to add new features. It was detected that when uploading a new feature, the change was not reflected in the list unless the user closed the modal and reopened it.
[MARXAN-1189](https://vizzuality.atlassian.net/browse/MARXAN-1189)

fix(front): update features list after uploading new one[MARXAN-1189]

---

app/layout/scenarios/edit/features/list/component.tsx
app/layout/scenarios/edit/wdpa/categories/component.tsx

Those two components' forms's dispatch actions updating the store, causing other components to re-render, before the user even touching any input. 
- `WDPACategories` Component
`setWDPACategories` ended up being the culprit here. Instead of making the call inside the `render` method, we can simply use an `useEffect` hook to set the initial values on the very first render (hence the empty dependencies list). The store will then only be updated when the actual list of values changes, no matter how many times the component re-renders. 
- `ScenariosFeaturesList`   
Similar issue here, except the culprit was `setFeatures`. Setting the initial values is not needed (and will break the app). 
Create a scenario and go through the flow with the browser console open. Ensure that: …

[MARXAN-1190] Fixing bad dispatch calls in the WDPACategories and ScenariosFeaturesList forms

---

app/components/forms/slider/value/component.tsx
app/layout/scenarios/edit/wdpa/threshold/component.tsx

This PR addresses a couple of issues with the (percentage) Sliders:  
1. Sliders' labels being cut off when the slider is set at either `0%` or `100%`  
Unfortunately this is due to how the scrolling of the the component's contents (when the contents don't fit vertically) works. This requires an `overflow-hidden` in the parent components, which is effectively why these labels get hidden.
We could rework this, but this would require us setting correct paddings in all the sections manually (instead of letting the `Pill` component standardise them. 
Alternatively, we can make the sliders shorter width-wise just enough to let the labels fit, which was the step taken here. I noticed that in the _Features_ section the sliders are inset so this doesn't stray from the designs much. 
2. Sliders' …

[MARXAN-1191] Fixing sliders' issues (cut off labels, floating point errors)

---

api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
api/apps/api/test/access-control/project-acl/project-acl-get.e2e-spec.ts
api/apps/api/test/access-control/project-acl/project-acl.fixtures.ts

- Replaced the method of finding users in projects so all roles can at least see each other. 
- Adapted tests.

MARXAN-1179 All Users can view other users in private projects

---

app/layout/projects/show/scenarios/component.tsx

This PR fixes a bug introduced in https://github.com/Vizzuality/marxan-cloud/pull/740, which caused excessive padding in the Project view, when the project has no Scenarios. See screenshots below for more details. 
[MARXAN-1193](https://vizzuality.atlassian.net/browse/MARXAN-1193)
**Before:**  
**After:**

Fixing bad padding when project has no scenarios yet

---

app/layout/scenarios/edit/status/component.tsx

This PR updates the message displayed to the user while features are being processed. 
Ensure that when the loading screen appears after editing features, the text is correctly updated. This may require the Network speed to be limited with the DevTools ("Slow 3G" works well for me to test this).  
[MARXAN-1045](https://vizzuality.atlassian.net/browse/MARXAN-1045)

Changing text displayed while features are being processed

---

app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/clicking/component.tsx
app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/drawing/component.tsx
app/layout/scenarios/edit/analysis/adjust-planning-units/buttons/uploading/component.tsx
app/layout/scenarios/edit/analysis/adjust-planning-units/component.tsx

This PR mainly addresses an issue with the [ScenariosSidebarAnalysisSections](https://github.com/Vizzuality/marxan-cloud/blob/develop/app/layout/scenarios/edit/analysis/adjust-planning-units/component.tsx) component. It uses an `useEffect` hook to update all `puIncludedValue`, `puExcludedValue`, `puTmpIncludedValue`, `puTmpExcludedValue`, with `PUData` (which comes from the API) which ends up running on every render.  
However, a dispatch for any of those _will_ trigger a re-render; this is particularly problematic when the user chooses to _"Select planning units"_, the respective `AnalysisAdjustClicking` component (along with any click) will be setting `puTmpIncludedValue`, `puTmpExcludedValue` causing a loop. 
&nbsp;
The main solution implemented was to check whether the user is using …

[MARXAN-1195] Fixing adjusting planning units triggering a dispatch/render loop

---

api/apps/api/src/modules/geo-features/geo-features.service.ts

https://vizzuality.atlassian.net/browse/MARXAN-1111
The previous implementation would not restrict the set of columns queried, resulting in potentially very large response payloads from db as well as correspondingly high memory usage while parsing the result set to, essentially, only select ids.
The present change limits the select to the id column we need.

avoid fetching geo columns when not needed [MARXAN-1111]

---

api/apps/api/src/modules/countries/country.geo.entity.ts
api/apps/api/test/countries.e2e-spec.ts

https://vizzuality.atlassian.net/browse/MARXAN-1197
The missing column configuration to exclude `theGeom` from selects by default via QueryBuilder was causing operations such as plain lists of country names and ids to take way longer than they should.
The `select: false` setting was applied to the `AdminArea` entity but had not been set on the `Country` entity: this change fixes this. Raw db query goes from >1sec to <10ms with this PR (then we have node/nest overhead, but still...)

avoid fetching `theGeom` by default from db

---

api/apps/api/src/utils/postgresql.utils.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1641582332000-FixUniquenessOfPuGeoms.ts
api/apps/geoprocessing/src/modules/planning-area/planning-units-grid/planning-units-grid.processor.ts
api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
api/apps/geoprocessing/src/utils/postgresql.utils.ts

https://vizzuality.atlassian.net/browse/MARXAN-1031
Please see shapefile attached to the Jira task for validating the functionality of this PR.
In practice, any PU grid shapefile with non-regularly-shaped (e.g. square, hexagon) PUs should allow to reproduce the issue without this PR, and should be processed correctly (if within other criteria such as maximum file size, valid geometries, etc.) with this PR.

avoid index size limit when uploading custom planning unit grids from shapefile [MARXAN-1031]

---

api/apps/api/src/modules/clone/export/adapters/typeorm-export.repository.ts

This PR fixes transaction "mode" of `typeorm-export.respository`

fix: typeorm export repository transaction method

---

api/apps/api/src/modules/scenarios/locks/__mocks__/scenario-access-control.mock.ts
api/apps/api/src/modules/scenarios/locks/dto/scenario.lock.dto.ts
api/apps/api/src/modules/scenarios/locks/entity/scenario.lock.api.entity.ts
api/apps/api/src/modules/scenarios/locks/lock.service.spec.ts
api/apps/api/src/modules/scenarios/locks/lock.service.ts
api/apps/api/src/modules/scenarios/locks/scenario.lock.api.entity.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/test/project-scenarios.e2e-spec.ts

-Adds lock creation endpoint for scenarios.
-Adds tests for lock creation with different roles on a scenario.
-Minor fixes and improvements.

MARXAN-1087-endpoint-acquire-scenarios-lock

---

api/apps/api/src/modules/access-control/projects-acl/project-acl.service.spec.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.service.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.service.ts
api/apps/api/test/access-control/project-acl/project-acl-get.e2e-spec.ts
api/apps/api/test/access-control/project-acl/project-acl-patch.e2e-spec.ts
api/apps/api/test/access-control/project-acl/project-acl.fixtures.ts
api/apps/api/test/access-control/scenario-acl/scenario-acl-get.e2e-spec.ts
api/apps/api/test/access-control/scenario-acl/scenario-acl-patch.e2e-spec.ts
api/apps/api/test/access-control/scenario-acl/scenario-acl.fixtures.ts
api/apps/api/test/steps/given-user-is-created.ts
api/apps/api/test/steps/given-user-is-deleted.ts

-Filters out deleted users when getting users on project/scenarios
-Prevent changes on user roles to deleted users in projects/scenarios.
-Adds tests for them.
Couple of notes:
The ACL check when deleting a user to check that no project was left without owners is not anywhere to be found due to a cyclical dependency problem that I left in a test branch as requested by @hotzevzl

MARXAN-1154-Filter-Deleted-users

---

api/apps/geoprocessing/src/modules/surface-cost/adapters/pu-cost-extractor.spec.ts
api/apps/geoprocessing/src/modules/surface-cost/adapters/pu-cost-extractor.ts
api/apps/geoprocessing/src/modules/surface-cost/application/__mocks__/geojson.ts

This PR adds a fix for filtering pu cost negative values when updating a scenario cost surface with a shapefile
[enforce that cost data provided in cost surface uploads is zero or a positive number](https://vizzuality.atlassian.net/browse/MARXAN-1207)

fix: negative pu cost filtering

---

app/hooks/scenarios/index.ts
app/layout/scenarios/edit/analysis/blm-calibration/component.tsx

[Figma](https://www.figma.com/file/DpHfvKRBNQylK71c0nq2FD/Marxan-Visual_Internal?node-id=6727%3A12961)
[MARXAN-1259](https://vizzuality.atlassian.net/browse/MARXAN-1259)

feat(front): persist BLM range[MARXAN-1259]

---

api/apps/api/src/modules/access-control/scenarios-acl/locks/__mocks__/scenario-access-control.mock.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/dto/scenario.lock.dto.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/lock.service.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-access-control.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-locks/project-scenario-locks.e2e-spec.ts
api/apps/api/test/scenario-locks/project-scenario-locks.fixtures.ts

-Changes `PATCH /scenarios/:scenarioId/release-lock` into `DELETE /scenarios/:scenarioId/lock`.
-Changes `GET /scenarios/:scenarioId/editing-locks` payload. No more an array of every scenario lock of the parent project of the scenario. It returns either the current lock in place (`{userId, scenarioId, createdAt}`) or null if unlocked.
-Adapt e2e tests to endpoint changes.

MARXAN-1261 Requested changes for scenario locks endpoints

---

api/apps/api/src/modules/clone/import/application/complete-import-piece.command.ts
api/apps/api/src/modules/clone/infra/import/import-piece.events-handler.spec.ts
api/apps/api/src/modules/clone/infra/import/import-piece.events-handler.ts
api/apps/api/src/modules/clone/infra/import/import.infra.module.ts

This PR adds `ImportPieceEventsHandler` which is in charge of creating api events and emitting/sending `ImportPieceFailed` event/`CompleteImportPiece` command  when a `import-piece` job fails or finishes successfully

feat: import piece events handler

---

api/apps/api/src/modules/clone/import/application/complete-import-piece.handler.spec.ts
api/apps/api/src/modules/clone/import/application/complete-import-piece.handler.ts
api/apps/api/src/modules/clone/import/application/import-application.module.ts
api/apps/api/src/modules/clone/import/domain/events/piece-imported.event.ts
api/apps/api/src/modules/clone/import/domain/import/import.ts

This PR adds: 
- `CompleteImportPieceHandler` which is executed when a `CompleteImportPiece` command is dispatched. `CompleteImportPieceHandler` completes the piece transactionally so there are not concurrency issues when completing the pieces of the import.

feat: complete import piece handler

---

api/apps/api/src/modules/access-control/projects-acl/project-acl.controller.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/__mocks__/scenario-access-control.mock.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-access-control.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.controller.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/src/utils/acl.utils.ts
api/apps/api/test/access-control/project-acl/project-acl.fixtures.ts
api/apps/api/test/access-control/scenario-acl/scenario-acl.fixtures.ts
api/apps/api/test/project-scenarios.e2e-spec.ts
api/apps/api/test/scenario-locks/project-scenario-locks.e2e-spec.ts

-Adds new lock logic check into every POST/PATCH/DELETE endpoint. Uses a flag for DELETE.
-Implements poor person's version of LOFU (Lock on first use)
-Adapts tests where needed for this new logic check, though with LOFU this would not be as needed as before.
-Refactors `aclErrorHandler` to address every type of error needed for `scenarios.controller` using exhaustive pattern (maybe the name should be changed into just  `errorHandler` or `exhaustiveErrorHandler`?).

MARXAN-1237-scenarioLocks-on-all-endpoints

---

api/apps/api/src/migrations/api/1645026803969-AddTokenIdColumnToLocks.ts
api/apps/api/src/modules/access-control/access-control.module.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.module.ts
api/apps/api/src/modules/access-control/projects-acl/project-acl.service.spec.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/entity/scenario.lock.api.entity.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/lock.service.spec.ts
api/apps/api/src/modules/access-control/scenarios-acl/locks/lock.service.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.module.ts
api/apps/api/src/modules/access-control/scenarios-acl/scenario-acl.service.spec.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/test/projects.e2e-spec.ts
api/apps/api/test/scenario-locks/project-scenario-locks.e2e-spec.ts
api/apps/api/test/scenario-locks/project-scenario-locks.fixtures.ts

-Adds migration to add a `token_id` column for  `lock` entity.
-Assigns expiration to lock based on expiration of token (on a ON CASCADE DELETE relationship between entities)
-Adds tests to check that lock is effectively removed when user token expires.

MARXAN-1091-lock-expiration-userToken

---

app/layout/loading/component.tsx
app/layout/loading/index.ts
app/layout/projects/show/map/component.tsx
app/layout/projects/show/scenarios/component.tsx
app/package.json
app/pages/_app.tsx
app/yarn.lock

This PR adds:
- nprogress
- react-nprogress

Page progress bar

---

api/apps/api/src/migrations/api/1645026803969-AddTokenIdColumnToLocks.ts
api/apps/api/test/scenario-locks/project-scenario-locks.e2e-spec.ts

This is so we don't risk running into a constraint violation when adding a FK reference later in the migration.
There should really be no "active" users by the time this migration runs, as there is no production environment yet, and LOFU should help the few developers and test users to keep their sessions running smoothly nevertheless.
I am not sure how wise it is to use an Unicode emoji in a PostgreSQL comment, but apparently we'll be fine with this 😇.

forcibly release all locks active at the time of migration [MARXAN-1091]

---

app/hooks/features/index.ts

Checking whether `properties` is defined here is just a workaround to avoid an error when processing `bioregional` features, which would prevent progressing through the stop of configuring features for a scenario until this code is reviewed.
Without much knowledge of the flow for feature data, I see that short-circuiting the `map()` below and therefore setting `splitOptions = []` still results in properties being shown in the dropdowns used for splitting features, but since `properties` is always undefined (from what I can see), we may need to adapt the API payload or how we process it here.
On the other hand: I started experiencing this error after loading the latest data dump (which now includes bioregional data) locally, however the app without the change in this PR and using m49 as …

temporary workaround for error when loading bioregional features

---

api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenarios/update-scenario.e2e-spec.ts

This PR addresses an issue in `ScenariosService` where `blockGuard.ensureThatProjectIsNotBlocked` calls were being made instead of `blockGuard.ensureThatScenarioIsNotBlocked`

fix: wrong block guard usage in scenarios service

---

api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom.piece-exporter.ts
api/libs/cloning/src/infrastructure/clone-piece-data/planning-area-custom.ts

This PR adds `planning-area-custom` piece exporter
[PieceExportProvider - PlanningAreaCustom](https://vizzuality.atlassian.net/browse/MARXAN-1149)

feat: planning area custom piece exporter

---

api/apps/api/src/migrations/api/1645440886194-PlatformAdmins.ts
api/apps/api/src/modules/users/platform-admin/admin.api.entity.ts
api/apps/api/src/modules/users/users.controller.ts
api/apps/api/src/modules/users/users.module.ts
api/apps/api/src/modules/users/users.service.ts
api/apps/api/test/fixtures/test-data.sql
api/apps/api/test/project-scenarios.e2e-spec.ts
api/apps/api/test/users.e2e-spec.ts

-Adds migration to introduce platform admins table.
-Adds Endpoints to get, create and delete admins.
-Adds tests for admins, refactors user-e2e-tests to fit GWT pattern.

MARXAN-1020-platformAdmins

---

.github/workflows/publish-postgres-docker-image.yml
README.md
api/apps/geoprocessing/src/app.module.ts
api/apps/geoprocessing/src/modules/ping/ping.controller.spec.ts
api/apps/geoprocessing/src/modules/ping/ping.controller.ts
infrastructure/main.tf
infrastructure/modules/container-registry/main.tf
infrastructure/modules/kubernetes/main.tf
infrastructure/modules/kubernetes/variables.tf
infrastructure/modules/network/main.tf
infrastructure/modules/network/outputs.tf
infrastructure/modules/node_pool/main.tf
kubernetes/main.tf
kubernetes/modules/database/main.tf
kubernetes/modules/geoprocessing/main.tf
kubernetes/modules/geoprocessing/variable.tf
kubernetes/modules/geoprocessing/versions.tf
kubernetes/modules/ingress/main.tf
kubernetes/modules/ingress/variable.tf
kubernetes/modules/ingress/versions.tf
kubernetes/modules/secrets/main.tf

Api deployment

---

api/apps/api/src/modules/planning-units-protection-level/calculate-planning-units-protection-level.handler.ts
api/apps/api/src/modules/scenarios/protected-area/selection/selection-change.module.ts
api/apps/api/src/modules/scenarios/protected-area/selection/selection-update.service.integration.spec.ts
api/apps/api/src/modules/scenarios/protected-area/selection/selection-update.service.ts

https://vizzuality.atlassian.net/browse/MARXAN-1316
We did originally fire the event changed in this PR in `CalculatePlanningUnitsProtectionLevelHandler.execute()`, however this would be *after* some potentially expensive SQL queries had been run in `ScenarioPlanningUnitsProtectedStatusCalculatorService.calculatedProtectionStatusForPlanningUnitsIn()`,
which would lead is some cases to a very long delay between the time an API user submits a request for `POST /api/scenarios/:id/protected-areas` and the time a `scenario.planningAreaProtectedCalculation.submitted/v1/alpha` event shows up in the scenario status data.
However, as we're moving the firing of this event across a couple of cqrs event boundaries, I am less confident that we would consistently fire a `finished` or `failed` event …

fire scenario.planningAreaProtectedCalculation.submitted much earlier [MARXAN-1316]

---

webshot/Dockerfile

`dist` is generated while building the Docker image, definitely not carried over from the build context (where it is, alas, gitignored), so `COPY`ing is nonsense. Apologies.

remove nonsense COPY from Dockerfile

---

api/apps/api/src/modules/clone/import/application/export-config-reader.spec.ts
api/apps/geoprocessing/src/export/pieces-exporters/export-config.project-piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/export-config.scenario-piece-exporter.ts
api/libs/cloning/src/infrastructure/clone-piece-data/export-config.ts

This PR adds new check within the validation process of the export config file. Now the version of the export saved inside the exported config file must equal the version of the system

feat: add version check to export config validation process

---

api/apps/geoprocessing/src/export/pieces-exporters/export-config.project-piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/export-config.scenario-piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.piece-exporter.spec.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-metadata.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-metadata.piece-exporter.ts

This PR adds error messages logs within exporters pieces. Other possible solution could be to log the error in `handleFailed` method of `QueueEventsAdapter` class, but this would affect all async jobs that are being handled with this class.

feat: add logger error messages to piece exporters

---

api/apps/api/src/migrations/api/1645550554581-ImplicitRolesFunctionsAndTriggers.ts
api/apps/api/src/modules/access-control/scenarios-acl/entity/users-scenarios.api.entity.ts
api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
api/apps/api/test/implicit-permissions/implicit-permissions.e2e-spec.ts
api/apps/api/test/implicit-permissions/implicit-permissions.fixtures.ts
api/apps/api/test/project-scenarios.e2e-spec.ts

-Adds migration to include triggers on `users_projects` changes and `scenarios` creation.
-Tweaks some differences in tests due to not-slightly-accurate test data.
-Changes columns definition in `user-scenarios` API entity to avoid duplicate key errors.
-Tests for implicit-permissions. [WIP]

Marxan 1164 implicit permissions

---

api/apps/geoprocessing/test/integration/planning-areas/custom-planning-area.repository.e2e-spec.ts
api/libs/planning-area-repository/src/custom-planning-area.repository.ts

This PR fixes inconsistent `project_id` in `planning_areas` table value when uploading planning area. Now the id of the newly planning area and its associated project_id are the same.

fix: add fake project id to planning area when uploading planning area

---

api/apps/api/config/custom-environment-variables.json
api/apps/api/src/main.ts
api/apps/api/src/modules/access-control/scenarios-acl/entity/users-scenarios.api.entity.ts
api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/uploads/upload-limits.ts

https://vizzuality.atlassian.net/browse/MARXAN-1194
Includes some lightweight refactor to use MiB as measurement unit - we won't need finer resolution (e.g. bytes) and using MiBs should, on the other hand, improve legibility of these bits of code.

make JSON payload size limit configurable for endpoint that allows setting planning unit lock status [MARXAN-1194]

---

api/apps/geoprocessing/src/export/pieces-exporters/scenario-metadata.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-metadata.ts

This PR adds marxan settings export and import implementation. `ScenarioMetadataPieceExporter` adds `metadata`, `blm` and `number_of_runs` columns of `scenarios` table to `ScenarioMetadataContent` (file content of `scenario-metadata` clone piece) allowing `ScenarioMetadataPieceImporter` to import this data easily
- [export piece (scenario): marxan settings](https://vizzuality.atlassian.net/browse/MARXAN-1352)
- [import piece (scenario): marxan settings](https://vizzuality.atlassian.net/browse/MARXAN-1353)

feat: export/import marxan settings

---

api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom-geojson.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-units-grid-geojson.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-units-grid.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-custom-protected-areas.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-metadata.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-planning-units-data.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-protected-areas.piece-exporter.ts
api/libs/cloning/src/infrastructure/clone-piece-data/planning-area-custom.ts
api/libs/cloning/src/infrastructure/clone-piece-data/planning-area-gadm.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-protected-areas.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-metadata.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-metadata.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-planning-units-data.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-protected-areas.ts

This PR adds piece exporter for `ScenarioPlanningUnitsData` `ClonePiece`. Scenario planning units data is composed by the following items:
- lock status
- cost
- feature list
- protected area percentage and if it is protected by default
- [export piece (scenario): lock status (locked by default, or manually locked in or out) per planning unit](https://vizzuality.atlassian.net/browse/MARXAN-1350)
- [export piece (scenario): cost data per planning unit](https://vizzuality.atlassian.net/browse/MARXAN-1348)

feat: scenario planning units data piece exporter

---

api/apps/geoprocessing/src/export/pieces-exporters/project-metadata.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-protected-areas.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/planning-area-custom.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/planning-area-gadm.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/planning-units-grid.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts
api/apps/geoprocessing/test/integration/clonning/planning-units-grid.piece-importer.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-metadata.ts

This PR fixes `PlanningUnitsGrid` piece importer and `ScenarioProtectedAreas` piece exporter:
- `PlanningUnitsGridPieceImporter` was not taking into consideration the type of planning units geometries . It was setting `FromShapefile` by default. `type` column of `planning_units_geom` table was containing incorrect values for that reason
- `ScenarioProtectedAreasPieceExporter` was not working when array of protected areas ids was empty (PostgreSQL `IN` operator doesn't support empty arrays)
- `ProjectMetadataContent` now contains the type of planning units geometries. `PlanningAreaGadmPieceImporter` and `PlanningAreaCustomPieceImporter` no longer updates this field of `projects` table.

fix: planning units grid piece importer and scenario protected areas piece exporter

---

api/apps/api/src/modules/published-project/controllers/publish-project.controller.ts
api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/published-project/published-project.service.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/project/public-projects.e2e-spec.ts

-Adds endpoint for `project_owners` to unpublish a public project.
-Adds conditions to when clearing a project from under moderation to be able to outright unpublish the project straightaway.
-Adds tests for the new endpoint and changes in the workflow.
Depends on #896 being closed beforehand.

MARXAN-1380-unpublish-public-project

---

api/apps/geoprocessing/src/export/pieces-exporters/scenario-run-results.piece-exporter.ts

This PR fixes a problem detected when exporting scenario run results of a scenario. Now, scenario run results file will have an empty array in case no Marxan run has been executed in the scenario.

fix :scenario run results piece exporter

---

webshot/Dockerfile

The default used by Puppeteer would not allow to render webgl stuff in
headless mode, so for the time being we're switching to Node/Ubuntu
images and installing Chrome from Google's APT sources.
https://vizzuality.atlassian.net/browse/MARXAN-1404

use Chrome as headless browser

---

api/apps/api/src/modules/projects/project.api.entity.ts
api/apps/geoprocessing/src/import/pieces-importers/planning-area-custom.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/planning-area-gadm.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts

This PR refactors some piece importers to use query builders instead of `query` method of `EntityManager`s

ref: use of query builder in piece importers

---

api/apps/geoprocessing/src/export/pieces-exporters/export-config.project-piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/export-config.scenario-piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom-geojson.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-custom.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.piece-exporter.spec.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-area-gadm.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-units-grid-geojson.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/planning-units-grid.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-metadata.piece-exporter.ts

This PR refactors some part exporters that used the entityManager query method, now these queries have been replaced by using queryBuilder methods.

ref: use query builder in piece exporters

---

api/apps/api/src/modules/clone/import/application/import-application.module.ts
api/apps/api/src/modules/clone/import/application/import-scenario.command.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.spec.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.ts

This PR adds `ImportScenario` command and it's corresponding command handler: `ImportScenarioHandler`

feat: import scenario command and handler

---

api/apps/api/src/modules/clone/infra/export/export-piece.events-handler.ts
api/apps/api/src/modules/clone/infra/export/mark-export-as-failed.handler.ts
api/apps/api/src/modules/clone/infra/import/import-piece.events-handler.ts
api/apps/api/src/modules/geo-features/processing/run.service.ts
api/apps/api/src/modules/scenarios-features/intersect-with-pu/intersect-with-pu.handler.ts
api/apps/api/src/modules/scenarios/blm-calibration/blm-calibration-events.service.ts
api/apps/api/src/modules/scenarios/blm-calibration/start-blm-calibration.handler.ts
api/apps/api/src/modules/scenarios/marxan-run/run.handler.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
api/apps/api/src/modules/scenarios/protected-area/protected-area.service.ts

https://vizzuality.atlassian.net/browse/MARXAN-1367
using BullMQ job ids to assemble `externalId` values for API events may lead to FK constraint violations as these job ids cannot be guaranteed to be forever monotonic.
This PR removes the use of `externalId` altogether for one kind of API events where this should not be needed, and adds `@todo` annotations to remove the dependency on job ids in other relevant code paths.

avoid possible fk constraint violations

---

api/apps/api/src/migrations/api/1648640687600-CreateFeaturesUniqueIndexes.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1648641020335-AddFeaturesHashColumn.ts
api/apps/geoprocessing/test/integration/marxan-run/blm-calibration-run.e2e-spec.ts
api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts

This PR adds the changes required to be able to export/import features and features data
[refactor project/scenario/feature linking](https://vizzuality.atlassian.net/browse/MARXAN-1405)

ref: project/scenario/feature linking

---

api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-features-data.piece-exporter.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-features-data.ts
api/libs/features/src/scenario-features-data.geo.entity.ts
api/libs/features/src/scenario-features-preparation.geo.entity.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts

This PR adds piece exporter for `ClonePiece.ScenarioFeaturesData`
[export piece (scenario): scenario features data](https://vizzuality.atlassian.net/browse/MARXAN-1413)

feat: scenario features data piece exporter

---

api/apps/api/src/modules/scenarios/blm-calibration/start-blm-calibration.command.ts
api/apps/api/src/modules/scenarios/blm-calibration/start-blm-calibration.handler.ts
api/apps/api/src/modules/scenarios/dto/start-scenario-blm-calibration.dto.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenarios/get-scenario-blm-calibration-results.fixtures.ts
api/apps/api/test/scenarios/get-scenario-blm-range.e2e-spec.ts
api/apps/api/test/scenarios/start-scenario-calibration.fixtures.ts
api/apps/geoprocessing/config/default.json
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-final-results.repository.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/blm-run-adapter.module.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/marxan-sandbox-blm-runner.service.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1648559688744-AddProtectedPUIdsPngColumnToBlmFinalResults.ts
api/apps/geoprocessing/src/modules/scenarios/scenarios.controller.ts
api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts
api/apps/geoprocessing/test/integration/marxan-run/blm-calibration-run.e2e-spec.ts
api/apps/geoprocessing/test/jest-e2e.json
api/libs/blm-calibration/src/blm-final-results.geo.entity.ts
api/libs/blm-calibration/src/calibration-job-input.ts
api/libs/webshot/src/index.ts
api/libs/webshot/src/webshot.dto.ts
api/libs/webshot/src/webshot.service.ts

-Adds a migration for the new two columns in `blm_final_results` table: `protected_pu_ids` and `png_data`.
-Adds new columns in entity to be used in update method on `blm_final_results` repo.
WIP: Sending png generation request to webshot-service + tile generation endpoint. Tests.

MARXAN-1374-BLMFinalResults-Puids-PNGdata

---

api/apps/api/src/modules/clone/import/application/import-project.command.ts
api/apps/api/src/modules/clone/import/application/import-project.handler.spec.ts
api/apps/api/src/modules/clone/import/application/import-project.handler.ts
api/apps/api/src/modules/clone/import/application/import-scenario.command.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.spec.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.ts
api/apps/api/src/modules/projects/dto/import.project.response.dto.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.service.ts

This PR adds `projectId` property to import project endpoint response
[Include id of new (cloned/imported) project in the response of POST /api/v1/projects/import](https://vizzuality.atlassian.net/browse/MARXAN-1444)

feat: include id of imported project in the response

---

infrastructure/kubernetes/main.tf
infrastructure/kubernetes/modules/api/main.tf
infrastructure/kubernetes/modules/api/variable.tf
infrastructure/kubernetes/modules/geoprocessing/main.tf
infrastructure/kubernetes/modules/geoprocessing/variable.tf
infrastructure/kubernetes/modules/key_vault/variable.tf
infrastructure/kubernetes/modules/storage/main.tf
infrastructure/kubernetes/modules/storage/variable.tf
infrastructure/kubernetes/modules/storage/versions.tf
infrastructure/kubernetes/modules/volumes/main.tf
infrastructure/kubernetes/modules/volumes/variable.tf
infrastructure/kubernetes/modules/volumes/versions.tf
infrastructure/kubernetes/variables.tf

https://vizzuality.atlassian.net/browse/MARXAN-1428

add k8s_storage module with initial storage class for Azure Files CSI over NFS [MARXAN-1428]

---

api/apps/api/src/migrations/api/1649665709084-AddClonePieceForMarxanExecutionMetadata.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
api/apps/api/src/modules/clone/import/adapters/import-resource-pieces.adapter.ts
api/apps/geoprocessing/src/export/pieces-exporters/marxan-execution-metadata.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/test/integration/clonning/fixtures.ts
api/apps/geoprocessing/test/integration/clonning/marxan-execution-metadata.piece-exporter.e2e-spec.ts
api/libs/cloning/src/domain/clone-piece.ts
api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
api/libs/cloning/src/infrastructure/clone-piece-data/marxan-execution-metadata.ts

This PR adds `ClonePiece.MarxanExecutionMetadata` piece exporter
[export piece (scenario): marxan execution metadata](https://vizzuality.atlassian.net/browse/MARXAN-1449)

feat: export marxan execution metadata

---

api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/marxan-sandbox-blm-runner.service.ts
api/apps/geoprocessing/test/integration/marxan-run/blm-calibration-run.e2e-spec.ts

-Changes how projectId is taken for the webshot service.
-Refactors blm-calibration test in geoprocessing due to mocked projectId/scenarioId not existant in API DB.

BLM-image-url-errors-add-project-metadata

---

api/apps/geoprocessing/src/export/pieces-exporters/marxan-execution-metadata.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/marxan-execution-metadata.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
api/apps/geoprocessing/test/integration/clonning/marxan-execution-metadata.piece-importer.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/marxan-execution-metadata.ts
api/libs/utils/src/index.ts
api/libs/utils/src/zip-file-extractor.ts

This PR adds `ClonePiece.MarxanExecutionMetadata` piece importer
[import piece (scenario): marxan execution metadata](https://vizzuality.atlassian.net/browse/MARXAN-1475)

feat: import marxan execution metadata

---

api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/users/users.controller.ts
api/apps/api/src/modules/users/users.service.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/geoprocessing/src/modules/scenarios/scenarios.service.ts

-Adds query search for users endpoint, also adds isAdmin check to prevent users from being seen by regular users.
-Adds metadata and publicMetadata to project JSONAPI serializer.
-Fix tiles DB request failing because missing escaped param.

Project-metadata-publicMetadata-isAdminEndpoints

---

api/apps/api/src/modules/projects/dto/export.project.dto.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/project/get-latest-export.e2e-spec.ts

This PR adds the id of the user who launched the export to the response of get latest export endpoint
[return userId on API endpoint GET /api/v1/projects/{projectId}/export](https://vizzuality.atlassian.net/browse/MARXAN-1476)

feat: return user id on get latest export endpoint

---

api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/users/user-requests-info.ts
api/apps/api/src/modules/users/users.service.ts

-Implements search for publishedProjects and users GET endpoints by admin.
-Implements option to add originalProject into PublishedProject information.

implements-search-users-PublishedProjects

---

api/apps/api/src/modules/clone/export/application/export-application.module.ts
api/apps/api/src/modules/clone/export/application/export-scenario.handler.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/piece-importers/scenario-metadata.piece-importer.e2e-spec.ts

This PR edits how `scenario-metadata` piece is exported/imported. Scenarios being cloned are now created at export scenario command handler level. With these changes, frontend will be able to query the status of the cloning process after receiving the response of clone endpoint
[modify scenario metadata piece importer/exporter to take into account cloning processes](https://vizzuality.atlassian.net/browse/MARXAN-1480)

feat: scenario cloning adjustments

---

api/apps/geoprocessing/config/custom-environment-variables.json
api/apps/geoprocessing/config/default.json

Initial workaround (only) for https://vizzuality.atlassian.net/browse/MARXAN-1491

add api config items to geoprocessing service [MARXAN-1490]

---

api/apps/api/src/migrations/api/1650619314086-AddLocationPngDataPublicProject.ts
api/apps/api/src/modules/published-project/dto/create-published-project.dto.ts
api/apps/api/src/modules/published-project/dto/publish-project.dto.ts
api/apps/api/src/modules/published-project/entities/published-project.api.entity.ts
api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/published-project/published-project.module.ts
api/apps/api/src/modules/published-project/published-project.service.ts
api/apps/api/test/fixtures/test-data.sql
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/project/public-projects.e2e-spec.ts
api/libs/webshot/src/webshot.service.ts
webshot/src/domain/published-project-maps/published-projects-maps.ts
webshot/src/main.ts

-Adds screenshot generation to publish action.
-Adds new location field to published project entity.
-Adapts tests to new fields.
-Minor removal of redundant fixture data.

MARXAN-1274-publicMap-screenshot

---

api/apps/api/src/modules/published-project/controllers/publish-project.controller.ts
api/apps/api/src/modules/published-project/dto/publish-project.dto.ts
api/apps/api/src/modules/published-project/published-project.service.ts

-Adds missing cookie for the webshot service to access the tile map.
-Refactors how DTO are set for published project creation / update.

MARXAN-1274-published-Project-image-webshot-cookie

---

api/apps/api/src/migrations/api/1650984916463-AddsExportIdToPublicProject.ts
api/apps/api/src/modules/published-project/controllers/publish-project.controller.ts
api/apps/api/src/modules/published-project/dto/create-published-project.dto.ts
api/apps/api/src/modules/published-project/dto/publish-project.dto.ts
api/apps/api/src/modules/published-project/entities/published-project.api.entity.ts
api/apps/api/src/modules/published-project/published-project.module.ts
api/apps/api/src/modules/published-project/published-project.service.ts

-Adds exportId column to public project.
-Creates export everytime a project is sent to publish.

MARXAN-1494-exportId-public-project

---

.github/workflows/deploy-to-kubernetes.yml

This change should allow the configured `sed` regexp replacement to work irrespective of the Azure zone the AKS API is in.
Assuming that the part of hostname for zones is always going to be alphanumeric. Maybe "anything but a `.`" maybe more resilient? I think alphanumeric should be good enough for the time being, without being overly permissive.

update regexp match to ignore azure zone URL hostname part

---

api/apps/api/src/modules/published-project/controllers/publish-project.controller.ts
api/apps/api/src/modules/published-project/dto/create-published-project.dto.ts
api/apps/api/src/modules/published-project/dto/publish-project.dto.ts
api/apps/api/src/modules/published-project/dto/update-published-project.dto.ts
api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/published-project/published-project.service.ts
api/apps/api/src/utils/webshot.utils.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/project/public-projects.e2e-spec.ts

-Adds PATCH endpoint to update public projects.
-Refactors how webshot is called from public projects actions for scenario snapshot generation.
-Adds basic tests for this new endpoint.

MARXAN1498-public-project-patch-endpoint

---

api/apps/api/src/bootstrap-app.ts
webshot/src/utils/passthrough-console.utils.ts

https://vizzuality.atlassian.net/browse/MARXAN-1406
The whitelisting of specific headers was an historical artifact inherited from earlier NestJS setups, but in practice, I don't think we need to be so picky with request headers as long as we whitelist origins correctly, as we seem to be doing.
Somehow, the previous setup was working correctly for the frontend app, except when this is puppeteered via the webshot service.

remove allowedHeaders whitelisting [MARXAN-1406]

---

api/apps/api/src/modules/clone/export/adapters/memory-export.repository.ts
api/apps/api/src/modules/clone/export/application/export-project.handler.spec.ts
api/apps/api/src/modules/clone/export/application/get-archive.handler.ts
api/apps/api/src/modules/clone/export/application/get-archive.query.ts
api/apps/api/src/modules/clone/export/domain/export/export.ts
api/apps/api/src/modules/clone/import/application/import-project.command.ts
api/apps/api/src/modules/clone/import/application/import-project.handler.ts
api/apps/api/src/modules/clone/import/application/import-scenario.command.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.ts
api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/src/utils/acl.utils.ts
api/apps/api/test/project/import-project.e2e-spec.ts

This PR refactors how is checked if an export has finished, if an export is a cloning export and if an export is a foreign export

ref: export aggregate

---

api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/modules/published-project/published-project.module.ts
api/apps/api/src/modules/published-project/published-project.service.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/project/public-projects.e2e-spec.ts

-Add conditions on findAll/findOne methods in public projects to avoid showing exportId when it is not ready.
-Add specific test to check that exportId is shown if export is finished.

Public-Projects-ExportId-Switch

---

api/apps/api/src/modules/access-control/role.api.entity.ts
api/apps/api/src/modules/clone/export/application/export-application.module.ts
api/apps/api/src/modules/clone/export/application/export-project.handler.spec.ts
api/apps/api/src/modules/clone/export/application/export-project.handler.ts
api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts

This PR adds logic for giving the user `project_owner` role immediately after a project shell is created when cloning is scheduled
[project shell not being returned in the list of projects after starting a cloning process](https://vizzuality.atlassian.net/browse/MARXAN-1528)

fix: project shell visibility

---

api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
api/apps/geoprocessing/test/e2e.config.ts
api/apps/geoprocessing/test/planning-units-processor.e2e-spec.ts

This PR fixes the size calculation of hexagon grids
[fix regular planning units size calculation](https://vizzuality.atlassian.net/browse/MARXAN-1529)

fix: size calculation for hexagon grids

---

api/apps/geoprocessing/src/export/pieces-exporters/scenario-run-results.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-run-results.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/scenario-run-results.piece-exporter.e2e-spec.ts
api/apps/geoprocessing/test/integration/cloning/piece-importers/scenario-run-results.piece-importer.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-run-results.ts

This PR adds `output_scenarios_summaries` data to cloning process
[BE - export/import/clone solutions data missing](https://vizzuality.atlassian.net/browse/MARXAN-1535)

fix: output scenarios summaries cloning

---

app/layout/scenarios/edit/parameters/blm-calibration/chart/component.tsx
app/layout/scenarios/edit/parameters/blm-calibration/results/component.tsx

[MARXAN-1392](https://vizzuality.atlassian.net/browse/MARXAN-1392)
---

fix(front): BLM chart improvements [MARXAN-1392]

---

app/hooks/admin/index.ts
app/layout/admin/published-projects/table/cells/email/component.tsx
app/layout/admin/published-projects/table/cells/email/index.ts
app/layout/admin/published-projects/table/component.tsx

- Please, test with `Miguel-test project` as it has actually three owners and check if emails match with names and are showing in same order.
[MARXAN-1547](https://vizzuality.atlassian.net/browse/MARXAN-1547)

feat(front): add emails to admin panel [MARXAN-1547]

---

api/apps/api/src/modules/queue/queue-options.provider.ts
api/apps/api/src/modules/queue/queue.module.ts
api/apps/api/src/utils/redisConfig.utils.ts
api/apps/api/test/scenario-cost-template/bull-mq-integration.e2e-spec.ts
api/apps/geoprocessing/src/modules/worker/queue-events.builder.ts
api/apps/geoprocessing/src/modules/worker/worker-builder.ts
api/apps/geoprocessing/test/integration/marxan-run/run-worker.e2e-spec.ts
api/apps/geoprocessing/test/worker-module/worker-module-di-usage.e2e-spec.ts
api/apps/geoprocessing/test/worker-module/worker-module-usage.e2e-spec.ts
api/libs/utils/src/bullmq/queue-namespacing.ts
api/libs/utils/src/index.ts

https://vizzuality.atlassian.net/browse/MARXAN-1566

allow to share a single redis db between MarxanCloud instances

---

app/layout/scenarios/edit/parameters/blm-calibration/component.tsx

We still have the input arrows that are seen in Firefox but I have decided to leave them that way so as not to influence the rest of the project or insert css classes
[MARXAN-1571](https://vizzuality.atlassian.net/browse/MARXAN-1571)

fix(front): remove firefox blm input margin [MARXAN-1571]

---

app/layout/guide-request/component.tsx

Instead of adding a new modal size, I decreased the size of the icon and reduced the margins between the elements of the guidance modal.
[MARXAN-1539](https://vizzuality.atlassian.net/browse/MARXAN-1539)

fix(front): guidance modal [MARXAN-1539]

---

api/apps/api/src/modules/clone/export/application/export-scenario.handler.ts

This PR adds `metadata` property to scenario shell when cloning a scenario

ref: add metadata to scenario shell

---

api/apps/api/src/modules/clone/export/application/finalize-archive.handler.ts
api/apps/api/src/modules/clone/export/domain/export/export.id.ts
api/apps/api/src/modules/clone/infra/export/export-piece-failed.saga.ts
api/apps/api/src/modules/clone/infra/export/mark-export-as-failed.command.ts
api/apps/api/src/modules/clone/infra/export/mark-export-as-failed.handler.ts
api/libs/cloning/src/domain/component.id.ts

This PR adds `reason` property to export failed api events
[Download project doesn't seem to work](https://vizzuality.atlassian.net/browse/MARXAN-1583)
When reviewing api events for the project of the issue we found that we were not storing the reason of the export failed api event. All piece exporters succeeded but an export failed api event was being emitted.

fix: added export failed api event reason

---

api/apps/api/src/modules/legacy-project-import/application/legacy-project-import-requested.saga.ts
api/apps/api/src/modules/legacy-project-import/application/legacy-project-import.application.module.ts
api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-as-submitted.command.ts
api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-as-submitted.handler.ts

This PR adds `LegacyProjectImportRequestedSaga`
[Implement LegacyProjectImportRequested saga](https://vizzuality.atlassian.net/browse/MARXAN-1562)

feat: legacy project import requested saga

---

api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-piece-as-failed.command.ts
api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-piece-as-failed.handler.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import-component.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
api/apps/api/src/modules/legacy-project-import/infra/import-legacy-project-piece.events-handler.ts
api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import.infra.module.ts
api/apps/api/src/modules/queue-api-events/adapter.ts

This PR adds logic for properly setting `errors` values of `LegacyProjectImportPieceComponent`s when a legacy project import piece job fails.
[Set proper errors and warnings values for MarkLegacyProjectImportPieceAsFailed command when a import legacy project piece job fails](https://vizzuality.atlassian.net/browse/MARXAN-1559)

feat: set proper errors when a job fails

---

api/apps/api/src/migrations/api/1653474952888-CreateProjectSourcesEnum.ts
api/apps/api/src/modules/legacy-project-import/application/start-legacy-project-import.handler.ts
api/apps/api/src/modules/projects/project.api.entity.ts
api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts

-Adds migration to add `sources` column and enum type to `projects` table.

MARXAN-1609-projects-sources-column

---

api/apps/api/src/modules/clone/export/adapters/memory-export.repository.ts
api/apps/api/src/modules/clone/import/application/import-scenario.handler.spec.ts
api/apps/api/src/modules/geo-features/geo-feature-property-sets.service.ts
api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-piece-as-failed.command.ts
api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-piece-as-failed.handler.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import-component.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
api/apps/api/src/modules/legacy-project-import/infra/import-legacy-project-piece.events-handler.ts
api/apps/api/src/modules/legacy-project-import/infra/legacy-project-import.infra.module.ts
api/apps/api/src/modules/queue-api-events/adapter.ts
api/apps/api/src/utils/json.type.ts
api/apps/api/test/fixtures/test-init-apidb.sql
api/apps/geoprocessing/src/migrations/geoprocessing/1653565019335-ModifyBboxCalculationTakingAntimeridian.ts
api/apps/geoprocessing/src/modules/admin-areas/admin-areas.service.ts
api/apps/geoprocessing/src/modules/features/features.service.ts
api/apps/geoprocessing/src/modules/planning-area/planning-area-tiles/planning-area-tiles.service.ts
api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
api/apps/geoprocessing/src/modules/planning-units/planning-units.service.ts
api/apps/geoprocessing/src/modules/protected-areas/protected-areas-tiles.service.ts
api/apps/geoprocessing/src/modules/scenarios/comparison-difference-tile/comparison-difference-tile.service.ts
api/apps/geoprocessing/src/utils/bbox.utils.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/export-config.project-piece-exporter.e2e-spec.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/scenario-protected-areas.piece-exporter.e2e-spec.ts
api/libs/utils/src/geo/bbox.ts
api/libs/utils/src/geo/index.ts

This fix is touching almost all intersections based on bbox in the application
So this applies 2 different fixes altogether:
BBox crosses the antimeridian, we are overpassing this in 2 steps, first, we properly calculate min and max longitude values by dividing the bbox in 2 bases on the east and west semihemisphers. 
After that both FE and backend will follow the next rule: if min long is > than max long, that means that the bbox crosses the antimeridian and we subdivide them.
Regarding the grid. So as we are already setting the equal area cost surface, I did take the license to every grid that is crossing the antimeridian will be cut in order to avoid it crossing the antimeridian. with this in place calculations should work as expected.
Also, small fixes were applied to everything that …

Antimeridian and bbox calc fix

---

api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-blm/asset-factory.service.ts
api/apps/geoprocessing/src/modules/features/features.service.ts

https://vizzuality.atlassian.net/browse/MARXAN-1628
- replace `fs-extra.copySync()` with `child_process.execSync('cp ...')` to avoid permissions issues with k8s volumes (and to avoid having to depend on specific mount options)

avoid uncaught error on nfs warnings on copy in k8s [MARXAN-1628]

---

api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features-specification.legacy-piece-importer.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features.legacy-piece-importer.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.comma-or-tab-finder.spec.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.comma-or-tab-finder.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.delimiter-finder.fake.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/dat-file.delimiter-finder.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/file-readers/file-readers.module.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/scenarios-pus-data.legacy-piece-importer.ts
api/apps/geoprocessing/test/integration/legacy-project-import/features-specification.legacy-piece-importer.e2e-spec.ts
api/apps/geoprocessing/test/integration/legacy-project-import/features.legacy-piece-importer.e2e-spec.ts
api/apps/geoprocessing/test/integration/legacy-project-import/scenarios-pus-data.legacy-piece-importer.e2e-spec.ts

This PR adds `DatFileDelimiterFinder` service and adapts legacy importers so they can read dat files using commas and tabs as delimiters 
[Support tabs and commas as delimiters when reading dat files](https://vizzuality.atlassian.net/browse/MARXAN-1639)

add dat file delimiter finder service and adapt legacy importers 

---

api/apps/api/src/migrations/api/1655459736009-AddBackgroundColumnsToUser.ts
api/apps/api/src/modules/authentication/authentication.service.ts
api/apps/api/src/modules/authentication/dto/sign-up.dto.ts
api/apps/api/src/modules/users/user.api.entity.ts

-Adds two new columns and enums for `users` columns.
-Adapts sign-up endpoint to allow sending `background` and `level` information.

MARXAN-1643-modify-signup-to-include-bakground

---

api/apps/api/src/modules/published-project/published-project-crud.service.ts
api/apps/api/src/utils/published-export.utils.ts

-Adds and follows the same logic per `findAll` method that was already used in `getById` for published project entities.
-This means that `exportId` would only be present in a project IF and only IF the export has finished. If not, the entity would not include the `exportId` among its properties.

MARXAN-1580-disable-initial-export-published-projects

---

api/apps/geoprocessing/src/import/pieces-importers/planning-units-grid.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/piece-importers/planning-area-custom.piece-importer.e2e-spec.ts

leftover from the transition to plain PostgreSQL (without PostGIS extension) for apidb.

use geodb for queries that need PostGIS [MARXAN-1167]

---

api/apps/geoprocessing/src/migrations/geoprocessing/1655901622494-AddApiFeatureIdToScenarioFeaturesData.ts

This PR fixes the update of existing `scenario_features_data` rows when adding `api_feature_id`
[set api_feature_id for existing features: fix migration](https://vizzuality.atlassian.net/browse/MARXAN-1674)

fix: wrong update of exisiting scenario features data in migration

---

README.md
api/apps/geoprocessing/src/migrations/geoprocessing/1611221157285-InitialGeoDBSetup.ts
api/apps/geoprocessing/test/tiles/protected-area.fixtures.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts
postgresql/apidb.Dockerfile
postgresql/geodb.Dockerfile

**DO NOT MERGE**: even if/when we are happy with these changes after having magnificently verified everything for functional and performance regressions, we should keep these changes in a parallel universe of a PR stack that includes changes needed for infra/tf, so that we can keep fast-tracking urgent changes into `develop` in the meanwhile for any fixes that may be needed for instances where demos/training sessions are running.
https://vizzuality.atlassian.net/browse/MARXAN-1664
Part of spike to check if all works as expected (bar any tolerable performance regressions) if we run both apidb and geodb on PostgreSQL v13, in preparation to moving the database instances in k8s setups to the Azure database for PostgreSQL Flexible service, which currently supports PostgreSQL up to version 13. …

downgrade PostgreSQL to v13.x [MARXAN-1664]

---

api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-as-finished.handler.ts
api/apps/api/src/modules/legacy-project-import/application/run-legacy-project-import.handler.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import-checker/legacy-project-import-checker.module.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import-checker/legacy-project-import-checker.service-fake.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import-checker/legacy-project-import-checker.service.spec.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import-checker/legacy-project-import-checker.service.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import-checker/marxan-legacy-project-import-checker.service.ts
api/apps/api/src/modules/legacy-project-import/domain/legacy-project-import/legacy-project-import.ts
api/apps/api/src/modules/projects/block-guard/block-guard.module.ts
api/apps/api/src/modules/projects/block-guard/marxan-block-guard.service.spec.ts
api/apps/api/src/modules/projects/block-guard/marxan-block-guard.service.ts
api/apps/api/src/modules/scenarios/scenarios.module.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts

This PR adds:
- `LegacyProjectImportChecker` service. Now block guard checks if a project is blocked depending if there is an ongoing legacy project import for the given project.
[Block legacy projects being imported](https://vizzuality.atlassian.net/browse/MARXAN-1612)

forbid changes to legacy project imports [MARXAN-1612]

---

api/apps/api/src/modules/scenarios-features/compute-area.service.spec.ts
api/apps/api/src/modules/scenarios-features/compute-area.service.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvspr.dat.legacy-project.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvspr.dat.marxan-project.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvspr.dat.processor.module.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvspr.dat.processor.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.processor/puvsrpr.dat.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.data.service.spec.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1657780657222-AddFKBetweenPuvsprCalculationsAndProjectsPu.ts
api/libs/puvspr-calculations/src/index.ts
api/libs/puvspr-calculations/src/puvspr-calculations.geo.entity.ts
api/libs/puvspr-calculations/src/puvspr-calculations.service.ts
api/libs/puvspr-calculations/src/repository/memory-puvspr-calculations.repository.ts
api/libs/puvspr-calculations/src/repository/puvspr-calculations.repository.ts
api/libs/puvspr-calculations/src/repository/typeorm-puvspr-calculations.repository.ts

This PR adds FK between `puvspr_calculations` and `projects_pu` table. Now `PuvsprCalculationsService` methods returns also the `project_pu.id`.
[fix: add FK between puvspr_calculations and projects_pu](https://vizzuality.atlassian.net/browse/MARXAN-1689)

fix: add fk between puvspr_calculations and projects_pu table

---

api/apps/api/src/modules/authentication/authentication.service.ts
api/apps/api/src/utils/passwordValidation.utils.ts
api/apps/api/test/users.e2e-spec.ts
api/package.json
api/yarn.lock

-Adds small utility to check that passwords used are over 80 in entropy levels.
-Adds small test to check lower than 80 password can't be used.

MARXAN-1484-minimum-password-strength

---

api/apps/api/src/app.module.ts
api/apps/api/src/modules/authentication/authentication.controller.ts
api/apps/api/src/modules/authentication/authentication.module.ts
api/apps/api/test/users.e2e-spec.ts
api/package.json
api/yarn.lock

-Adds an endpoint request limit for Auth endpoints.
-The limit is 25 requests per minute mainly due to the amount of sign-in endpoint calls inside tests for the Auth module.

MARXAN-1486-auth-endpoint-limit

---

api/apps/api/src/modules/legacy-project-import/application/mark-legacy-project-import-as-finished.handler.ts
api/apps/api/src/modules/legacy-project-import/application/start-legacy-project-import.handler.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/input.legacy-piece-importer.ts
api/apps/geoprocessing/test/integration/legacy-project-import/input.legacy-piece-importer.e2e-spec.ts

This PR fixes scenario metadata for legacy project. Now when the legacy project import is finished the scenario metadata is updated so the lastCheckJob is made after the features are imported

feat: update scenario metadata for legacy project imports

---

api/apps/geoprocessing/src/migrations/geoprocessing/1657795596079-CreateFeaturesDataCleanupPreparation.ts
api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts

-Adds new method to cleanup `(geoDb)features_data` using a comparison with active `(apiDb)features`.
-Includes said method in the cleanup cron job in Geoprocessing service.

MARXAN-1684-cleanup-features-data

---

api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
api/apps/api/src/modules/scenarios-features/split/split-create-features.service.ts
api/apps/api/src/modules/scenarios-features/split/split-operation.service.ts
api/apps/api/src/modules/scenarios/specification/split-feature-config.mapper.ts
api/apps/api/test/integration/split-create-features.service.e2e-spec.ts

This PR adds creation of features when a split specification is submitted.
In case the base feature is already a derived feature, the service will fail, also, when cretaing the new features, in case no value has been specified in the subsets, the name of the only created feature will be set to:  "<base-feature-name> / <split-by-property>" 
[api: when users request to split features, (apidb)features records should always be created](https://vizzuality.atlassian.net/browse/MARXAN-1681)

create features for split [MARXAN-1681]

---

api/apps/api/src/modules/scenarios-features/split/split-create-features.service.ts
api/apps/api/src/modules/scenarios-features/split/split-operation.service.ts
api/apps/api/src/modules/scenarios-features/split/split-query.service.ts
api/apps/api/test/integration/split-query.service.e2e-spec.ts

This PR adds api feature id to split query. Also, now, split query is performed once per each split feature.
[api: set apiFeatureId in `SplitQuery.prepareQuery`](https://vizzuality.atlassian.net/browse/MARXAN-1682)

feat: add api_feature_id to split query

---

api/apps/api/src/modules/scenarios-features/split/split-query.service.ts

This PRs fixes the way we are filtering values in split query service. When uploading [feature](https://github.com/marxan-cloud/tnc-training-bots/blob/main/2022-03_okavango/geo-data/features/species/Syncerus_caffer.zip), values are of type numerical so the filtering was not working.

fix: filter values in split query service

---

api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/planning-grid.legacy-piece-importer.ts
api/apps/geoprocessing/test/integration/legacy-project-import/planning-grid.legacy-piece-importer.e2e-spec.ts

This PR sets on legacy project projects planning unit grid shape to `PlanningUnitGridShape.FromShapefile` 
[Legacy projects does not have planning_unit_grid_shape](https://vizzuality.atlassian.net/browse/MARXAN-1705)

feat: set planning unit grid shape on legacy projects

---

api/apps/api/config/default.json
api/apps/api/src/app.module.ts
api/apps/api/src/modules/export-cleanup/export-cleanup.module.ts
api/apps/api/src/modules/export-cleanup/export-cleanup.service.ts
api/apps/api/src/modules/export-cleanup/export-cleanup.ts

- Adds ExportCleanup module and service to API.
- Adds config interval to check for validity of creation of exports.
- Adds job that identifies expired exports based on time, its presence on the `published_projects` table and the scenario exports.

feat: identify expired resources in exports table [MARXAN-1649]

---

app/layout/projects/all/toolbar/upload-btn/legacy-upload-modal/upload-files/component.tsx
app/layout/projects/show/status/actions/done.tsx
app/layout/scenarios/edit/parameters/component.tsx

This PR adds the functionality so that it is possible to close the modal that is used to upload legacy projects in the event that the import is going to be executed correctly, or that validation errors are displayed in the event that the files are incorrect.
It also disables the Run Scenario button in case the option has been checked when uploading the legacy project.
**IMPORTANT:** The `useScenariosStatus` polling is not fast enough for the "_legacy_" job to return a "_failure_" status before the project has been deleted, so the solution adopted has been to add a `useEffect` to read the validations in case `useScenarioStatus` returns an error or the status of the job is failure. This is not optimal, since `useScenarioStatus` could fail for another reason.
1. Please create a legacy …

feat(front): legacy project validations + solutions locked[MARXAN-1693]

---

api/apps/geoprocessing/src/migrations/geoprocessing/1658479002103-AddColumnMarkSelectionsUsersScenariosPuData.ts
api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
api/libs/scenarios-planning-unit/src/scenario-planning-units-protection-status-calculator-service.ts
api/libs/scenarios-planning-unit/src/scenarios-planning-unit.geo.entity.ts

- Adds new column `lock_status_set_by_user` to `scenarios_pu_data` table.
- Applies lock by user when it is effectively locked by user in ScenarioPlanningUnitsInclusionProcessor.
- Checks for locks by users when ScenarioPlanningUnitsProtectedStatusCalculatorService calculation is executed.

MARXAN-1308-1690-1691-1692-scenarios-lockin-lockout

---

api/apps/api/src/modules/geo-features/geo-feature-property-sets.service.ts

This PR changes the `bbox` filter being made in `getFeaturePropertySetsForFeatures` function as it seems to not be working properly. As an example, when selecting [Syncerus_caffer](https://github.com/marxan-cloud/tnc-training-bots/blob/main/2022-03_okavango/geo-data/features/species/Syncerus_caffer.zip) feature in a project with  the whole Angola 5000km2 hex as planning grid, no properties sets are returned, meanwhile, when using the same feature in a project with Angola -> Cuando Cubango region, 5000km² hex as planning grid,  properties sets are returned
Now we use the `nominatim2bbox` function and interchange the east and west `bbox`. These changes replicate what seems to be the same filter in other parts of the codebase, so it could be wrong.
[Split icon  does not appear in features …

fix: bbox filter in getFeaturePropertySetsForFeatures function

---

app/components/features/selected-item/component.tsx
app/hooks/map/constants.tsx
app/hooks/map/index.ts
app/hooks/map/types.ts
app/layout/scenarios/edit/map/component.tsx
app/package.json
app/yarn.lock

Continuation of `feature/split` since that branch was merged into develop and vercel-demo so the backend could work.
- Collapse the split button when there are split features as well.
- Add basic legend to the features preview, displaying the name of each legend.
- Assign a color within a ramp to each feature preview
[MARXAN-1706](https://vizzuality.atlassian.net/browse/MARXAN-1706)
[MARXAN-1713](https://vizzuality.atlassian.net/browse/MARXAN-1713)
---

feat(front): Features Split 2

---

api/apps/api/src/modules/scenarios-features/copy/copy-data-provider.service.ts
api/apps/api/src/modules/scenarios-features/copy/copy-operation.service.ts
api/apps/api/src/modules/scenarios-features/copy/copy-query.service.spec.ts
api/apps/api/src/modules/scenarios-features/copy/copy-query.service.ts

This PR adds support for split features in `CopyQuery`.
The copy of split features will insert into `scenario_features_preparation` every features_data record which is part of the split(they have the `splitByProperty` key in their properties with the same `value` if specified), the `api_feature_id` will always be the `feature_id`  from the specification(independent of if we are copying a derived feature or not) and in case we are copying a derived feature, the filters by `feature_id` will use with the `base feature id`
[Copy query should support split features ](https://vizzuality.atlassian.net/browse/MARXAN-1723)

feat: copy query supports split features

---

api/apps/api/src/modules/scenarios-features/compute-area.service.spec.ts
api/apps/api/src/modules/scenarios-features/compute-area.service.ts
api/apps/api/src/modules/scenarios-features/scenario-features.module.ts
api/apps/api/src/modules/scenarios/input-files/input-files.module.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.dat.service.ts
api/apps/api/src/modules/scenarios/input-files/puvspr.data.service.spec.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-custom-features.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-features-data.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/project-custom-features.piece-importer.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features-specification.legacy-piece-importer.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features.legacy-piece-importer.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1659032419406-MoveAmountFromLegacyProjectToFeaturesData.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/scenario-features-data.piece-exporter.e2e-spec.ts
api/apps/geoprocessing/test/integration/cloning/piece-importers/scenario-features-data.piece-importer.e2e-spec.ts
api/apps/geoprocessing/test/integration/legacy-project-import/features.legacy-piece-importer.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-features.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-features-data.ts
api/libs/features/src/scenario-features-data.geo.entity.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts
api/libs/puvspr-calculations/src/puvspr-calculations.service.ts

This PR moves `amount_from_legacy_project` column from `scenario_features_data` to `feratures_data` and adds `project_pu_id` FK to `projects_pu` in `features_data`.
It also change the way we check if a project is a legacy project using the `ProjectSourcesEnum`, this is need as in case we clone a legacy project the previous check would fail as it would not be considered a legacy project.
[move amount from legacy project column from scenarios_features_data to features data](https://vizzuality.atlassian.net/browse/MARXAN-1728)

move amount from legacy project column [MARXAN-1728 ]

---

api/apps/geoprocessing/src/migrations/geoprocessing/1659439420578-RenameCleanUpPreparationTables.ts
api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts

This PR improves geo clean up service adding locks to projects, scenarios and features tables when searching for the in use ids.
Also, in the before implementation, in `cleanupProjectsDanglingData` function, we were removing `features` rows when a feature is from a project that is not in `projects` table, I believe this is not necessary because, there is already a foreing key between `features` and `projects` tables with `on delete` action
[improve geodata garbage collection](https://vizzuality.atlassian.net/browse/MARXAN-1694)

feat: improve geo clean up service

---

app/components/features/target-spf-item/types.ts
app/hooks/features/index.ts
app/hooks/map/constants.tsx
app/hooks/map/index.ts
app/hooks/map/types.ts
app/layout/scenarios/edit/features/set-up/add/list/component.tsx
app/layout/scenarios/edit/map/component.tsx

This PR adds the possibility to show preview layers on the map, even if they are splitted. 
I also change a little bit the way we were assigning the colors to those layers to prevent changing the color once you add one layer to the map. Adding the layers

Preview splitted features on the map

---

api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features-specification.legacy-piece-importer.ts
api/apps/geoprocessing/test/integration/legacy-project-import/features-specification.legacy-piece-importer.e2e-spec.ts
api/libs/legacy-project-import/src/legacy-project-import-piece-processor.port.ts

https://vizzuality.atlassian.net/browse/MARXAN-1771

retry more slowly but for longer (every 30s up to 2hrs) [MARXAN-1771]

---

app/components/gap-analysis/item/component.tsx
app/hooks/gap-analysis/index.ts

Split from BE PR
[https://github.com/Vizzuality/marxan-cloud/pull/1256#pullrequestreview-1160014410](https://github.com/Vizzuality/marxan-cloud/pull/1256#pullrequestreview-1160014410)
Test with new Andrea and Ana share project `/projects/c2d153f4-d480-4720-bff9-bd4b199da859` and also with other accounts.
[MARXAN-1818](https://vizzuality.atlassian.net/browse/MARXAN-1818)

fix(front): use onTarget value on  target achievement and gap analysis

---

infrastructure/base/main.tf
infrastructure/base/modules/kubernetes/main.tf
infrastructure/base/modules/kubernetes/variables.tf
infrastructure/base/modules/node_pool/main.tf
infrastructure/base/modules/node_pool/variables.tf
infrastructure/base/variables.tf
infrastructure/kubernetes/main.tf
infrastructure/kubernetes/modules/ping_test/configuration.xml.tpl
infrastructure/kubernetes/modules/ping_test/main.tf
infrastructure/kubernetes/modules/ping_test/variables.tf
infrastructure/kubernetes/variables.tf

Tried to apply this, ran into the following:
> │ Error: updating Cluster: (Managed Cluster Name "marxan-tnc" / Resource Group "marxan-rg"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="To enabled Auto Upgrade, agentpools and cluster kubernetes versions must be at least (lowest supported minor version - 1) for rapid and stable channel or supported for patch and node-image channel."
Need to further look into it, didn't want to invest more time without ok from the client

Enable patch version updates on k8s

---

api/apps/api/test/scenario-input-files/scenario-input-files.e2e-spec.ts
api/libs/marxan-input/src/__snapshots__/marxan-input.spec.ts.snap
api/libs/marxan-input/src/marxan-input.spec.ts
api/libs/marxan-input/src/marxan-parameters.ts

Default should be `-1`.
N/A
When entering the tab to set advanced Marxan settings, BESTSCORE should be set to `-1`.
https://vizzuality.atlassian.net/browse/MARXAN-1819
---

fix default BESTSCORE value [MARXAN-1819]

---

api/apps/api/config/default.json
api/apps/api/src/modules/export-cleanup/export-cleanup.service.ts

Fix overly eager query - it would identify all project exports created over the configured timespan as to be purged, whereas exports of published projects must never be purged.
The PR also actually enables scheduled cleanups (until now they were conservatively semi-paused, executing only once yearly).
N/A
Exports of published projects should never be purged
https://vizzuality.atlassian.net/browse/MARXAN-1823
---

only purge expired private project exports [MARXAN-1823]

---

api/apps/geoprocessing/src/marxan-sandboxed-runner/adapters-shared/assets/asset-fetcher.ts
env.default

I think we were relying on a networking configuration that is either valid in Compose v1 and not in v2 or on some combination of factors that made it possible in Compose v1 to reach a service running in a container, from a container on the same Docker network, using a port exposed via the `services.<servicename>.ports` configuration section, whereas this is not possible (arguably, for very good reasons) in Compose v2.
This commit fixes the `env.default` file so that it can be used "out of the box" after running `make .env` in a development instance.

use in-container port by default [MRXN23-50]

---

api/apps/api/src/modules/scenarios/dto/clear-lock-status-param.dto.ts
api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-pu-change/assertions/has-expected-job-details.ts
api/apps/api/test/scenario-pu-change/scenario-pu-status-clear.e2e-spec.ts
api/apps/api/test/scenario-pu-change/steps/WhenChangingPlanningUnitInclusivity.ts
api/apps/api/test/scenario-pu-change/steps/world.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts

Adding possibility for the user to clear selected kind of previously set statuses: Locked-in, Locked-out or Made available.
Process is the following:
- Endpoint receives scenario id and kind of status to be cleared
- Service finds all the PU ids that were set by user for each status kind 
- Removes the kind selected to be cleared from the claims to be sent to status change processor
- Processor resets all the statuses and ads only received claims. Since no claims for the selected to be cleared statuses will be received - PUs that had this status will be set to:
available with setbyUser=false OR 
locked-in with setByUser=false with protectedByDefault=true in case of PUs belonging to a protected area
_Please explain how to test the PR: …

[api] Clear PU status by category

---

api/apps/api/src/modules/analysis/providers/shared/__mocks__/scenario-planning-unit-geo.data.ts
api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.dto.ts
api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.serializer.ts
api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.e2e-spec.ts
api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.fixtures.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts
api/libs/scenarios-planning-unit/src/scenarios-planning-unit.geo.entity.ts

Apart form 'defaultStatus' and 'inclusionStatus' response will also include 'setByUser' property.
Tests updated accordingly.
---

Add setByUser property to PU endpoint response, update tests

---

api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/scenario-pu-change/assertions/has-expected-job-details.ts
api/apps/api/test/scenario-pu-change/scenario-pu-status-clear.e2e-spec.ts
api/apps/api/test/scenario-pu-change/steps/world.ts
api/apps/geoprocessing/test/steps/given-scenario-pu-data-exists.ts

- New method added to correctly find the PUs that has have been set by user and NOT coincide with status kind to be clear (basically adding filter 
- New separate method for finding the above mentioned PUs with status 'available' - in this case we need to use Query Builder, because in DB available lock status is NULL, and with the latest update of Typeorm repository find method with where condition translates to 'WHERE scenarioPuData.lockin_status =NULL' which leads to corrupted results
- Test preconditions are expanded to have more PUs with both SetByUser property values of true and false, expected results updates
_Link to the related task manager …

[api] Fix setByUser filter bug when changing status by kind

---

api/apps/geoprocessing/src/export/pieces-exporters/project-custom-features.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/project-custom-features.piece-importer.ts
api/apps/geoprocessing/src/legacy-project-import/legacy-piece-importers/features.legacy-piece-importer.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1689003155444-RenameAmountColumnInFeaturesData.ts
api/apps/geoprocessing/test/integration/legacy-project-import/features.legacy-piece-importer.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-features.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts
api/libs/puvspr-calculations/src/puvspr-calculations.service.ts
docs/download-upload-clone/legacy-marxan-projects/high-level-design.md

Currently 'features_data' table in geoprocessing database has a column 'amount_from_legacy_project', the aim of this PR is to change column name to 'amoutn' to make it more abstract, since, with the further changes, amount will also come from csv files uploads.
---

Rename amount column in geo features_data table

---

api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/planning-unit-inclusion.e2e-spec.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts

When PUs are in locked-in by default status because of being considered protected, if I make some of these “available” and I then clear the “available” status, the PUs that were explicitly set as available earlier on are now not locked in again (the PU fill-color stays blue but they are not coloured with the pale blue-green stroke on their edges).
This is a bug in api applyClaims() method that resets protectedByDefault to false when applying makeAvailable claims.
PR removes protectedByDefault reset and adds a new test covering the use case
---
deploying to staging/production, please add brief testing …

Fix protectedByDefault over-ride for makeAvailable claims

---

api/api.Dockerfile
api/apps/api/src/app.module.ts
api/apps/api/src/migrations/api/1689091277937-AddOutputProjectSummary.ts
api/apps/api/src/modules/projects/output-project-summaries/output-project-summaries.module.ts
api/apps/api/src/modules/projects/output-project-summaries/output-project-summaries.service.ts
api/apps/api/src/modules/projects/output-project-summaries/solution-data/best-solution-data.service.ts
api/apps/api/src/modules/projects/output-project-summaries/solution-data/summed-solution-data.service.ts
api/apps/api/src/modules/scenarios/marxan-run/events.handler.ts
api/apps/api/src/modules/scenarios/marxan-run/marxan-run.module.ts
api/apps/api/src/modules/scenarios/marxan-run/run.service.spec.ts
api/apps/api/test/jest-e2e.json
api/apps/api/test/project/output-project-summaries.e2e-spec.ts
api/apps/api/test/scenarios/cost-range.service.e2e-spec.ts
api/apps/geoprocessing/test/integration/marxan-run/blm-calibration-run.e2e-spec.ts
api/apps/geoprocessing/test/integration/marxan-run/marxan-run.e2e-spec.ts
api/apps/geoprocessing/test/jest-e2e.json
api/apps/geoprocessing/test/steps/given-scenario-pu-data-exists.ts
api/libs/output-project-summaries/src/index.ts
api/libs/output-project-summaries/src/output-project-summary.api.entity.ts
api/libs/output-project-summaries/tsconfig.lib.json
api/nest-cli.json
api/package.json
api/tsconfig.json

Adds a new OutputProjectSummariesService that will generate a series of CSV files with summary info for all the scenarios runs in a given project, and store a zip with those files on the DB. This will be triggered after completing a Marxan run, on the API side at the end of the whole process.
---

feat(Marxan): Adds new service to generate Project Summaries after a run

---

app/hooks/scenarios/index.ts
app/layout/scenarios/edit/planning-unit/adjust-planning-units/actions-summary/component.tsx
app/layout/scenarios/edit/planning-unit/adjust-planning-units/actions/component.tsx
app/layout/scenarios/edit/planning-unit/adjust-planning-units/actions/draw/component.tsx
app/layout/scenarios/edit/planning-unit/adjust-planning-units/actions/select/component.tsx
app/layout/scenarios/edit/planning-unit/adjust-planning-units/actions/upload/component.tsx

This PR attempts to fix the issue reported [here](https://vizzuality.atlassian.net/browse/MRXN23-120?focusedCommentId=25215) where, once a user created a scenario and sets a protected area, the locked-in PU of the protected area were reflected in the summary in the panel. This lead to display of the _Clear_ button but actually it does nothing as it's trying to revert to the original state of the PUs when it is already there.
Before:
The solution is filtering the, in this case, locked-in PUs (_included_ ones for humans) by the property `setByUser` as the protected area setup is not run by the user (well, it is, but the user does not set explicitly the status of the PU) so we can assume there's nothing to clear as there isn't anything set by the user yet.
This also implies those PUs won't …

[MRXN23-120]: fixes PU count with protected area set

---

api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/test/upload-feature/upload-feature-csv.e2e-spec.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts

This PR adds small fixes for Id0 feature upload via CSV file:
1. Saving csv data in temporary storage in (apiDb).features_amounts is fixed to be done in bulk, divided in chunks 
2. After successful insert of all feature data in relevant tables, project sources is changed to 'legacy_import' for correct amount usage during runs
3. Small test update to check projects.sources change
---

(api): fix CSV feature upload  [MRXN23-249, MRXN23-246]

---

api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts

Adding logs and small performance improvement for bulk insert query - according to tests and logs analysis the fastest way for now is to set CTE used for features_data inserts as NOT MATERIALIZED and using chunks of 1000 values.
Some postgres analyse results:
Possible further solutions - inserting data with async jobs, refactoring geometries handling for features data uploaded via csv.
---

[api] improve insert performance when persisting features data from CSV uploads [MRXN23-256]

---

api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts

Small fix that sets new features, uploaded with csv file, to have value `is_legacy=true`. After csv feature upload project sources has already been being set to `legacy_import`. Setting features as legacy was missing for correct data generation made by `PuvsprDatLegacyProject.getAmountPerPlanningUnitAndFeature()`
Upload features from csv file to a projects scenario. New features must have `is_legacy=true` in (apiDB).featuresTable.
Generating puvspr.dat file must return amounts per species per planning units in accordance with csv file data (not an empty table as it is now).
---
to the deploy checklist …

[api] fixes csv features upload to save features as is_legacy=true for correct puvspr.dat generation [MRXN23-279]

---

app/layout/projects/show/status/actions/done.tsx
app/layout/projects/show/status/component.tsx

This PRs fixes a loop with one of the dependencies when the user generates the download of a project and the job callbacks are triggered in a loop.
–
[MRXN23-291](https://vizzuality.atlassian.net/browse/MRXN23-291)
---
[MRXN23-291]: https://vizzuality.atlassian.net/browse/MRXN23-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MRXN23-228] fix: project export loop on status actions

---

api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.service.ts
api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/projects/dto/upload-shapefile.dto.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/test/upload-feature/upload-feature.e2e-spec.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts

`POST /api/v1/projects/:projectId/features/shapefile` should return a JSON:API representation of the uploaded feature from shapefile, upon success.
https://vizzuality.atlassian.net/browse/MRXN23-289
---

return JSON:API representation of new feature when successfully creating a feature from shapefile [MRXN23-289 ]

---

api/apps/api/src/modules/geo-features/import/csv.parser.ts

Uploading CSV files of features from puvspr data is _always_ failing since... some days ago, because by the time we'd call `resolve(featureAmount)` (`on('end')`), in `featureAmountCsvParser()`, `featureAmount` would be null.
I haven't been able to check why the original implementation, which we didn't touch since it was done, has always been working as expected, and then suddenly stopped working, all the time, except it's working just fine when running in CI: I guess this should be best done by `git bisect`ing things, which could take some time.
In the meanwhile, the proposed fix in this PR does solve the problem that sprung up.
Uploading features from a puvspr CSV sample file should lead to features being correctly created (please use a valid features.csv file so that we don't have to …

use validateSync() (to avoid temporal dead zone?) [MRXN23-292]

---

api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/business-critical/marxan-run/execute-marxan-run.e2e-spec.ts
api/apps/api/test/business-critical/marxan-run/fixtures.ts
api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.fixtures.ts

- Adds a new ProjectCostSurfaceControler
- Moves all cost surface related operations from ScenarioController to ProjectCostSurfaceControler
- Updates tests / fixtures
Following the API conventions in the scope of this task, no functionality is added, besides creating new endpoints.
Access control is handled at service level since 49ea0d52c98c530cc6eb3250711b3476a51ba6d8 as opposed to how is done in different controlers, the only auth stuff being used is the built-in module with some custom decorators.
I also realized that there are no tests specifically hitting the moved endpoints, however acl methods being used in said endpoints are tested hitting another endpoints
This being said I think it would be redundant to add more tests hitting those new endpoints
CI happy we happy
1. …

New ProjectCostSurfaceController [MRXN23-92]

---

api/apps/api/src/modules/projects/projects-proxy.controller.ts
api/apps/api/src/modules/projects/projects.controller.ts
api/apps/api/test/project/projects.fixtures.ts
api/apps/api/test/upload-feature/upload-feature.e2e-spec.ts

Like for all other "reverse-proxy" endpoints in front of the webshot service, since we need to be able to accept a request body for these requests.
Requests from frontend should be processed correctly, including their body
---

fix: use POST verb rather than GET for webshot API endpoint for scenario comparison maps [MRXN23-323]

---

api/apps/api/src/modules/projects/project-protected-areas.controller.ts
api/apps/api/src/modules/projects/project-protected-areas.service.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/protected-areas/protected-areas-crud.module.ts
api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
api/apps/api/test/scenario-protected-areas/fixtures.ts
api/apps/api/test/scenario-protected-areas/list-project-protected-ares.e2e-spec.ts
api/libs/protected-areas/src/protected-areas.geo.entity.ts

`GET /api/v1/projects/:projectId/protected-areas` should return a response such as the one below, with all of the user-uploaded protected areas listed in alphabetical order (by `fullName`), including a `scenarioUsageCount`.
```
{
"data": [
{
"type": "protected_areas",
"id": "3902bb73-c95c-42e1-b69f-e7f185d3cb45",
"attributes": {
"wdpaId": null,
"fullName": "pa elephant",
"iucnCategory": null,
"shapeLength": null,
"shapeArea": null,
"countryId": null,
"status": null,
"designation": null,
"scenarioUsageCount": 0
}
}
]
}
```
https://vizzuality.atlassian.net/browse/MRXN23-251
https://vizzuality.atlassian.net/browse/MRXN23-282
---

add ability to list protected areas by project, with count of scenarios where each protected area is used [MRXN23-251] [MRXN23-282]

---

api/apps/api/src/modules/scenarios/scenarios.controller.ts

After some investigation of the missing endpoint, the conclusions and sequence of events are the following:
- Following endpoints have been removed from ScenariosController and added to ProjectCostSurfaceController: processCostSurfaceShapefile, getCostRange, getScenarioCostSurface
- Then following endpoints were roll back as deprecated: processCostSurfaceShapefile, getScenarioCostSurface rolled back and renamed to getPuDatFile
- So getCostRange() hasn't been rolled back as deprecated to ScenariosController
In order for FE to be able to work with 'old' endpoints, they need to be the following (implemented in this PR) :
`GET /api/v1/scenarios/{scenarioId}/cost-surface`- to get cost surface range
`POST /api/v1/scenarios/{scenarioId}/cost-surface/shapefile` - to upload shapefil of cost …

Rollback ScenariosController.getCostRange() as deprecated, fix param bug

---

app/hooks/scenarios/index.ts
app/layout/scenarios/edit/map/component.tsx

This PR fixes two issues:
- the scenario data returned by a mutation after saving the new planning units was wrong (`{data: scenario}` vs `scenario`) leading to an undefined result and a wrong layer threshold.
- an issue with the cache of the layers: now we need to ensure the cache is updated whenever the user changes the tab, or the layer will remain untouched regardless of changing the tab and its configuration.
–
https://vizzuality.atlassian.net/browse/MRXN23-397
---

[MRXN23-397]: fixes PU map

---

app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/index.tsx
app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/tabs/index.tsx
app/layout/scenarios/edit/map/component.tsx

https://vizzuality.atlassian.net/browse/MRXN23-410
---

[MRXN23-410]: updates planning unit status tab order

---

app/hooks/map/constants.tsx
app/hooks/map/index.ts

Updates colours of Protected Areas and Protected Areas Preview layer to differentiate them better.
Note: this is done without design consent. We might need to change colours later, but, for now, at least the layers can be differentiated.
https://vizzuality.atlassian.net/browse/MRXN23-395
---

[MRXN23-395]: updates protected area step improve

---

app/layout/project/sidebar/index.tsx
app/layout/project/sidebar/project/inventory-panel/components/inventory-table/index.tsx
app/layout/project/sidebar/project/inventory-panel/features/index.tsx
app/layout/project/sidebar/project/inventory-panel/index.tsx
app/layout/project/sidebar/project/scenarios-list/index.tsx
app/layout/project/sidebar/scenario/advanced-settings/blm-calibration/component.tsx
app/layout/project/sidebar/scenario/advanced-settings/overview/component.tsx
app/layout/project/sidebar/scenario/grid-setup/features/add/component.tsx
app/layout/project/sidebar/scenario/grid-setup/features/add/list/component.tsx
app/layout/project/sidebar/scenario/grid-setup/gap-analysis/index.tsx
app/layout/project/sidebar/scenario/solutions/gap-analysis/index.tsx
app/layout/scenarios/sidebar/component.tsx

Now lists will take up all the space available instead of limiting them manually.
- Check any list in the sidebar, there shouldn't be scrollbar unless it is needed and they should take up all the space if there many items on them.
https://vizzuality.atlassian.net/browse/MRXN23-399
---

[MRXN23-399]: improves layout and responsiveness of lists

---

app/layout/projects/show/map/index.tsx
app/layout/scenarios/new/map/component.tsx

–
- go to `/projects/{id}` and `/projects/{id}/scenarios/new`,
- The map should be adjusted and centered according to the space available
–
---

[FE]: adjusts bbox padding for some maps

---

app/hooks/wdpa/index.ts
app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx
app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/pa-uploader/index.tsx

This PR ensures the PA list is kept up to date once the user has uploaded a new PA. The truth is this was already working, but I am adding query invalidation just in case.
- go to `/projects/{id}/scenarios/{id}/edit?tab=protected-areas`,
- Click on `Upload your protected area network` button and upload a PA.
- Check again the list in the panel, the uploaded PA should be reflected in the list.
NOTE: uploading the same shapefile over again will REPLACE the current PA with the new one, so don't expect having 2 different PAs with the same shapefile.
https://vizzuality.atlassian.net/browse/MRXN23-408
---

[MRXN23-408]: ensures PA list in scenarios keeps up to date after uploading a protected area

---

app/hooks/projects/index.ts
app/layout/projects/show/map/index.tsx
app/layout/projects/show/status/component.tsx
app/layout/projects/show/status/utils.tsx
app/layout/scenarios/edit/map/component.tsx
app/layout/scenarios/reports/blm/map/component.tsx
app/layout/scenarios/reports/frequency/map/component.tsx
app/layout/scenarios/reports/solutions/selected-solution-page/map/component.tsx
app/layout/scenarios/reports/solutions/selection-frequency-page/map/component.tsx

This PR aims to hide the status screen when a job is done. Keeping the condition came out in a visual bug when sometimes a process was done (and the API informed about it) but we kept the status screen visible while nothing was running in the background.
An example is when a user tries to download a project, after clicking to generate the report, once done, the status screen is still visible despite not running anything in the API.
- Go to the project `/projects/{id}` page and click on `Downlaod` button,
- generate a new export. You will notice the background darken as the status screen is visible. This is fine.
- after finishing generating the report, the status screen should be gone.
–
---
deploying to staging/production, please …

[FE]: removes job done status as condition to display status progress

---

app/layout/projects/new/form/component.tsx

The issue was the property `PAOptionSelected` (the one that determines which kind of layers the map should render) wasn't being passed correctly after moving the form a long time ago.
–
- go to `/projects/new`,
- In the form, select the `Yes, I have a planning unit shapefile` option and upload the shapefile attached to the task,
- After uploading and saving, the map should look like the image above.
https://vizzuality.atlassian.net/browse/MRXN23-407
---

[MRXN23-407]:  fixes project creation through shapefile with grid

---

app/hooks/features/index.ts
app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx

Fixes issues retaining old data for targets and SPF invalidating the query cache.
https://vizzuality.atlassian.net/browse/MRXN23-402?focusedCommentId=25688
---

[MRXN23-402]: adds query invalidation for target-spf data

---

api/apps/api/src/modules/projects/output-project-summaries/output-project-summaries.service.ts
api/apps/api/test/project/output-project-summaries.e2e-spec.ts

look-up for scenarios that have been run at least once, to avoid exception for when searching a scenario that have never run, in the table of scenarios that must have been run, as simple as that
1. Create a project, and two scenarios. Run one of them, it should succeed.
2. It's pretty much the same, but: Create a project, a scenario and run it. Create another scenario, and run the PREVIOUS one. It should also succeed.
3. Any other case related to this that I am not aware of just yet
[MRXN23-45](https://vizzuality.atlassian.net/browse/MRXN23-403)
[MRXN23-45]: …

[MRXN-23-45] bugfix: marxan run fail 

---

app/components/button/index.ts
app/layout/header/index.tsx
app/pages/index.tsx
app/pages/projects/index.tsx

Fixes header when a user is logged adding a callback to the user menu.
–
https://vizzuality.atlassian.net/browse/MRXN23-416
---

[MRXN23-416]: adds callback in header for logged users

---

app/components/upload-tabs/index.tsx

Hides CSV tab behind a feature flag until approved.
- To enable the tab, add `CSVUpload` to your `NEXT_PUBLIC_FEATURE_FLAGS` variable.
https://vizzuality.atlassian.net/browse/MRXN23-423
---

[MRXN23-423]: adds feature flag for CSV feature upload

---

app/hooks/scenarios/index.ts
app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx

Fixes an issue where the form would reset the default values of the selector after uploading a shapefile.
- Go to `/projects/{pid}/scenarios/{sid}/edit?tab=protected-areas`,
- Click on the selector and add/remove an option,
- Upload a shapefile and check the number of options selected in the selector.
- It should be up to date with your most recent selection (previously it would go back to the default value coming from API)
https://vizzuality.atlassian.net/browse/MRXN23-419
---

[MRXN23-419]: PA selector: fixes setting default values after uploading shapefile

---

app/layout/project/navigation/hooks.tsx
app/layout/project/navigation/index.tsx

Moves Planning Units section right after Protected Areas.
–
https://vizzuality.atlassian.net/browse/MRXN23-427
---

[MRXN23-427]: moves PU section right after PA

---

app/layout/project/navigation/constants.ts
app/layout/project/navigation/hooks.tsx
app/layout/project/navigation/index.tsx
app/layout/project/navigation/types.ts

https://vizzuality.atlassian.net/browse/MRXN23-431
---

[MRXN23-431]: renames advanced settings section

---

.github/workflows/cypress.yml
.github/workflows/deploy-to-kubernetes.yml
.github/workflows/publish-marxan-docker-images.yml

https://vizzuality.atlassian.net/browse/MRXN23-455

fix(infra): remove reliance on deprecated gh actions bits [MRXN23-455]

---

app/hooks/wdpa/index.ts
app/layout/project/sidebar/project/inventory-panel/components/inventory-table/types.ts
app/layout/project/sidebar/project/inventory-panel/wdpas/index.tsx
app/layout/project/sidebar/project/inventory-panel/wdpas/modals/delete/index.tsx
app/layout/project/sidebar/project/inventory-panel/wdpas/modals/edit/index.tsx
app/layout/project/sidebar/project/inventory-panel/wdpas/modals/upload/index.tsx
app/types/api/wdpa.ts

This PR parses the hook that provides WDPAs per project to follow JSONAPI spec and eliminate the `attributes` property.
–
---

[N/A]: parses WDPA endpoint

---

api/apps/geoprocessing/src/modules/features/features.service.ts

Hotfix that adds a coalesce to prevent a side effect of concatenating a null value with a json.

added coalesce to avoid issue when property does not exist

---

api/apps/api/src/decorators/json-api-parameters.decorator.ts
api/apps/api/src/migrations/api/1692296547437-AddUploadingProtectedAreaShapefileToProjectEvents.ts
api/apps/api/src/modules/async-jobs-garbage-collector/project-async-jobs.garbage-collector.ts
api/apps/api/src/modules/projects/project-protected-areas.controller.ts
api/apps/api/src/modules/projects/projects.module.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/src/modules/protected-areas/protected-areas-crud.service.ts
api/apps/api/src/modules/scenarios/protected-area/getter/selection-get.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/api/test/scenario-protected-areas/fixtures.ts
api/apps/api/test/scenario-protected-areas/list-project-protected-ares.e2e-spec.ts
api/apps/geoprocessing/src/modules/features/features.service.ts
api/libs/protected-areas/src/protected-areas.geo.entity.ts

Response structure updated - new property 'name' added. For custom PAs it will contain 'fullName', for global - 'iucnCategory'.
Global PAs are grouped by category.
Sorting and filtering by 'name' property enabled.
Tests updated
---

[api] Update GET project protected areas list endpoint [MRXN23-451]

---

app/layout/project/navigation/hooks.tsx

This PR removes the feature flag used to hide the Protected Areas section in the inventory panel.
–
–
---

[N/A]: removes PAs feature flag

---

app/layout/project/sidebar/scenario/grid-setup/protected-areas/categories/index.tsx
app/layout/project/sidebar/scenario/grid-setup/protected-areas/threshold/index.tsx

Now we are reading complete global protected areas name from API both on Inventory Panel and scenarios detail
[MRXN23-461](https://vizzuality.atlassian.net/browse/MRXN23-461)
[MRXN23-461]: https://vizzuality.atlassian.net/browse/MRXN23-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FE (fix): protected areas name consistency [MRXN23-461]

---

app/layout/projects/show/map/index.tsx

Fixes a visual glitch where the loading screen of the map would overlap the sidebar, leading to a _blink_ effect.
---

fixes sidebar blink

---

app/components/toast/component.tsx
app/hooks/scenarios/index.ts
app/layout/help/documentation/component.tsx
app/layout/loading/component.tsx
app/layout/project/sidebar/project/scenarios-list/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx
app/layout/projects/show/map/index.tsx
app/layout/scenarios/edit/map/component.tsx
app/layout/scenarios/edit/map/legend/hooks/index.ts
app/layout/toast/component.tsx

Now it's not possible asking for the scenario summary unless there is, at least, one scenario run previously.
https://vizzuality.atlassian.net/browse/MRXN23-475
---

[MRXN23-475]: disables scenario export without run scenarios

---

app/hooks/scenarios/index.ts
app/layout/project/navigation/hooks.tsx
app/layout/project/navigation/index.tsx
app/layout/project/sidebar/scenario/header/index.tsx

- The scenario list is now refetched on focus (ie: changing to the tab).
- Minor adjustment to navigation routes to avoid displaying the scenario title in the scenario creation screen.
---

[N/A]: refetches scenarios list on focus

---

api/apps/api/src/modules/cost-surface/cost-surface.service.ts
api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/api/src/modules/scenarios/protected-area/getter/selection-get.service.ts
api/apps/api/test/project/project-cost-surface.e2e-spec.ts
api/apps/api/test/project/project-cost-surface.fixtures.ts

The endpoint has already been part of ProjectCostSurfaceController and was using ScenariosService  to get min and max values from `cost_surface_pu_data`. This PR implements Cost Surface service to retrieve min and max data from `(api)cost_surfaces table` and adds test.
---

[api] Update endpoint for getting project cost surface min and max values [MRXN23-320]

---

api/apps/api/src/modules/cost-surface/cost-surface.api.entity.ts
api/apps/api/src/modules/cost-surface/dto/cost-surface.serializer.ts
api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/api/test/project/project-cost-surface.controller.acl.e2e-spec.ts
api/apps/api/test/project/project-cost-surface.e2e-spec.ts
api/apps/api/test/project/project-cost-surface.fixtures.ts

feat(CostSurface): Adds GET endpoint to retrieve one and all Cost Surfaces for a Project [MRXN23-108] [MRXN23-109]

---

api/apps/api/src/modules/scenarios/scenarios-crud.service.ts
api/apps/api/test/project-scenarios.e2e-spec.ts

Modifies the Scenarios serializer config to account the possible inclusion of costSurfaces on the GET responses (by using FetchSpecification's include in the GET request)
---

feat(CostSurface): Adds CostSurface data to Scenario GET endpoints [MRXN23-110]

---

api/apps/api/src/migrations/api/1695040870835-AddClonePieceForProjectCostSurfaces.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.spec.ts
api/apps/api/src/modules/clone/export/adapters/export-resource-pieces.adapter.ts
api/apps/api/src/modules/cost-surface/cost-surface.service.ts
api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/geoprocessing/src/export/pieces-exporters/pieces-exporters.module.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-cost-surfaces.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/pieces-importers.module.ts
api/apps/geoprocessing/src/import/pieces-importers/project-cost-surfaces.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/fixtures.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/project-cost-surface.piece-exporter.e2e-spec.ts
api/apps/geoprocessing/test/integration/cloning/piece-importers/project-cost-surface.piece-importer.e2e-spec.ts
api/apps/geoprocessing/test/integration/cost-surface/cleanup.fixtures.ts
api/libs/cloning/src/domain/clone-piece.ts
api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-cost-surfaces.ts

[api] Add cost surface piece exporter and importer [MRXN23-111] [MRXN23-19] [MRXN23-112] [MRXN23-20]

---

api/apps/api/src/modules/clone/infra/export/schedule-piece-export.handler.ts
api/apps/api/src/modules/cost-surface/cost-surface.api.entity.ts
api/apps/api/src/modules/cost-surface/cost-surface.module.ts
api/apps/api/src/modules/cost-surface/cost-surface.service.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/cost-surface-deleted.saga.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/delete-cost-surface.command.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/delete-cost-surface.handler.spec.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/delete-cost-surface.handler.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/delete-cost-surface.module.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/schedule-cost-surface-unused-resources-cleanup.command.ts
api/apps/api/src/modules/cost-surface/delete-cost-surface/schedule-cost-surface-unused-resources-cleanup.handler.ts
api/apps/api/src/modules/cost-surface/dto/cost-surface.serializer.ts
api/apps/api/src/modules/cost-surface/events/cost-surface-deleted.event.ts
api/apps/api/src/modules/projects/delete-project/schedule-project-unused-resources-cleanup.handler.ts
api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/api/src/modules/scenarios/delete-scenario/schedule-scenario-unused-resources-cleanup.handler.ts
api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
api/apps/api/src/utils/acl.utils.ts
api/apps/api/test/project/project-cost-surface.controller.acl.e2e-spec.ts
api/apps/api/test/project/project-cost-surface.e2e-spec.ts
api/apps/api/test/project/project-cost-surface.fixtures.ts
api/apps/geoprocessing/src/modules/unused-resources-cleanup/delete-unused-resources/cost-surface-unused-resources.ts
api/apps/geoprocessing/src/modules/unused-resources-cleanup/delete-unused-resources/unused-resources.module.ts
api/apps/geoprocessing/src/modules/unused-resources-cleanup/unused-resources-cleanup.processor.ts
api/apps/geoprocessing/test/integration/cost-surface/cleanup.fixtures.ts
api/libs/unused-resources-cleanup/src/job-input.ts

Feature/api/mrxn23 97 delete cost surface [MRXN23-97]

---

api/apps/api/src/migrations/api/1691980238543-AddCostSurfaceApiDb.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-metadata.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/project-metadata.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/project-metadata.piece-exporter.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/index.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-metadata.ts

See https://vizzuality.atlassian.net/browse/MRXN23-473

avoid error on export if no scenario has ever been run [MRXN23-473]

---

api/apps/api/src/modules/cost-surface/cost-surface.service.ts
api/apps/api/src/modules/projects/project-cost-surface.controller.ts
api/apps/geoprocessing/src/modules/cost-surface/cost-surface.controller.ts
api/apps/geoprocessing/src/modules/cost-surface/cost-surface.module.ts
api/apps/geoprocessing/src/modules/cost-surface/cost-surface.service.ts

New endpoint in ProjectCostSurfaceController to retrieve Cost Surface tiles.
Implementation is similar to the endpoint for tiles for Geo Features
---

[api] Cost surfaces tiles endpoint [MRXN23-118]

---

api/apps/geoprocessing/src/migrations/geoprocessing/1697102188000-AddProjectsPuIdIndexOnCostSurfacePuData.ts

This will help with the query that does a `UPDATE "cost_surface_pu_data" SET "cost_surface_id" = $1 WHERE "projects_pu_id" = $2` while linking rows of a project's default cost surface to a newly-created project.
context: https://vizzuality.atlassian.net/browse/MRXN23-483

add index to improve performance when updating cost_surface_pu_data [MRXN23-483]

---

api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/projects/projects.project-features.controller.ts
api/apps/geoprocessing/src/modules/features/features.controller.ts
api/apps/geoprocessing/src/modules/features/features.service.ts

New endpoint in ProjectFeaturesController:
- checks if feature belongs to projects + acl
- gets tiles for feature with amounts retrieved from (`geoDB).puvspr_calculations `by `featureId` and `project_pu_id`
---

[api] Add Project Feature tiles endpoint [MRXN23-477]

---

app/hooks/cost-surface/index.ts
app/hooks/map/constants.tsx
app/hooks/map/index.ts
app/hooks/map/types.ts
app/hooks/scenarios/index.ts
app/hooks/scenarios/types.ts
app/layout/project/navigation/hooks.tsx
app/layout/project/navigation/index.tsx
app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/bulk-action-menu/utils.ts
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/modals/delete/index.tsx
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/modals/edit/index.tsx
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/modals/upload/index.tsx
app/layout/project/sidebar/scenario/grid-setup/cost-surface/index.tsx
app/layout/projects/show/map/index.tsx
app/layout/projects/show/map/legend/hooks/index.ts
app/layout/scenarios/edit/map/legend/hooks/index.ts
app/package.json
app/types/api/cost-surface.ts
app/yarn.lock

[N/A]: cost surfaces adjustments after API implementation

---

app/hooks/map/index.ts
app/hooks/map/types.ts
app/layout/projects/show/map/legend/hooks/index.ts
app/layout/scenarios/edit/map/component.tsx
app/layout/scenarios/edit/map/legend/hooks/index.ts

This PR groups binary and continuous features in the map legend. The criteria to difference between binary and continuous is checking the properties `min` and `max` in every feature. These properties are not implemented in the API yet so it's not possible to distinguish between both types of properties right now.
–
https://vizzuality.atlassian.net/browse/MRXN23-488
---

[MRXN23-488]: map legend: merges binary and continuous features

---

app/hooks/map/index.ts

[N/A]: sets individual opacity for conservation areas

---

app/layout/project/navigation/hooks.tsx

[N/A]: removes env environmental to display cost surfaces

---

docs/developers/editors/vscode/configs/launch.json

Auto attach would cause things such as Mapshaper's runCommandsXL() to fail, when running in OCI containers, as VSCode would try to attach to exec'ed child processes.
See: https://github.com/microsoft/vscode-js-debug/issues/374

disable autoAttachChildProcesses in the recommended vscode launch.json config

---

app/hooks/features/index.ts
app/hooks/gap-analysis/index.ts
app/hooks/projects/index.ts
app/hooks/published-projects/index.ts
app/hooks/scenarios/index.ts
app/hooks/solutions/index.ts
app/layout/community/published-projects/list/table/item/component.tsx
app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/list/component.tsx
app/layout/project/sidebar/scenario/grid-setup/features/add/intersect/list/component.tsx
app/layout/project/sidebar/scenario/grid-setup/gap-analysis/list/index.tsx
app/layout/project/sidebar/scenario/solutions/overview/table/table-form/component.tsx
app/layout/project/sidebar/scenario/solutions/target-achievement/list/index.tsx
app/layout/projects/show/scenarios/component.tsx

This PR aims to fix the crashes produced by disabling pagination in several endpoints.
https://vizzuality.atlassian.net/browse/MRXN23-498
---

[MRXN23-498]: fixes many crashes due to disabling pagination

---

api/apps/api/src/migrations/api/1645026803969-AddTokenIdColumnToLocks.ts
api/apps/api/src/migrations/api/1645449750000-SyncPuShapeEnumFromGeoprocessingToApi.ts
api/apps/api/src/migrations/api/1696603545456-AddCostSurfaceLinkingNewEvents.ts
api/apps/api/src/migrations/api/1697210673344-AddMinMaxAmountColumnsToFeatures.ts
api/apps/api/src/modules/cost-surface/adapters/scenario/scenario-cost-surface-api-events.ts
api/apps/api/src/modules/cost-surface/application/scenario/link-cost-surface-to-scenario.handler.ts
api/apps/api/src/modules/cost-surface/infra/project/project-cost-surface-events.handler.ts
api/apps/api/src/modules/cost-surface/infra/scenario/scenario-cost-surface-events.handler.ts
api/apps/api/src/modules/cost-surface/infra/scenario/scenario-cost-surface-queue.provider.ts
api/apps/api/src/modules/geo-features/geo-features.controller.ts
api/apps/api/src/modules/planning-areas/planning-areas.service.ts
api/apps/api/src/modules/projects/projects-crud.service.ts
api/apps/api/src/modules/projects/projects.project-features.controller.ts
api/apps/api/src/modules/scenarios/scenarios.service.ts
api/apps/api/test/projects/cost-surfaces/project-cost-surface.controller.acl.e2e-spec.ts
api/apps/api/test/projects/cost-surfaces/project-cost-surface.e2e-spec.ts
api/apps/api/test/projects/cost-surfaces/project-cost-surface.fixtures.ts
api/apps/api/test/projects/crud/project-get.e2e-spec.ts
api/apps/api/test/projects/projects.fixtures.ts
api/apps/geoprocessing/test/integration/cost-surface/planning-unit-fixtures.ts
api/apps/geoprocessing/test/integration/cost-surface/steps/world.ts
api/libs/api-events/src/api-event-kinds.enum.ts

when uploading a cost surface to a project, a `project.costSurface.shapefile.finished/v1alpha1` API event should be emitted rather than a `scenario.costSurface.finished/v1alpha1`
https://vizzuality.atlassian.net/browse/MRXN23-472

emit correct api events when dealing with cost surface uploads [MRXN23-472]

---

api/apps/api/src/modules/geo-feature-tags/geo-feature-tags.service.ts
api/apps/api/test/geo-features/geo-feature-tags.e2e-spec.ts

https://vizzuality.atlassian.net/browse/MRXN23-316

prevent db deadlocks while updating feature tags [MRXN23-316]

---

app/layout/project/sidebar/project/inventory-panel/features/modals/delete/index.tsx
app/layout/project/sidebar/project/inventory-panel/features/modals/edit-bulk/index.tsx
app/layout/project/sidebar/project/inventory-panel/features/modals/edit/index.tsx
app/layout/project/sidebar/project/inventory-panel/features/modals/upload/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/uploader/component.tsx

https://vizzuality.atlassian.net/browse/MRXN23-500
---

[MRXN23-500]: minor issues in inventory/features

---

app/components/gap-analysis/item/component.tsx
app/hooks/gap-analysis/index.ts
app/layout/project/sidebar/scenario/grid-setup/gap-analysis/index.tsx
app/layout/project/sidebar/scenario/grid-setup/gap-analysis/list/index.tsx

https://vizzuality.atlassian.net/browse/MRXN23-498
---

[MRXN23-498]: removes KM2 units from gap-analysis/target-achivements results

---

app/components/modal/component.tsx
app/layout/project/sidebar/project/inventory-panel/components/inventory-table/row-item/index.tsx

https://vizzuality.atlassian.net/browse/MRXN23-504
---

[MRXN23-504]: fixes sticky behaviour of actions menu on scroll

---

app/hooks/map/constants.tsx
app/hooks/map/index.ts

https://vizzuality.atlassian.net/browse/MRXN23-523
---

[MRXN23-523]: represents cost surfaces with flat ranges with basic colors

---

app/layout/project/sidebar/scenario/grid-setup/cost-surface/index.tsx
app/package.json
app/yarn.lock

https://vizzuality.atlassian.net/browse/MRXN23-521
---

[MRXN23-521]: displays default cost-surface when user clears selection

---

app/hooks/scenarios/index.ts
app/layout/scenarios/edit/map/legend/hooks/index.ts
app/layout/scenarios/reports/solutions/frequency/index.tsx
app/layout/scenarios/reports/solutions/resume/index.tsx
app/layout/scenarios/reports/solutions/solutions-table/index.tsx

[MRXN23-529](https://vizzuality.atlassian.net/browse/MRXN23-529)
[MRXN23-529]: https://vizzuality.atlassian.net/browse/MRXN23-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MRXN23-529] add info to solutions report

---

app/layout/scenarios/reports/solutions/webshot-status/index.tsx
webshot/src/domain/solutions-report/solutions-report.ts

In some cases when generating pdf report for scenario some solutions maps are left empty.
This PR increases webshot timeout from 30 to 60 seconds and in FE increases timeout for setting MARXAN.webshot_ready to true to 10 seconds
Manual testing done with Okavango project - before timeouts increase 3 out of 5 maps were empty, after the increase all 5 maps are printed correctly.
[project_okavango-scenario_new_scenario-run_after.pdf](https://github.com/Vizzuality/marxan-cloud/files/13673979/project_okavango-scenario_new_scenario-run_after.pdf)
[project_okavango-scenario_new_scenario-run_before.pdf](https://github.com/Vizzuality/marxan-cloud/files/13673980/project_okavango-scenario_new_scenario-run_before.pdf)
[MRXN23-530](https://vizzuality.atlassian.net/browse/MRXN23-530)
---
deploying to …

Increase timeouts for scenario report generation [MRXN23-503]

---

app/layout/project/sidebar/scenario/grid-setup/features/add/add-modal/component.tsx

When adding a feature to an scenario several times, we obtain above error, so we just changed the way to obtain the index of the `string[]`
To try to test, it is important to repeat the action of adding and removing a feature several times in a row in different scenarios.
[MRXN23-503](https://vizzuality.atlassian.net/browse/MRXN23-503)
[MRXN23-503]: https://vizzuality.atlassian.net/browse/MRXN23-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FE](fix): Avoid double click when adding feature to scenario [MRXN23-503]

---

app/components/map/legend/types/gradient/index.tsx

Need to test here [https://marxan23.vercel.app/projects/8b02401f-6952-467c-b31c-ef11c21c5536?tab=cost-surface](https://marxan23.vercel.app/projects/8b02401f-6952-467c-b31c-ef11c21c5536?tab=cost-surface)
or see sreenshoot below:
[MRXN23-527](https://vizzuality.atlassian.net/browse/MRXN23-527)
[MRXN23-527]: https://vizzuality.atlassian.net/browse/MRXN23-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[FE](fix): recover zero on cost surface map legend [MRXN23-527] 

---

app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx
app/layout/project/sidebar/scenario/grid-setup/protected-areas/threshold/index.tsx

After clicking save in some cases you go back to the previous tab (Protected areas) or you stay in the same (features).
We should make this consistent. 
This PR is a solution, removing the goBack action when saving threshold and disable mutation when threshold has been not changed, as protected areas are already saved in previous step.   
Also, selected features mutation is disable when there is no changes.
In both cases an info toast has been added:
Here is some extra info about why we are not disabling button and we are just disabling mutations:
[https://axesslab.com/disabled-buttons-suck](https://axesslab.com/disabled-buttons-suck)
[MRXN23-547](https://vizzuality.atlassian.net/browse/MRXN23-547)
[MRXN23-547]: https://vizzuality.atlassian.net/browse/MRXN23-547?atlOrigin=eyJpIjoiNWRkNTljN …

[FE](fix): remove automatic back action when saved PAs and show save btn only when necessary [MRXN23-547]

---

api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/geo-features.e2e-spec.ts

https://vizzuality.atlassian.net/browse/MRXN23-528

report min/max amounts in square km for features from shapefile [MRXN23-528]

---

app/layout/project/sidebar/scenario/grid-setup/features/targets/list/component.tsx
app/layout/scenarios/edit/map/legend/hooks/index.ts

[MRXN23-555](https://vizzuality.atlassian.net/browse/MRXN23-555)
[MRXN23-555]: https://vizzuality.atlassian.net/browse/MRXN23-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FE(fix): show features on gap analysis grid legend

---

app/layout/upcoming-changes/component.tsx
app/layout/upcoming-changes/index.ts
app/pages/index.tsx

Adds _upcoming changes_ banner in homepage.
To display it, add the  `upcomingChanges` key to the `NEXT_PUBLIC_FEATURE_FLAGS` env variable.
https://vizzuality.atlassian.net/browse/MRXN23-560
---

[MRXN23-560] adds upcoming changes banner to homepage

---

api/apps/geoprocessing/src/modules/planning-units/planning-units.job.ts
data/scripts/cost-surface/cost-surface-incorrect-pu-data-purge.py

Also includes script to fix incorrect pu data in the DB
---

fix(Cost Surface): Fixes a bug in the insertion of Cost Surface PUs for projects without a shapefile [MRXN23-525]

---

app/layout/upcoming-changes/component.tsx
app/layout/upcoming-changes/index.ts
app/pages/index.tsx

Adds notice banner for upcoming changes, for MaPP v1 (currently only used in the TNC production environment)
N/A
Banner should be shown in production when enabled via feature flag. Nothing else should break 🙏🏼 .
https://vizzuality.atlassian.net/browse/MRXN23-560
---

adds upcoming changes banner to homepage (cherry-picked change for MaPP v1 production environment) [MRXN23-560]

---

api/apps/api/src/modules/geo-features/geo-feature.measurement-units.spec.ts
api/apps/api/src/modules/geo-features/geo-feature.measurement-units.ts
api/apps/api/src/modules/projects/planning-unit-grid/set-project-grid-from-shapefile.handler.ts
api/apps/api/src/modules/projects/projects.blm.controller.ts
api/apps/api/src/modules/projects/projects.planning-area-and-grid.controller.ts
api/apps/api/src/modules/projects/projects.scenario-comparison.controller.ts
api/apps/api/src/modules/projects/projects.service.ts
api/apps/api/test/projects/crud/projects.e2e-spec.ts
api/apps/api/test/projects/projects.fixtures.ts

Fix my own 🤦🏼 bug that broke stuff because of an improper reliance on falseish values.
N/A
There's a new unit test file, which I believe captures most of the logic and edge cases, including the sad-trombone bug in my previous implementation.
https://vizzuality.atlassian.net/browse/MRXN23-559
---

set min/max correctly when values are zero [MRXN23-559]

---

app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx
app/layout/scenarios/edit/status/actions/done.tsx

This PR revalidates features data after the processing job in the API is done.
https://vizzuality.atlassian.net/browse/MRXN23-569
---

[MRXN23-569]: fixes query invalidation after processing scenario features

---

api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts

Adding aggressive table locks to prevent stale reads from trigger that executes when inserting new `scenarios` rows.
N/A
Create a project with 20ish scenarios. It should almost consistently _fail_ to clone without this change, and it should _always_ clone successfully with this change.
https://vizzuality.atlassian.net/browse/MRXN23-572
---

use table locks to prevent stale reads from trigger [MRXN23-572]

---

app/layout/project/sidebar/header/title/index.tsx
app/layout/project/sidebar/project/header/index.tsx
app/layout/project/sidebar/scenario/header/index.tsx

Fixes updating description of a project.
https://vizzuality.atlassian.net/browse/MRXN23-576
---

[MRXN23-576] fixes updating description of a project

---

app/layout/project/sidebar/scenario/grid-setup/features/target-spf/targets-spf-table/row-item/index.tsx
app/styles/globals.css

This was a visual glitch where rows with long names would grow further its container hiding other elements (like SPF input).
https://vizzuality.atlassian.net/browse/MRXN23-577
---

[MRXN23-577] fixes overflow of row with long names

---

app/layout/project/sidebar/project/inventory-panel/cost-surfaces/index.tsx
app/layout/project/sidebar/project/inventory-panel/cost-surfaces/modals/delete/index.tsx

Prevents select and delete the default cost surface when the checkbox to select all is checked.
---

[N/A] prevents selecting default cost surface

---

api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts
api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
api/apps/api/test/projects/crud/delete-project.e2e-spec.ts
api/apps/api/test/upload-feature/upload-feature.e2e-spec.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts
api/apps/api/test/utils/wait-for-feature-to-be-ready.utils.ts
api/apps/api/test/utils/wait-for.utils.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts
api/apps/geoprocessing/src/modules/cleanup-tasks/cleanup-tasks.service.ts

Complements the original fix to MRXN23-518, adding deletion of dangling `feature_amounts_per_planning_unit` rows while deleting a feature.
https://vizzuality.atlassian.net/browse/MRXN23-518
---

delete dangling feature_amounts_per_planning_unit data straight away when deleting a feature [MRXN23-518]

---

app/hooks/cost-surface/index.ts
app/hooks/projects/index.ts

This PR delays the query invalidation of cost surfaces up to one second so it avoids falling in limbo when the API processes the cost surface between the POST callback and the first `/status` polling. If the API takes more than that second into processing the cost-surface, the `/status` will in charge of telling the application when the query invalidation should occur.
For future reference:
https://vizzuality.atlassian.net/browse/MRXN23-531
---

[MRXN23-531]: invalidates cost-surface fetch a second later of creation

---

api/apps/api/src/migrations/api/1708525796000-PrepareToStoreListOfRelevantFeaturesDataAlongsideFeatures.ts
api/apps/api/src/modules/geo-features/geo-feature.api.entity.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1708524274000-AddStableIdsToFeaturesDataRows.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts
docs/README_revision-of-feature-split-functionality-in-marxan-cloud-v2.md

Foundation work for the Make Splits Great Again epic.
This PR adds table columns and includes TypeORM entities changes to accommodate the data needed to link features to subsets of `features_data` at the outset, rather than by running spatial queries when needed.
https://vizzuality.atlassian.net/browse/MRXN23-588
https://vizzuality.atlassian.net/browse/MRXN23-589
https://vizzuality.atlassian.net/browse/MRXN23-590

handle stable id for features data [MRXN23-588] [MRXN23-589] [MRXN23-590]

---

api/apps/api/src/migrations/api/1708525796000-PrepareToStoreListOfRelevantFeaturesDataAlongsideFeatures.ts
api/apps/api/src/modules/geo-features/geo-feature.api.entity.ts
api/apps/api/test/upload-feature/upload-feature.fixtures.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-custom-features.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/project-custom-features.piece-importer.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1708524274000-AddStableIdsToFeaturesDataRows.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-custom-features.ts
api/libs/geofeatures/src/geo-feature.geo.entity.ts
docs/README_revision-of-feature-split-functionality-in-marxan-cloud-v2.md

This PR adds the ability to export and import metadata for `(apidb)features` and `(geodb)features_data` that handles how features are linked explicitly to their spatial data, as part of the MSGA (Make Splits Great Again) plan (see #1654).
https://vizzuality.atlassian.net/browse/MRXN23-594
https://vizzuality.atlassian.net/browse/MRXN23-595
https://vizzuality.atlassian.net/browse/MRXN23-596
https://vizzuality.atlassian.net/browse/MRXN23-597

handle feature to features data links through cloning process [MRXN23-594] [MRXN23-595] [MRXN23-596] [MRXN23-597]

---

.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/deploy-to-kubernetes.yml
.github/workflows/e2e-client.yml
.github/workflows/publish-marxan-docker-images.yml
.github/workflows/publish-webshot-docker-images.yml
.github/workflows/tests-api-e2e.yml
.github/workflows/tests-api-unit.yml
.github/workflows/tests-backend-build-oci-images.yml
.github/workflows/tests-geoprocessing-e2e.yml
.github/workflows/tests-geoprocessing-unit.yml
.github/workflows/webshot-build.yml

https://vizzuality.atlassian.net/browse/MRXN23-586
Exceptions so far: Azure's own actions, and (most of) GitHub's own actions, which haven't released versions that use Node v20 yet (some of these have PRs being reviewed 🤞🏼)

update GH Actions dependencies for which a version that uses Node v20 is available from upstream maintainers [MRXN23-586]

---

api/apps/api/src/modules/analysis/providers/shared/__mocks__/scenario-planning-unit-geo.data.ts
api/apps/api/src/modules/scenarios/dto/scenario-planning-unit.serializer.ts
api/apps/api/src/modules/scenarios/planning-units/scenario-planning-units.service.ts
api/apps/api/test/scenario-input-files/scenario-cost-surface/scenario-cost-surface.fixtures.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-cost-surfaces.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-planning-units-data.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-planning-units-data.piece-importer.ts
api/apps/geoprocessing/src/modules/scenario-planning-units-inclusion/scenario-planning-units-inclusion-processor.ts
api/apps/geoprocessing/test/integration/planning-unit-inclusion/world.ts
api/libs/cloning/src/infrastructure/clone-piece-data/scenario-planning-units-data.ts
api/libs/scenarios-planning-unit/src/scenarios-planning-unit.geo.entity.ts

The `lockStatusSetByUser` scenario PU flag had not been added to piece exporters and importers, leading to loss of this data when cloning scenarios. This change fixes this.
Set some PUs to excluded, some to available and some to included for a scenario.
Clone the scenario (or its whole parent project). The new copy of the scenario must preserve the statuses set manually in the source scenario.
https://vizzuality.atlassian.net/browse/MRXN23-600
---

 export and import lockStatusSetByUser flag [MRXN23-599]

---

api/apps/api/src/migrations/api/1710069730000-AddStableIdsToCostSurfaces.ts
api/apps/api/src/modules/cost-surface/cost-surface.api.entity.ts
api/apps/api/src/modules/scenarios/input-files/input-params/input-parameter-file.provider.spec.ts
api/apps/geoprocessing/src/export/pieces-exporters/project-cost-surfaces.piece-exporter.ts
api/apps/geoprocessing/src/export/pieces-exporters/scenario-metadata.piece-exporter.ts
api/apps/geoprocessing/src/import/pieces-importers/project-cost-surfaces.piece-importer.ts
api/apps/geoprocessing/src/import/pieces-importers/scenario-metadata.piece-importer.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/project-cost-surface.piece-exporter.e2e-spec.ts
api/libs/cloning/src/infrastructure/clone-piece-data/project-cost-surfaces.ts

Allow scenarios to be linked correctly to copies of cost surfaces within cloned projects.
https://vizzuality.atlassian.net/browse/MRXN23-606
---

link scenarios correctly to cost surfaces after cloning [MRXN23-606]

---

app/layout/project/sidebar/scenario/grid-setup/features/target-spf/all-targets/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/modals/edit/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/targets-spf-table/row-item/details/index.tsx

This PR fixes an issue were the features listed were defaulted to the app's default values (for target and spf) when one of the features was edited by selecting it (through the checkbox) and clicking on the edit button in the floating menu.
The PR also displays the current values for target and spf when the user edits their values instead of defaulting to the app's default values. If more than one features are selected to edit, then the app's default values will display though.
https://vizzuality.atlassian.net/browse/MRXN23-604
---
to the deploy checklist …

[MRXN23-604] fixes target/spf values after editing one of them

---

api/apps/api/src/migrations/api/1708099064649-AddFeatureShapefileApiEvents.ts
api/apps/api/src/modules/analysis/providers/shared/__mocks__/scenario-planning-unit-geo.data.ts
api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/geoprocessing/test/integration/cloning/fixtures.ts
api/apps/geoprocessing/test/integration/cloning/piece-exporters/scenario-metadata.piece-exporter.e2e-spec.ts
api/apps/geoprocessing/test/steps/given-scenario-pu-data-exists.ts

Fixes a few non-passing tests due to previous changes, plus small tweaks/notes
---

fix(Tests): Fixes a couple of tests, plus small tweaks

---

app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/index.tsx
app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/index.tsx

https://vizzuality.atlassian.net/browse/MRXN23-600
---

[MRXN23-600] adds scroll to PU form in small viewports

---

app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/buttons/index.tsx
app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions-summary/index.tsx
app/layout/project/sidebar/scenario/grid-setup/planning-unit-status/actions/index.tsx
app/store/slices/scenarios/edit.ts

Adds loaders after saving selection of planning units (clicking on _save selection_) and clear them (clicking on _clear_).
---

[N/A]: planning units: adds loaders after saving selection and clearing

---

app/hooks/map/index.ts

This PR ensure if possible to interpolate values when the `min` and `max` values of the cost-surface layer are equal by adding 1 to the `max` value.
https://vizzuality.atlassian.net/browse/MRXN23-618
---

[MRXN23-618] cost surface layer: ensures interpolation is possible

---

api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts

When uploading large CSV files, it would crash when trying to insert the CSv import submitted api_event, because the whole is included in the data property. It will now be ignored and not included, as it might be useful but not much, and the files could be as if larger.
https://vizzuality.atlassian.net/browse/MRXNM-41

[MRXN-41] Ignores CSV file as part of the API Event data column

---

api/apps/api/src/modules/geo-features/geo-features.service.ts
api/apps/api/src/modules/geo-features/import/features-amounts-upload.service.ts

https://vizzuality.atlassian.net/browse/MRXN23-609
This is only a fix for the bug. I recommend to add a migration that fixes existing duplicated data as a separate PR, to keep things manageable and fast-track this fix (if approved) to production.
There are no tests with this fix. It's going to be complicated to test this exhaustively within a limited development effort.

avoid inserting duplicate feature_amounts_per_planning_unit rows over and over [MRXN23-609]

---

api/apps/api/src/modules/scenarios-features/compute-area.service.spec.ts
api/libs/feature-amounts-per-planning-unit/src/repository/memory-feature-amounts-per-planning-unit.repository.ts
api/libs/feature-amounts-per-planning-unit/src/repository/typeorm-feature-amounts-per-planning-unit.repository.ts

https://vizzuality.atlassian.net/browse/MRXNM-43

filter out pusvpr rows where amount is zero [MRXNM-43]

---

app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/modals/delete/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/modals/edit/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx

This PR removes a side effect triggered when the user searched for some targets and the edited values were reverted to app's defaults after rendering the filtered results.
https://vizzuality.atlassian.net/browse/MRXN23-624
---

[MRXN23-624] targets: sync local with remotes changes in targets

---

api/apps/api/src/modules/scenarios-features/scenario-features-gap-data.service.ts
api/apps/api/src/modules/scenarios-features/scenario-features-output-gap-data.service.ts
api/apps/api/src/modules/scenarios/scenarios.controller.ts
api/apps/geoprocessing/src/migrations/geoprocessing/1710497811000-IncludeDecimalDigitsWhenRoundingTargetAndCurrentDataInGapDataViews.ts
api/libs/features/src/scenario-features-gap-data.geo.entity.ts
api/libs/utils/src/numeric-string-to-float.utils.spec.ts
api/libs/utils/src/numeric-string-to-float.utils.ts
app/components/gap-analysis/item/component.tsx

https://vizzuality.atlassian.net/browse/MRXN23-601

pass through gap data (target/met) values with rounding to 4 decimal digits [MRXN23-601]

---

app/layout/project/sidebar/scenario/grid-setup/features/target-spf/bulk-action-menu/modals/edit/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/index.tsx
app/layout/project/sidebar/scenario/grid-setup/features/target-spf/targets-spf-table/index.tsx
app/utils/numbers.ts

This PR solves the casuistic of an user being able to perform unwanted changes when performing certain bulking actions.
---

feature bulking: added edition modes

---

infrastructure/base/main.tf
infrastructure/base/modules/bastion/main.tf
infrastructure/base/modules/bastion/variables.tf
infrastructure/base/modules/network/outputs.tf

- link bastion network security group (allows public ssh access on ipv4) to bastion host NIC
- add a small swapfile and enable it as swap when provisioning the bastion host VM
- use latest Ubuntu LTS base image
Re-creating the bastion host VM via Terraform should do all the above.
https://vizzuality.atlassian.net/browse/MRXNM-52
---

infra(chore): update bastion host vm setup [MRXNM-52]
